export default function(add){
add('kennen','Kennen','A','PTA','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Boots; Mercury’s Treads bei zusätzlichem AP/CC.',
'Ragnarok nimmt Kennens Stuns die wichtigste Schutzfunktion. Sein E und die Distanz zum Turm entscheiden weiter, ob Olaf Kontakt bekommt.',
'Nach verbrauchtem E sind drei Autos realistisch und das Killfenster kurz. Conqueror lädt gegen ständigen Rückzug häufig zu spät auf.',
'Kennen kontrolliert mit Reichweite. Olaf gewinnt nur mit Q-Treffer und langem Rückweg. CS abgeben, statt für jeden Minion einen Auto zu nehmen.',
'Hinter Minions Q blocken; verstärkten W-Auto beobachten. Nach offensivem E und ohne vorbereitete Stun-Marken anlaufen.',
'R vor dem entscheidenden Stun oder zum Befreien nutzen. Kennens R verursacht trotzdem Schaden; angeschlagen kein automatischer Sieg.',
'E-Flucht, passive Stun-Marken, W-verstärkter Auto, R-Schaden.',
'E verbraucht und Kennen weit vom Turm. R fehlt: auch ein zweiter Angriff nach Reset möglich.',
'R ohne erreichbares Ziel zünden; mehrfach gratis W-Autos nehmen; mit wenig HP in seine gesamte R laufen.',
'Anfangs auf eigener Seite sammeln und ausdünnen. Nach erzwungenem E Slowpush und Crash. Kein erzwungener erster Cheater gegen sein Poke.',
'Q aus sicherem Winkel treffen, anlaufen und E-Flucht abwarten. Ghost für Restdistanz; R beim Stun, Auto–W–Auto–Auto und kurze Qs.',
'Stridebreaker für Kontakt, danach Maw of Malmortius bei relevantem AP-Burst. Ravenous Hydra als Alternative, wenn Poke statt Flucht das Problem ist.',
'Sterak’s gegen gemischten Burst statt Maw; Fiendhunter Bolts bei Vorsprung und zuverlässig erreichbaren Backline-Zielen.',
'1 Item: Stride eröffnet Catches. 2 Items: mit MR gute Side bei verfügbarer R. 3 Items: Kennen kann sicher clearen; sein Teamfight bleibt stärker als sein isoliertes Duell.',
'Lass dich vor 6 nicht für jeden CS herunterpoken. Nutze Kennens E als Startsignal und halte die Lane lang. Mit R kannst du seinen Stun übergehen, aber nicht seinen Schaden.',
'Conqueror, wenn Kennen nur dein Lane-Gegner ist und du im Gesamtspiel hauptsächlich mehrere Bruiser bekämpfst.');
add('kled','Kled','E','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh gegen sein Auto-Fenster.',
'Zwei HP-Phasen und Remount bestrafen Olafs Low-HP-Fights. Kled kann mit W und E einen scheinbar gewonnenen Kampf drehen.',
'Dismount, Courage und erneuter Kontakt machen das All-in länger als einen PTA-Proc. Conqueror passt zur notwendigen zweiten Schadensphase.',
'Olaf gewinnt längeren Kontakt nach verfehltem Q. Gegen getroffenes Q nicht bis zum Rückzug überdehnen. Kleds zweite Lebensphase mitrechnen.',
'W auf Minions auslösen lassen; nach Ende der schnellen Autos angreifen. Seine weiteren Autos verkürzen den W-Cooldown, also kein starres langes Fenster annehmen. E2-Zugang und Courage prüfen.',
'Kled-R eröffnet Ganks und Rotationen. Olaf-R hilft gegen CC, verhindert aber weder Kleds Remount noch dessen Schaden.',
'W-Autos mit Cooldown-Verkürzung, Q-Zug/Slow, E-Recast, unmounted Q und Courage. Q hat seit 25.14 keine eingebaute Heilungsreduktion mehr.',
'W verbraucht und weiterer Auto-Zugang begrenzt; E verfehlt; Kled unmounted mit wenig Courage. Bei voller Courage kommen Remount-HP sofort, daher nicht auf eine letzte Animationslücke setzen.',
'Remount ignorieren; mit wenig HP seine volle W tanken; ein starres W-Fenster trotz weiterer Kled-Autos annehmen; mit altem Q-Antiheal-Wissen planen.',
'Wave nahe eigener Seite halten und nicht riesig werden lassen. Nach seinem Roam Crash erzwingen, falls kein sinnvoller Gegenlauf möglich ist.',
'Q-Poke, W-Verbrauch abwarten, Q–Auto–E. Beim Dismount Flucht-Q antizipieren; nur weiter, wenn du ihn vor Remount töten oder die zweite Phase überstehen kannst.',
'Ravenous Hydra für Reset-Sustain, dann Death’s Dance. Stridebreaker, wenn seine E-Flucht statt Lane-HP das Hauptproblem ist.',
'Sterak’s als Burstpuffer; Executioner’s gegen weitere Heiler, aber nicht als verlässlichen Schalter zum Abschalten von Kleds Remount behandeln.',
'1 Item: sein W/Remount bleibt gefährlich. 2 Items: Armor und eigener Sustain helfen bei sauberem Einstieg. 3 Items: kein blinder Statcheck; HP-Phasen entscheiden weiterhin.',
'Lass Kled zuerst seine W-Autos verbrauchen. Plane den Kampf über Dismount hinaus und prüfe Courage. Ein abgebrochener Angriff ist besser als ihm auf wenig eigenen HP den Remount zu schenken.',
'PTA nur für ein Team mit kurzen Catches; auf der Side bleibt Conqueror die verlässlichere Wahl.');
add('malphite','Malphite','B','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Keine Pflicht-Upgrades; Mercury’s bei AP-Build und passender Comp.',
'Olaf kann CC neutralisieren und mit E Armor umgehen. Malphite kann jedoch kurz traden, disengagen und später hohen Teamfight-Wert liefern.',
'Schild, Armor und wiederholte Q-Rückzüge verlängern das Matchup. Drei schnelle Autos allein lösen die effektiven HP nicht.',
'Olaf im langen Kontakt, Malphite im einzelnen Q-Trade. Schild mit Q brechen, aber nicht durch eine große Wave nachlaufen.',
'Nach Q-Verbrauch Druck, sofern du HP und Platz hast. E-Attack-Speed-Debuff vor 6 respektieren; nicht nur Autos in seinen aktiven defensiven Trade drücken.',
'R verhindert den Knock-up, wenn rechtzeitig aktiv, oder befreit nach Kontrollverlust. AP-Malphite hat weiterhin echten Burst. R nicht für einen bloßen Q-Poke verschwenden.',
'Passive Schild, E-Attack-Speed-Reduktion, Q-Temposteal, R-Burst.',
'Q/E verbraucht bei langer Lane; R fehlt nach misslungenem Engage. Schild noch nicht regeneriert erleichtert den nächsten Trade.',
'Armor-stapelnden Malphite nur mit Autos bekämpfen; Q-Chases unter Turm; ohne HP-Puffer AP-R unterschätzen.',
'Slowpush bei HP-Vorteil, sonst Bounce zu dir. Freeze zwingt ihn zu Q-Farm und Mana-Ausgaben. Crash vor Reset vollständig machen.',
'Q zum Schildbrechen, nach Q-Ende erneut treffen, Auto–E–W–Auto. Kurze Äxte und E-Zyklen; abbrechen, wenn er sicher zum Turm kommt.',
'Ravenous Hydra für Sustain; Black Cleaver als zweites gegen Armor, wenn auch dein Team davon profitiert. Stridebreaker bei dauerhaftem Disengage statt Hydra.',
'Maw gegen AP-Burst; Sterak’s gegen gemischte Gefahr. Kein BotRK-Rush allein wegen seiner HP: Armor reduziert dessen physischen Zusatzschaden.',
'1 Item: Sustain schafft Druck. 2 Items: E und Armor-Shred erlauben längere Duelle. 3 Items: Malphite muss nicht duellieren, um mit R das Gesamtspiel zu gewinnen.',
'Gewinne über wiederholte kontrollierte Trades und Wave-Druck. Behalte genug HP für einen möglichen AP-Burst. Deine bessere Side ersetzt keine rechtzeitige Antwort auf seine Teamfight-R.',
'PTA, wenn Malphite nur Waveclear spielt und du ansonsten vier fragile Ziele mit kurzem Kontakt bekämpfst.');
add('mordekaiser','Mordekaiser','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Frühe Boots zum Q/E-Dodgen; Mercury’s bei AP-lastiger Comp.',
'Olaf kann Morde über langen Kontakt schlagen und seine R vor dem Banish verhindern. Wer zu spät R drückt, muss den Realm samt Stat-Steal ausspielen.',
'Mordes W-Schild und passive Schadenszone verlangen längeren DPS. Conqueror bleibt über seine Schildphase nützlich.',
'Olaf meist stärker mit Q-Resets. Nicht unnötig isolierte Qs nehmen; seitlich statt gerade auf ihn zulaufen.',
'Nach verfehltem E/Q gehen, bevor W viel Ressource hat. E zwischen Autos; bei großem W-Schild nicht den gesamten eigenen HP-Puffer aufbrauchen.',
'Olaf-R vor Abschluss von Mordes R verhindert den Banish. Bereits im Death Realm kannst du ihn mit R NICHT verlassen; R hilft dort trotzdem im Duell.',
'Isoliertes Q, E, W-Schildressource, passive Zone, R-Banish/Stat-Steal.',
'E verfehlt, Q verbraucht, W gerade genutzt. R-CD erlaubt aggressivere Waveposition ohne Realm-Falle.',
'R als nachträglichen Realm-Cleanse behandeln; isolierte Qs tanken; gegen volles W auf sehr wenig HP committen.',
'Früher Slowpush möglich, dann auf eigener Seite halten. Nach 6 nur weit vorschieben, wenn R und Jungle-Information vorhanden sind.',
'E seitlich dodgen, Q treffen, Auto–W–Auto und E. R rechtzeitig bei drohendem Banish; kurze Qs sichern Kontakt, W-Schild mit planbarem HP-Puffer durcharbeiten.',
'Ravenous Hydra für Side-Sustain, danach Maw. Stridebreaker statt Hydra, wenn du außerhalb der Lane häufiger Ziele erreichen musst.',
'Spirit Visage später bei mehreren AP-Quellen und zusätzlicher Verbündetenheilung. Black Cleaver erst gegen relevanten Armor-Kauf; QSS nicht als Realm-Lösung kaufen.',
'1 Item: Olaf hat gute Fenster, Morde mit vollem W bleibt gefährlich. 2 Items: Maw stabilisiert. 3 Items: R-Timing, Antiheal und defensive Builds entscheiden; kein bedingungsloser Sieg.',
'Bestrafe verfehltes E und verbrauchtes W. Drücke R rechtzeitig, wenn du den Death Realm verhindern willst. Nach dem Banish geht es ums Gewinnen des Duells, nicht ums nachträgliche Reinigen.',
'PTA für kurze Backline-Catches möglich, wenn du Morde nicht dauerhaft auf der Side durchkämpfen musst.');
add('nasus','Nasus','C','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Boots zum Verfolgen; Plated Steelcaps vor starken Q-Duellen.',
'Olaf kann frühes Stacking stark bestrafen und Wither mit R übergehen. Nasus-R und ausreichend Stacks können das Duell trotzdem drehen.',
'Hohe HP, Heilung und wiederholte Qs machen sein R-All-in lang. PTA ersetzt keinen Plan, seine R auslaufen zu lassen.',
'Olaf stärker. Zwischen Nasus und Nahkämpfer stellen, ohne gegnerischen Jungle zu ignorieren. Q nur so werfen, dass du nicht ungewollt die ganze Wave schnell pushst.',
'Jeden Q-Last-Hit in Reichweite bedrohen. Nach Q-Nutzung Auto–E-Trade; gegen E-Max nicht unnötig in der Zone stehen.',
'Wither ist mit eigener R übergehbar, Nasus-R gibt aber massive Kampfstärke. Seine R ziehen und auslaufen lassen, wenn der Kill nicht klar ist.',
'Q-Stacks, W-Wither, E-Armor-Reduktion, R-HP und beschleunigte Q-Nutzung.',
'R beendet und Q gerade genutzt. W verbraucht vor 6. Ein Q auf Minion ist nur ein kurzes Fenster, kein langer Freifahrtschein.',
'Freies Farmen durch endloses Autopushen; in E stehen bleiben; lange in aktive Nasus-R hineinrennen, nachdem eigene R auslief.',
'Frühen Crash in Freeze auf eigener Seite umwandeln. Tiamat verschieben, wenn der Freeze real CS verweigert. Bei Roam erst vollständig crashen.',
'Q bei seinem Last-Hit, Auto–E, mit W nur bei echtem Anschluss verlängern. R auf Wither im Commit; falls Nasus-R das Kräfteverhältnis kippt, per Q Abstand schaffen.',
'Stridebreaker, wenn Kontakt und Freeze wichtig sind; Ravenous Hydra nach Ende der Denial-Phase für Side-Sustain. Zweites Black Cleaver gegen Armor oder Death’s Dance gegen AD-Druck.',
'Executioner’s, wenn seine Heilung ein tatsächliches All-in kippt. Sterak’s gegen Q-Burst. BotRK nur bei viel HP und ausreichend eigenem Überleben.',
'1 Item: Olaf bei verweigerten Stacks gut. 2 Items: Stackstand wird zentral. 3 Items: Nasus kann das 1v1 gewinnen; frühe Türme und Rotationen statt stiller Farmvertrag.',
'Dein Vorteil entsteht aus verweigerten Stacks. Halte die Wave so, dass Nasus für jeden Q bezahlen muss. Erzwinge nicht den kompletten Kampf durch seine R, wenn du danach ein besseres Fenster bekommst.',
'PTA bei kurzem Carry-Zugang im Gesamtspiel; Conqueror behalten, wenn Nasus dein dauerhafter Side-Auftrag ist.');
add('ornn','Ornn','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Frühe Boots zum Q/E-Ausweichen; Upgrades nach Comp.',
'Olaf kann Ornn im langen Fight bedrängen und ab 6 dessen CC-Kette übergehen. Ornn bleibt mit Waveclear und Team-Scaling nützlich.',
'Armor, HP und mehrere Schild-/Defensivkäufe verlangen nachhaltigen Schaden. Kurzer PTA-Burst ist selten das entscheidende Killfenster.',
'Olaf im langen Kontakt. Nach Ornn-Q vorrücken, nicht entlang der entstehenden Säule verfolgen.',
'W-Flammen seitlich verlassen und Brittle-Proc vermeiden. Nach E-Verbrauch längeres All-in, sofern keine große gegnerische Wave anliegt.',
'R kann Knock-ups verhindern, aber W/Brittle-Schaden bleibt. Eigene R nicht zu früh aus Distanz starten, wenn Ornn mit E abdrehen kann.',
'W/Brittle, Q-Säule, E-Wandknock-up, R-Doppelkontakt.',
'W und E verbraucht. Fehlendes R macht Gank-Setup und Selbstverteidigung schwächer.',
'Neben Säule/Wand stehen; gesamten W-Kegel tanken; Ornn-Skalierung unterschätzen, nur weil du auf der Side mehr Schaden machst.',
'Slowpush, nach Crash zurückbouncen lassen. Freeze zwingt ihn aus sicherer Q-Farm. Hydra-Clear nutzen, wenn du früh rotieren statt einfrieren willst.',
'Q treffen, seitlich aus W laufen, nach E Auto–W–Auto–E. Fluchtweg mit kurzen Qs sichern; R für Knock-up im tatsächlichen Commit.',
'Ravenous Hydra für Sustain und Push, danach Black Cleaver gegen Armor. Stridebreaker, wenn er häufig knapp entkommt.',
'Sterak’s gegen Team-Burst; Maw bei AP-Gefahr. BotRK erst bei hohem HP-Anteil und eigenem Überleben, nicht blind gegen Armor.',
'1 Item: gute Drucklane. 2 Items: anhaltender Schaden bedroht Ornn auf langer Side. 3 Items: meist weiter Side-Druck, aber seine Upgrades und Engage stärken das gegnerische Team.',
'Weiche W seitlich aus und greife nach E an. Zwinge Ornn aus sicherer Reichweite, statt ihn unter Turm zu jagen. Übersetze Side-Druck rechtzeitig in Objectives, bevor sein Team-Scaling zählt.',
'PTA gegen vier fragile Teamgegner möglich, wenn Ornn nur gehalten wird.');
add('pantheon','Pantheon','B','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Plated Steelcaps gegen Q/Auto-Druck; kein automatischer Mercury-Kauf nur für W.',
'Olaf gewinnt längeren Kontakt nach Pantheons defensivem E. Pantheon kontrolliert kurze Bursttrades und kann mit Q auf niedrigen HP abschließen.',
'E unterbricht Olafs sinnvollen Auto-Schaden; Q/E können Conqueror vor dem anschließenden Fight vorbereiten. PTA ist erst nach E zuverlässig.',
'Pantheon mit sicherem Q-Poke, Olaf bei langem Q-Chase. Nicht für Low-HP-Passive in Q-Execute-Reichweite bleiben.',
'Passive Stacks beachten. Nach W-Kombo und E-Ende re-engagen; während frontalem E nicht W und alle Autos verbrauchen.',
'R neutralisiert W-Stun, nicht seinen Schaden. Pantheon-R-Roams mit Crash beantworten oder rechtzeitig folgen, ohne blind hinterherzulaufen.',
'Empowered W, E-Schadensblock von vorne, Q-Execute, passive Stacks.',
'E beendet und W fehlt; Q verfehlt verbessert den Einstieg. Sein R-Roam gibt ein Wave-/Turmfenster.',
'Frontal in E burstieren; auf wenig HP Q unterschätzen; seinen Roam ohne Ping und Gegenwert zulassen.',
'Früh auf eigener Seite halten. Nach seinem E einen Slowpush beginnen. Bei R-Roam sofort prüfen, ob Crash/Turm sicher mehr bringt als verspätetes Folgen.',
'Q-Poke, W-Kombo mit eigenem W überstehen, E auslaufen lassen oder sicher hinter ihn gelangen. Dann Auto–E–Auto und Q-Chase; R auf Stun im Commit.',
'Ravenous Hydra für Poke-Sustain, danach Death’s Dance. Stridebreaker, wenn er nach E regelmäßig außer Reichweite kommt.',
'Sterak’s gegen Burst; Armor vor zusätzlichem reinen DPS bei Rückstand. Fiendhunter Bolts nur, wenn seine E bereits zuverlässig gezogen wird.',
'1 Item: Sustain verbessert die Lane. 2 Items: längere Duelle oft gut für Olaf. 3 Items: Pantheons Armor-Penetration hält ihn gefährlich; Burst und E-Positionierung bleiben relevant.',
'Behandle sein E als Pause für deinen großen Schaden. Überstehe den ersten Burst und kämpfe danach weiter. Bleibe nicht mit minimalen HP in Q-Reichweite.',
'PTA bei verlässlichem Kontakt nach E und vielen kurzen Team-Catches; Lane-Conqueror ist keine Comp-Pflicht.');
add('poppy','Poppy','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps bei AD-lastiger Comp, sonst Basis-Boots genügen früh.',
'Olaf hat keinen normalen Dash, den Poppy-W ausschaltet, und kann ihre CC-Verteidigung mit R übergehen. Wandposition und Q-Schaden bleiben wichtig.',
'Schild, Armor und kurze Rückzüge machen mehrere Schadensrotationen nötig. Conqueror passt zum anschließenden langen Nahkampf.',
'Olaf bei langem Kontakt. Q-Zone verlassen, statt beide Treffer zu nehmen. Buckler nur betreten, wenn das keinen Wandstun vorbereitet.',
'Offene Lane-Seite nutzen. Nach Q/E-Verbrauch anlaufen und ihren Schild-Pickup verweigern, wenn sicher.',
'R verhindert Wegschleudern/Knock-up bei aktivem Olaf-R. Vor Ablauf Kontakt halten; Poppy kann W-Tempo zum Auslaufen deiner R nutzen.',
'E-Wandstun, Q-Doppeltreffer, passive Buckler, W-Tempo, R-Disengage.',
'E verfehlt/ohne Wandwert, Q verbraucht, Schild nicht erreichbar. R fehlt erleichtert den nächsten Chase.',
'An einer Wand traden; im zweiten Q-Treffer stehen; R aus großer Entfernung zünden und auslaufen lassen.',
'Auf eigener Seite mit Raum zur offenen Lane halten. Slowpush nach guten Trades; unter Turm keinen E-Wandwinkel anbieten.',
'Q treffen, diagonal aus ihrer Q-Zone gehen, Auto–E. Nach E Auto–W–Auto; R gegen ihren tatsächlichen Disengage, nicht schon beim ersten Poke.',
'Ravenous Hydra für Sustain, danach Black Cleaver bei Armor oder Death’s Dance bei AD-Druck. Stridebreaker, wenn W-Tempo Kontakt verhindert.',
'Sterak’s als Burstpuffer; zusätzliche Armor nach Gegnerteam. Crit nur mit Vorsprung und nach defensiver Basis, wenn sie nicht Armor stapelt.',
'1 Item: gute lange Trades. 2 Items: Shred und Sustain stärken Side. 3 Items: Poppy kann stallen; Teamfight-Peel kann deine Backline-Ziele dennoch schützen.',
'Bleib weg von Wänden und verlasse ihre Q-Zone. Wenn E weg ist, kannst du lange kämpfen. Spare R für das tatsächliche Wegschleudern und halte anschließend Kontakt.',
'PTA, wenn kurze Catches der gegnerischen Carries wichtiger sind als Poppys Side.');
add('quinn','Quinn','B','PTA','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Plated Steelcaps gegen Auto-Poke.',
'Quinn kann Olaf vor 6 auf Abstand halten. Nach verbrauchtem Vault und mit R/Ghost wird ihr kurzer Kontaktverlust häufig nicht mehr ausreichend.',
'Nach E entsteht ein kompaktes Fenster für drei Autos. Langes Aufladen ist gegen ihr ständiges Spacing seltener realistisch.',
'Quinn bestimmt die ersten Autos. Olaf nur mit Q-Treffer und freier Chase-Linie stärker; nicht die halbe HP-Leiste für frühe CS zahlen.',
'Q durch Minions abfangen lassen; E herauslocken. Ghost erst nutzen, wenn der Rückweg lang genug ist und nicht direkt ihr Turm wartet.',
'Olaf-R hilft gegen Vault-CC und Nearsight, aber Quinns eigene Bewegung bleibt. Ihre Roams früh pingen und Wave bestrafen.',
'E-Vault, Q-Nearsight, Harrier-Marken/Tempo, R-Roams.',
'E verbraucht und Q verfehlt/auf CD; Quinn zu weit vom Turm. Nach Rückkehr von Roam nicht ohne Vision ambushen.',
'R mit Kontaktgarantie verwechseln; ihr in unaufgedeckten Jungle folgen; drei Autos erzwingen, während die Wave dich tötet.',
'Früh ausgedünnte Wave vor eigenem Turm. Nach misslungenem E-Chase resetten oder crashen. Roams durch schnellen Crash beantworten.',
'Q treffen und anlaufen; E abwarten, dann Ghost/Stride zum Anschluss. R gegen Unterbrechung, Auto–W–Auto–Auto; Äxte kurz in Fluchtrichtung.',
'Stridebreaker, danach Death’s Dance gegen AD oder Sterak’s bei gemischtem Burst. Ravenous nur, wenn du sonst aus der Lane gepokt wirst.',
'Randuin’s gegen mehrere Crit-Ziele. Fiendhunter Bolts bei sicherem Kontakt und Vorsprung; keine frühe gläserne Crit-Linie aus Rückstand.',
'1 Item: Stride ermöglicht echte Catches. 2 Items: Armor hilft beim Einstieg. 3 Items: Quinn kann kiten/roamen; offenes 1v1 bleibt von E und deiner R abhängig.',
'Bewahre HP, bis Quinn E ausgegeben hat. Dann nutze die lange Lane mit Ghost und R. Wenn sie roamt, nimm sicheren Wave- und Turmwert statt ihr blind nachzulaufen.',
'Conqueror bei mehreren tankigen Melees im Gegnerteam, sofern Quinn nicht dein wichtigstes Killziel bleibt.');
add('renekton','Renekton','C','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh bei gleichmäßiger Lane.',
'Renekton gewinnt vorbereitete Fury-Bursttrades und kann Olafs Schild brechen. Olaf gewinnt, wenn er nach der Kombo längeren Kontakt hält.',
'Renektons R-HP und mehrere E-Bewegungen verlängern den Kampf. Der wichtige Schaden kommt nach seinem Burst, nicht zwingend in drei frühen Autos.',
'Olaf im langen Fight; Renekton-Q gewinnt sichere kurze Trades. Fury nicht gratis an der Wave aufbauen lassen, ohne dabei den Wavevorteil zu verlieren.',
'Vorbereitete Fury und E-Rückweg prüfen. Eigenes W möglichst nach empowered W: dessen Schildbruch verschwendet sonst deinen Schutz. Nach E2 langen Trade suchen.',
'Olaf-R verhindert Stun, aber weder empowered-W-Schaden noch Schildbruch. Renekton-R gibt HP und Schadensdruck; All-in mit eigener W-Verfügbarkeit planen.',
'Fury, empowered W/Schildbruch, E2-Rückzug, Q-Heilung, R-HP.',
'E2 verbraucht, wenig Fury und Q/W fehlen. Nach R-Ende erneuter Angriff besser als in seinen vollen Spike.',
'W-Schild in empowered W legen; mit wenig HP Burst abwarten; nach E1 losrennen, obwohl E2 noch offen ist.',
'Wave auf eigener Seite, aber nicht unter großem Stack tanken. Nach verbrauchter Kombo Slowpush; Crash nur, wenn sein E/W dich nicht im Weg stoppen.',
'Q beim Rückzug treffen, seine W-Kombo abfangen, danach eigenes W–Auto–E. Nach E2 mit kurzen Äxten dranbleiben; R nur im echten Commit.',
'Ravenous Hydra für Reset-Sustain, dann Death’s Dance. Stridebreaker, wenn der E2-Rückzug das zentrale Problem ist.',
'Sterak’s erst mit Bewusstsein für Schildbruch; Armor kann verlässlicher sein. Executioner’s bei heillastigem Build und engem All-in.',
'1 Item: Fury und E2 entscheiden. 2 Items: Olaf profitiert von längeren Duellen mit Armor. 3 Items: häufig gute Side bei sauberem W-Timing, Renektons Team-Burst bleibt relevant.',
'Respektiere volle Fury und spare deinen Schild für nach empowered W. Wenn E2 weg ist, verlängere den Trade. Gewonnen wird die zweite Hälfte des Kampfes, nicht das Tankieren seiner ersten Kombo.',
'PTA bei kurzen Team-Catches nach verbrauchtem gegnerischen Disengage; Conqueror für wiederholte Renekton-Duelle.');
}
