export default function(add){
add('tryndamere','Tryndamere','F','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh; Armor hilft gegen seine Auto-Kette.',
'Tryndameres R verweigert den Kill, während Olaf für Heilung und R-Verlängerung weiter angreifen möchte. Crit und E-Mobilität machen Low-HP-Rennen extrem riskant.',
'Das Duell umfasst seine Unsterblichkeitsphase und einen möglichen Re-engage. PTA-Burst kann R erzwingen, löst aber die folgende Überlebensphase nicht.',
'Olaf bei geringer gegnerischer Fury und Q-Abstand. Gegen volle Fury keinen zufallsabhängigen Crit-Statcheck eingehen.',
'Fury-Aufbau an Minions bedrohen, nach Q-Heilung ohne Fury handeln. E-Verbrauch erleichtert Q-Kiting. W-Slow beim Wegdrehen beachten.',
'Seine R ziehen, dann mit Q/Abstand überleben. Eigene R allein gewinnt diese Phase nicht; falls Kontakt abreißt, endet auch deine Verlängerung.',
'Fury/Crit, Q-Heilung, W-AD-Reduktion/Slow, E-Reset-Mobilität, R-Unsterblichkeit.',
'R fehlt, E verbraucht und wenig Fury. Nach Q-Heilung gutes kurzes Tradefenster, aber HP-Unterschied weiterhin prüfen.',
'Bis zum Tod in seine aktive R autoattacken; ohne Rückweg all-in; frühe Crit-Zufälle als garantierten Level-1-Sieg planen.',
'Wave auf eigener Seite ausdünnen. Mit Rückstand keinen großen Dive-Stack zulassen. Nach gezogenem R crashen/resetten, statt ohne Ressourcen weiterzustehen.',
'Q–Auto–E, W für seine erste echte Schadensphase. R erzwingen, Q zum Kiten und Flash/Ghost für Abstand bewahren; nach R-Ende nur bei sicherem Zugriff töten.',
'Stridebreaker für Abstand und Wiedereinstieg, danach Death’s Dance. Ravenous Hydra, wenn Wave-Sustain und Halten statt Solokill dein Auftrag ist.',
'Randuin’s gegen Crit-Druck; frühe Armor ist oft wertvoller als mehr DPS. Executioner’s gegen relevante Lifesteal-Itemisierung, nicht als Antwort auf seine R.',
'1 Item: R-Management zwingend. 2 Items: Armor/Kiting verbessert Überleben. 3 Items: Tryndamere bleibt eine große Side-Gefahr; sichere Waves und Teamantworten vorbereiten.',
'Bekämpfe zuerst seine Fury und ziehe dann R. Plane vor dem Einstieg, wie du seine Unsterblichkeit überlebst. Ein erzwungenes R mit anschließendem Reset ist bereits ein brauchbarer Gewinn.',
'PTA nur bei Team-Pick-Plan und abgesicherter Side; Conqueror ist die Lane-Voreinstellung, keine Garantie für den Statcheck.');
add('urgot','Urgot','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh gegen W/Autos und physischen Druck.',
'Olaf kann E-Kontrolle und den R-Suppress mit richtigem R-Timing verhindern. Urgots Shotguns verursachen trotzdem hohen Burst, besonders wenn Olaf um ihn herumläuft.',
'W-DPS, Schild und HP führen zu langen Melee-Fights. Conqueror unterstützt mehrere E-Zyklen gegen einen Gegner, den drei Autos selten töten.',
'Urgots E plus geladene Beine ist gefährlich. Olaf erst nach verfehltem E/langem Q-Kontakt; keinen garantierten Level-1-Sieg annehmen.',
'E seitlich ausweichen und auf bereits abgefeuerter Beinseite bleiben. Nicht durch Umkreisen alle Shotguns freischalten.',
'R rechtzeitig gegen E/R-Suppress einsetzen und durch Autos/E aktiv halten, solange die Execute-Drohung besteht. Nicht voraussetzen, dass ein früher kurzer R-Druck jeden späteren R-Recast löscht.',
'E-Dash/Schild, Shotgun-Beine, W-Fokus, R-Markierung/Execute.',
'E verfehlt, nahe Beine abgefeuert. R fehlt; vor W-Max sind dessen Off-Phasen zusätzliche Fenster.',
'Alle Beine ablaufen; mit auslaufender R unter Execute-Schwelle stehen; E-Dash frontal tanken, nur um eine Axt aufzuheben.',
'Eigene Seite mit seitlichem Platz. Nach E-Verfehlung Slowpush; unter seinem Turm keinen Flip-Winkel anbieten.',
'Q treffen, E seitlich dodgen, auf verbrauchter Beinseite Auto–W–Auto–E. R beim drohenden Kontroll-/Execute-Zugriff und mit Kontakt verlängern.',
'Ravenous Hydra für Side-Sustain, danach Death’s Dance. Black Cleaver gegen frühes Armor als Alternative für längere Duelle.',
'Sterak’s für Burstpuffer; BotRK gegen hohen HP-Anteil bei sicherem Überleben. Zusätzliche Armor bei gegnerischem AD-Team.',
'1 Item: E-Dodge entscheidet. 2 Items: Urgots W-/Bein-Spikes respektieren; R bleibt dein Werkzeug. 3 Items: Olaf kann Side spielen, aber ein abgelaufenes R kann das Duell sofort drehen.',
'Bleib auf einer bereits abgefeuerten Beinseite und weiche E aus. Spare R für die Kontrolle beziehungsweise Execute-Drohung. Halte es dann durch echten Kontakt aktiv.',
'PTA für kurze Carry-Catches möglich; Conqueror besser, wenn Urgot dein permanenter Side-Gegner bleibt.',
'R-Execute-Interaktion verlangt präzises Timing. Keine Behauptung eines dauerhaft gelöschten R-Markers; empfohlener Plan ist aktive CC-Immunität während der Gefahr.');
add('vayne','Vayne','F','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Plated Steelcaps früh, zusätzliche Bewegung zum Zugang.',
'Q-Mobilität, R-Unsichtbarkeit und prozentualer True Damage greifen Olafs Kernplan an. R verhindert Condemn-Kontrolle, garantiert aber keine Autos auf ein sichtbares Ziel.',
'Trotz fragiler Vayne ist PTA wegen R/Q-Unterbrechungen nicht zuverlässig. Conqueror kann über Q/E und erneuten Kontakt arbeiten, ist ohne Zugriff ebenfalls kein Rettungsanker.',
'Vayne hat Reichweitenkontrolle; Olaf nur bei Q-Treffer und langem Rückweg. Ohne günstige Lage HP bewahren, nicht drei Autos erzwingen.',
'Nach offensivem Q und verbrauchtem E anlaufen. Silver-Bolts-Procs nicht gratis durch CS-Gier erlauben. Gank mit langer Lane vorbereiten.',
'R/Q macht Auto-Uptime noch schlechter. Olaf-R vor Condemn hilft gegen Knockback, Unsichtbarkeit bleibt. Nicht R allein in einen frischen Stealth-Zyklus investieren.',
'Q-Tumble, E-Condemn, W-True-Damage, R/Q-Stealth.',
'E fehlt, Q offensiv benutzt und R nicht verfügbar; abgeschnittener Fluchtweg oder verlässliche Teamhilfe.',
'Sweeper als True Sight behandeln; Armor als Lösung gegen W ansehen; R ohne Kontaktplan zünden; Wandstun vor 6 anbieten.',
'Wave auf eigener Seite und möglichst dünn. Gegen großen Stack Hilfe/Reset priorisieren. Nach einem Kill vollständig crashen, bevor sie zurückkitet.',
'Q aus Winkel treffen, nach Q/E-Verbrauch anlaufen. R gegen Condemn, Auto–E und W für sichtbares Auto-Fenster; Stealth-Endpunkt vorausplanen statt blind weiterzuklicken.',
'Stridebreaker für Anschluss, danach Death’s Dance gegen physischen Anteil/AD-Comp oder Sterak’s gegen gemischten Burst. Beides löst W-True-Damage nicht.',
'Randuin’s gegen tatsächlichen Crit-Build/weitere Crit-Ziele, nicht blind gegen On-hit-Vayne. Kein gläserner Kritlaf aus Rückstand; Team-CC und Flanken haben höheren Wert.',
'1 Item: Stride schafft begrenzte Catches. 2 Items: Vayne wird mit On-hit gefährlicher. 3 Items: offene Side meist vermeiden, wenn kein deutlicher Vorsprung oder Hilfe vorhanden ist.',
'Bewahre HP und halte den Rückweg lang. Greife bevorzugt nach E und ohne ihre R an. Später sind Flanken und Hilfe verlässlicher als der Versuch, sie im offenen Feld zu statchecken.',
'PTA, wenn Vayne in der Praxis kaum dein Ziel ist und drei sichere Autos auf die übrigen Carries regelmäßig möglich sind.');
add('vladimir','Vladimir','B','PTA','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Boots; Mercury’s bei AP-lastigem Gegnerteam.',
'Olaf kann Vlad vor seinen großen Spikes bedrohen. Pool und Bewegung entscheiden jedoch, ob der erste Kontakt in tatsächlichen Schaden übergeht.',
'Nach Pool-Ende ist das Killfenster kompakt und drei Autos plausibel. PTA vor frischem Pool zu erzwingen ist dagegen unzuverlässig.',
'Olaf bei Q-Chase, Vlad im sicheren Q-Poke. Empowered Q anzeigen lassen und kurz aus dessen Reichweite gehen.',
'Pool herauslocken, dann mit langer Lane erneut angreifen. Nicht in empowered Q traden; E-Ladung und Minionblockierung beachten.',
'Olaf-R verhindert Pool nicht und entfernt Vlad-R-Schaden nicht. Pool kann deine R auslaufen lassen; R möglichst erst für den zweiten Kontakt investieren.',
'Empowered Q, W-Pool, aufgeladenes E, R-Verzögerung/Burst.',
'W verbraucht und empowered Q vorbei. R fehlt nach einem abgebrochenen All-in.',
'Frische R in Pool laufen lassen; Vlad-R-Nachschaden auf wenig HP vergessen; jeden roten Q mit eigenem Gesicht beantworten.',
'Eigene Seite für langen Chase; nach Pool-Verbrauch Slowpush/Crash. Freeze nur, solange du ihn tatsächlich von CS wegdrängen kannst.',
'Q treffen, kurze Autos/E zum Pool-Zwang. Pool-Ende abwarten, dann Ghost und Auto–W–Auto–Auto; W vor dem erwarteten Burst, nicht erst nach dem letzten Treffer.',
'Stridebreaker für Kontakt, danach Maw. Ravenous Hydra statt Stride, wenn du gegen Poke nicht gesund ins Fenster kommst.',
'Executioner’s bei knappem All-in mit mehreren Heilzyklen. Fiendhunter Bolts nur bei Vorsprung und verlässlich verbrauchtem Pool; Spirit Visage bei AP/Teamheilung.',
'1 Item: gute Jagdfenster nach Pool. 2 Items: Vlad-Burst steigt, Maw hilft. 3 Items: Vlad wird im Teamfight sehr gefährlich; früh Druck in Türme/Objekte umsetzen.',
'Spiele um Pool und den roten Q. Erzwinge erst Pool, dann nutze das zweite Fenster mit vollem Auto-Kontakt. Plane seinen verzögerten R-Schaden in deine verbleibenden HP ein.',
'Conqueror bei defensivem Vlad-Build oder mehreren langlebigen Melees; Pool-Unterbrechung kann auch in der Lane Conqueror rechtfertigen.');
add('volibear','Volibear','C','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps gegen Auto-lastige Variante; Mercury’s bei AP-lastiger Gesamtcomp.',
'Olaf kann Q-Stun übergehen, Volis zweites W und E-Schild gewinnen aber lange unvorbereitete Trades. Das Duell hängt stark von Markierung und E-Treffer ab.',
'Schild, Heilung und wiederholte Nahkampfzyklen verlangen langen Schaden. Conqueror passt, sobald du ein günstiges W/E-Fenster geschaffen hast.',
'Olaf mit Q-Abstand stark. Volis passive Stacks und E-Landung können den Nahkampf drehen; gelernten Spell beobachten.',
'E-Kreis verlassen. Nach erstem W den markierten Recast nicht gratis erlauben; kurz lösen und nach Markierungsende neu angreifen, sofern Wavezustand es erlaubt.',
'R stoppt Q-Stun, nicht E-/W-Heilung oder Voli-R-HP/Burst. Unter eigenem Turm mit niedrigen HP kann seine R den vermeintlich sicheren Rückzug aufheben.',
'W-Markierung/Recast-Heal, E-Kreis/Schild, passive Stacks, Q, R-Turmdisabling.',
'E verfehlt und Schild weg; W-Markierung abgelaufen. R fehlt für Dive/HP-Flip.',
'Stationär im E bleiben; zweiten W auf angeschlagenem Olaf akzeptieren; eigenen Turm gegen seine R als sicheren Schutz ansehen.',
'Eigene Seite, aber großen Dive-Stack vermeiden. Nach verfehltem E Wave ausdünnen/crashen; HP-Reset vor drohendem R-Dive.',
'Q–Auto–E außerhalb seines E. Nach erster W-Markierung Abstand, dann erneut Q–Auto–W–Auto, wenn Markierung und Schild weg sind.',
'Ravenous Hydra für wiederholte Trades, zweites Death’s Dance gegen AD oder Maw gegen AP-Variante. Stridebreaker erleichtert Lösen und Re-engage.',
'Executioner’s, wenn W-/Itemheilung das Duell entscheidet. Armor/MR nach tatsächlichem Build; gegen AP-On-hit nicht nur Armor stapeln.',
'1 Item: sein Build und E/W-Timing zentral. 2 Items: passende Resistenz stabilisiert. 3 Items: kein pauschales Scaling-Ergebnis; AP/On-hit und Bruiser erfordern verschiedene Antworten.',
'Laufe aus E und verweigere den zweiten W. Spiele zwei Trades statt eines schlechten Dauer-All-ins. Resette rechtzeitig, bevor Voli mit R den Turm als Schutz ausschaltet.',
'PTA bei kurzen Team-Catches und wenn Voli nicht durch mehrere Heilzyklen besiegt werden muss.');
add('warwick','Warwick','E','Conqueror','Doran’s Blade + Health Potion','Ghost + Ignite','Plated Steelcaps gegen Autos; Magieschaden seiner Heilautos/Q bleibt.',
'Warwicks Low-HP-Heilung und E-Schadensreduktion bestrafen Olafs eigenes Low-HP-Rennen. R-Immunität entfernt nur einen Teil seiner Kontrolle.',
'Mehrere Heilzyklen und E-Defensive machen das Duell lang. PTA-Burst in aktive E ist selten ein sauberer Killplan.',
'Keinen blinden Statcheck: Warwick wird bei niedrigen HP gefährlicher. Q-Poke und Waveposition statt All-in bei voller beidseitiger HP.',
'E herauslocken und Schadensreduktion auslaufen lassen. Gehaltenes Q kann Bewegungen folgen. Nicht seinen Low-HP-Zustand mit sicherem Kill verwechseln.',
'R kann Fear und Suppress verhindern/befreien, wenn passend eingesetzt. Warwick-Q/Passive heilt weiterhin; R-Timing allein ersetzt Antiheal und HP-Vorteil nicht.',
'Passive Low-HP-Heilung, Q-Heal/Folgebewegung, E-Schadensreduktion/Fear, R.',
'E beendet, Q verbraucht, Ignite bereit und genug HP für seine Heilphase. Fehlende R senkt Burst/Fluchtoptionen.',
'In E hineinbursten; auf minimalen HP ohne Antiheal statchecken; Ghost+Ignite ohne Flash wie einen sicheren Escape-Build spielen.',
'Eigene Seite mit sicherem Rückweg. Ohne TP vor Questabschluss Resets früh planen. Nach gezogenem E kurzer Druck, keinen großen gegnerischen Stack tanken.',
'Q-Poke, E ziehen und Abstand. Danach Q–Auto–W–Auto–E; Ignite vor der entscheidenden Low-HP-Heilphase, R für Fear/Suppress im Commit.',
'Ravenous Hydra für Sustain ohne erzwungenes All-in, danach Death’s Dance bei AD-Comp; Maw bei zusätzlichem AP-Druck. Stridebreaker bei Bedarf zu lösen.',
'Executioner’s, wenn Ignite nicht oft genug verfügbar ist; kein doppelter Grievous-Wounds-Kauf ohne Mehrwert. Defensive vor Kritlaf.',
'1 Item: Warwick bleibt im Low-HP-Fight gefährlich. 2 Items: Antiheal und Resistenz helfen. 3 Items: Side nur mit E-/Heal-Plan; Gruppenwert kann besser sein als permanentes Duell.',
'Ziehe E und kämpfe erst nach der Schadensreduktion. Setze Antiheal vor seiner großen Heilphase. Ein Warwick auf wenig HP ist noch kein gewonnener Kill.',
'Flash + Ghost statt Ghost + Ignite bei Terrain-/Gank-Gefahr der Gesamtcomp; dann Antiheal über Item/Team absichern. PTA nur für klaren Team-Pick-Plan.');
add('wukong','Wukong','B','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps gegen Auto-/Q-Druck.',
'Olaf übergeht die Knock-ups, Wukongs Clone/Stealth nimmt ihm aber Uptime. Passive Armor und Q-Shred verhindern einen einfachen Auto-Statcheck.',
'Clone und mehrere R-Kontakte verlängern oder unterbrechen den Fight. Conqueror über echte Q/E-Treffer nutzen, nicht PTA auf dem falschen Ziel erzwingen.',
'Olaf mit Q-Resets gut; Wukong-E plus Passive kann den Nahkampf drehen. Nicht ohne Rückweg durch volle Wave kämpfen.',
'W herauslocken und echten Gegner über Bewegung/Spellgebrauch identifizieren. Nach Clone-Ende bei verbrauchtem E verfolgen.',
'R verhindert Knock-up, nicht R-Schaden oder Clone-Ablenkung. Vorzeitig gestartetes Olaf-R kann während Stealth auslaufen.',
'W-Clone/Stealth, passive Armor, Q-Armor-Shred, E-Zugang, R-Zyklen.',
'W weg und E verbraucht. Beide R-Aktivierungen beendet erleichtern den zweiten Fight.',
'W/Autos in Clone verschwenden; Sweeper als volle Zielbarkeit behandeln; seine zweite R-Aktivierung vergessen.',
'Eigene Seite mit langer Lane. Nach W-Verbrauch Slowpush; vor Freeze große gegnerische Wave ausdünnen.',
'Q–Auto–E zum W-Zwang. Clone nicht tunneln; echten Wukong nach W wieder Q treffen, Auto–W–Auto, R gegen Knock-up bei realem Kontakt.',
'Ravenous Hydra für Sustain, danach Death’s Dance. Black Cleaver, wenn Armor-Stapelung tatsächlich bremst.',
'Sterak’s gegen Burst; Stridebreaker statt Hydra bei Kontaktproblem. Crit erst nach Clone-Verbrauch zuverlässig, kein Lane-Default.',
'1 Item: Clone-Timing zentral. 2 Items: Armor/Shred bestimmen Duell. 3 Items: Side spielbar, Wukongs Teamfight kann trotz Lane-Nachteil stark bleiben.',
'Ziehe Clone, bevor du deinen ganzen Fight investierst. Halte R für echten Kontakt mit Wukong. Seine zweite R und die passive Armor bleiben auch ohne Knock-ups relevant.',
'PTA bei verlässlich kurzen Catches der restlichen Comp; gegen wiederholte Wukong-Duelle Conqueror.');
add('yasuo','Yasuo','B','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh gegen Auto-/Q-Druck.',
'Olaf kann Yasuo im langen Fight bedrohen, aber Minion-Dashes und Windwall nehmen Q-Kontakt. R verhindert Knock-up-Setup bei rechtzeitigem Einsatz.',
'Schild, Dashes und Windwall verursachen mehrere Kontaktphasen. Q/E können Conqueror aufbauen; drei frühe Autos sind in voller Wave nicht garantiert.',
'Olaf bei treffenden Qs/anhaltendem Kontakt. Yasuo kann mit Q-Abstand gewinnen; passive Schild vorher günstig brechen.',
'Nicht in einer dichten eigenen Wave verfolgen, die viele E-Wege bietet. Nach Windwall-Verbrauch erneut Q nutzen; Tornado und E-Markierungen beachten.',
'R verhindert Knock-up und damit sein eigenes R-Setup auf Olaf, solange aktiv. Nach R-Ende oder durch verbündeten Knock-up bleibt Yasuo gefährlich.',
'E-Dashpfade, W-Windwall, Q3, passive Schild/Crit, R.',
'Windwall fehlt und keine sicheren E-Ziele. Q3 verbraucht. R-CD hilft, aber kein Ersatz für gute Waveposition.',
'Q in Windwall werfen; in eigener voller Wave im Kreis jagen; nach Olaf-R-Ende Tornado unterschätzen.',
'Eigene Seite, Wave eher dünn halten. Nach Windwall-Verbrauch Crash vorbereiten. Keine Verfolgung durch viele frische Dash-Ziele.',
'Schild mit Q brechen, Windwall abwarten/umlaufen. Bei wenig E-Zielen Auto–E–W–Auto; R für Knock-up im Commit und kurze Qs für Kontakt.',
'Stridebreaker gegen Dash-Spacer oder Ravenous Hydra für Sustain; danach Death’s Dance. Wahl davon abhängig, ob Kontakt oder HP fehlen.',
'Randuin’s gegen mehrere Crit-Ziele; Executioner’s gegen viel Lifesteal. Fiendhunter Bolts nur bei Vorsprung und sicherem Kontakt.',
'1 Item: Wave und Windwall entscheiden. 2 Items: sein Crit-Spike ist ernst, Armor hilft. 3 Items: kein freier Statcheck; E-Wege und Team-Knock-ups können die Lage drehen.',
'Kämpfe bei dünner Wave und fehlender Windwall. Neutralisiere das Knock-up mit R, sobald du wirklich dran bist. Verschenke deine Äxte nicht in seine Wand.',
'PTA, wenn die Comp kurze Catches ohne viele Dash-Ziele bietet; Lane-Conqueror für mehrere Kontaktphasen.');
add('yone','Yone','B','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps gegen Auto-/Q-Anteil; gemischten Schaden mitdenken.',
'Olaf übergeht Yones CC und gewinnt viele längere Kontakte. E-Rückkehr und W-Schild erlauben Yone jedoch risikoreduzierte kurze Trades.',
'W-Schild und E-Re-engages verlängern das Muster. Conqueror über Q/E aufbauen, aber kein sinnloser Chase nur zum Erhalten der Stacks.',
'Olaf bei Q-Resets stark. Yone-Q-Abstand respektieren und vor geladenem Q3 nicht geradlinig anlaufen.',
'Nach E-Rückkehr Druck auf den Körperstandort. W-Verbrauch nutzen; seine E-Form nicht bis unter gegnerischen Turm verfolgen.',
'R verhindert Knock-ups, nicht den Schaden von Yone-R oder E-Wiederholung. Seine R kann auch Fluchtweg sein; eigene R erst bei erreichbarem Anschluss.',
'E-Rückkehr/Schadenswiederholung, W-Schild, Q3, R-Bewegung.',
'E beendet, W verbraucht, Q3 fehlt. R verfehlt/als Flucht genutzt öffnet Folgefenster.',
'E-Geist blind verfolgen; verzögerten E-Schaden auf wenig HP vergessen; R zünden, bevor er mit R weit weg ist.',
'Eigene Seite mit dünner Wave. Nach E-Ende Slowpush oder Freeze-Druck; vor seinem Q3/R-Dive HP rechtzeitig resetten.',
'Q–Auto–E zum W-Zwang; E-Rückkehr abwarten, dann Auto–W–Auto am realen Körper. R gegen CC im Commit, Q auf verbleibenden Fluchtweg.',
'Ravenous Hydra für wiederholte Trades oder Stridebreaker für Anschluss; danach Death’s Dance gegen AD-lastige Comp.',
'Randuin’s gegen Crit-Druck; Sterak’s bei gemischtem Burst. Armor reduziert nicht alle Schadensanteile, daher keine reine Armor-Lösung behaupten.',
'1 Item: gute lange Fights nach E. 2 Items: Crit-/Lifesteal-Spike respektieren. 3 Items: Side weiter skillabhängig; sein Zugang zur Backline kann im Teamspiel höher sein.',
'Warte auf E-Rückkehr und kämpfe dann am echten Körper. Nutze R gegen die Kontrolle, nicht als Antwort auf allen Schaden. Plane die E-Schadenswiederholung in deine HP ein.',
'PTA bei kurzen, sicheren Carry-Kontakten im Gesamtspiel; Conqueror bei mehreren Frontline-Fights.');
add('yorick','Yorick','E','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps gegen physischen Druck; Basisbewegung für E-Dodge.',
'Yoricks Käfig bleibt unter Ragnarok stehen. Ghouls und Maiden liefern Schaden, während Olaf erst Terrain und zusätzliche Ziele bearbeiten muss.',
'Mehrere Ziele und lange HP-Phasen machen PTA auf Yorick allein unzuverlässig. Conqueror hilft im anschließenden Champion-Fight, ersetzt aber kein Pet-Management.',
'Olaf stärker, solange noch keine vorbereiteten Gräber/Ghouls vorhanden sind. Q-Poke und Platz nehmen, ohne späteren Ghoul-Stack zu ignorieren.',
'E unbedingt seitlich ausweichen. Ghouls mit Autos gezielt beseitigen; Q-AoE ist dafür nicht automatisch effizient. Käfig per Autos/Auto–W-Reset öffnen oder Flash für kritischen Ausgang.',
'Maiden verändert das Duell stark. Erst Pets beziehungsweise sicher exponierte Maiden bearbeiten; R zerstört W-Terrain nicht. Kein blindes All-in in volle Beschwörungen.',
'W-Käfig, E-Markierung/Ghoul-Sprung, Gräber/Ghouls, R-Maiden, Q-Heilung.',
'E verfehlt, W fehlt und wenige Ghouls; Maiden tot/zu weit weg. Mehrere Voraussetzungen zusammen erzeugen das echte Killfenster.',
'R als Käfig-Escape ansehen; Maiden ignorieren; alle Autos auf Yorick richten, während Ghouls dich herunterarbeiten.',
'Früh kontrollierter Slowpush möglich. Später Wave/Pets ausdünnen und nicht unter großem Stack einschließen lassen. Crash vor Roam, sonst verliert die Side schnell Türme.',
'E dodgen, Ghouls mit Autos abräumen, exponierte Maiden sicher bestrafen. Erst danach Q–Auto–W–Auto–E auf Yorick; Flash nicht für geringen Zusatzschaden verschwenden.',
'Ravenous Hydra für Wave-Sustain/Clear, danach Death’s Dance gegen AD-Druck. Hydra ersetzt die gezielten Autos auf Ghouls nicht.',
'Black Cleaver gegen Armor; Sterak’s gegen gemischten Burst. Hullbreaker nur, wenn du tatsächlich Turmzeit erhältst, nicht während du dauerhaft Maiden abwehrst.',
'1 Item: ohne Maiden gute Fenster. 2 Items: Pet- und Wavekontrolle wichtiger als reiner Buildwert. 3 Items: offene Side mit voller Maiden gefährlich; Hilfe zum Pet-Reset schafft Druck.',
'Weiche E aus und entferne Ghouls, bevor du Yorick selbst bekämpfst. Halte Flash für einen kritischen Käfig. Ohne Maiden und W ist das Matchup deutlich besser spielbar.',
'PTA, wenn Yorick nur gecleart wird und die restliche Comp kurze Catches erlaubt; in vollen Pet-Fights Conqueror.');
add('zaahen','Zaahen','D','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps gegen Auto-/Q-Druck.',
'Aufgebaute Passive, Heilung und mögliche Wiederbelebung bestrafen einen unvorbereiteten Olaf-Statcheck. Ohne Stacks und verbrauchte Mobilität ist Zaahen angreifbar.',
'Heilung, defensive R-Phase und gegebenenfalls zweite Lebensphase machen den Fight lang. PTA-Frontload allein deckt diese Phasen nicht ab.',
'Keinen pauschalen Sieger behaupten: Zaahens Q-Heilung und beginnender Stackaufbau gegen Olafs Q-Resets. Kurz handeln und volle Passive nicht gratis aufbauen lassen.',
'Q-Recast und E-Dash beobachten. Außenkante von E vermeiden; nach W-Verfehlung und verbrauchtem E anlaufen, solange Passive nicht voll vorbereitet ist.',
'Seine R hat eine defensive Castphase und heilt über den folgenden Treffer. Olaf-R nimmt Kontrolle, nicht Schadensreduktion, Heilung oder passive Wiederbelebung.',
'Passive Stacks/Revive-Bereitschaft, Q-Heilung/Recast, W-Zug, E-Außenkante, R-Defensivphase.',
'E und Q-Recast verbraucht, R fehlt und Passive nicht voll beziehungsweise Revive nicht bereit. Nicht allein auf niedrige sichtbare HP reagieren.',
'In R-Defensivphase den ganzen Burst investieren; Revive vergessen; voll gestackte Passive auf niedrigen eigenen HP statchecken.',
'Wave auf eigener Seite mit seitlichem Raum. Nach verbrauchten Spells kurzer Druck/Slowpush; keinen langen Kampf in gegnerischem Minionstack.',
'Q-Poke, W seitlich umgehen, nach E Auto–E. R-Castphase nicht statisch tanken; danach Auto–W–Auto, falls HP und passive zweite Phase kalkulierbar bleiben.',
'Ravenous Hydra für kurze Trades und Reset, danach Death’s Dance. Stridebreaker bei Kontaktproblemen als Alternative, nicht als Heilungsersatz.',
'Executioner’s vor entscheidenden langen Heilkämpfen; Sterak’s als Burstpuffer. Crit-Linie hier kein Default, solange passive/defensive Phasen nicht zuverlässig überspielt werden.',
'1 Item: Stackzustand wichtiger als bloße Itemzahl. 2 Items: Heilung/Defensive verlängert das Duell. 3 Items: Side ohne klare Passive-/R-Information meiden; qualitative Unsicherheit höher.',
'Greife bei niedrigen Stacks und verbrauchtem E an. Rechne R-Heilung und mögliche Wiederbelebung als eigene Phasen. Niedrige sichtbare HP allein sind kein Killfenster.',
'PTA nur bei klar kurzen Team-Catches; für Zaahens mehrphasige Duelle Conqueror.',
'Höhere Unsicherheit: jüngerer Champion und wenig belastbare spezifische Olaf-Daten. Keine exakten Stack-, Heil- oder CD-Werte aus älteren Release-Guides übernommen; D ist vorläufige Kit-Einschätzung.');
}
