export const matchups=[];
import part2 from './matchups2.mjs';
import part3 from './matchups3.mjs';
import part4 from './matchups4.mjs';
import part5 from './matchups5.mjs';
const add=(slug,name,tier,rune,start,sums,boots,reason,runeReason,l1,l25,l6,threats,window,errors,wave,trade,items,situ,side,plan,override,uncertainty='Tier und Build sind qualitative Analyse, keine gemessene Gewinnwahrscheinlichkeit. Ein Rang Abweichung bei anderer Ausführung oder Comp ist plausibel.')=>matchups.push({slug,name,tier,rune,start,sums,boots,reason,runeReason,l1,l25,l6,threats,window,errors,wave,trade,items,situ,side,plan,override,uncertainty});
add('aatrox','Aatrox','B','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps bei ausgeglichener Lane.',
'Olaf kann nach verfehlten Qs dauerhaft Kontakt halten und ab 6 den CC übergehen. Aatrox gewinnt mit Abstand, Sweetspots und Heilung, wenn Olaf bereits angeschlagen ankommt.',
'Mehrere Q-Rotationen und Aatrox-R-Heilung verlängern den Kampf. Conqueror belohnt Olafs fortgesetzte Autos und E-Zyklen stärker als einen erzwungenen Dreiertrade.',
'Olaf bei treffenden, aufhebbaren Äxten. Q1 ausweichen und danach Platz beanspruchen. Nicht alle drei Sweetspots tanken, um einen Axe-Reset zu erzwingen.',
'Nach Q3 oder offensiv verbrauchtem E anlaufen. Bis dahin Q-Poke seitlich zur Wave. W nach eingehendem Schaden benutzen, ohne in Q3-Burst zu fallen.',
'R nimmt Knock-ups und W-Rückzug als zuverlässige Unterbrechung. Aatrox-R erhöht trotzdem Sustain und Fluchttempo. Nur bei erreichbarem Kontakt committen.',
'Q-Sweetspots, E-Repositionierung, W-Zone, R-Heilung.',
'Q-Kette beendet und E verbraucht. Nach seinem R-Ende erneut Druck. W verfehlt erleichtert den langen Chase vor 6.',
'Geradlinig durch Q1–Q3 laufen. R aus zu großer Entfernung starten. Einen Aatrox mit laufender R in unbekannten Jungle verfolgen.',
'Früh kontrollierter Slowpush, Crash nur vollständig. Cheater-Recall bei freiem Crash möglich. Danach Bounce auf eigener Seite halten, damit seine E nicht bis zum Turm reicht.',
'Q treffen, Q-Sweetspot seitlich umgehen, nach E an seine Nahseite laufen. Auto–W–Auto, E zwischen Autos, kurze Äxte auf den Fluchtweg. Bei Aatrox-R nur fortsetzen, wenn W und HP reichen.',
'Ravenous Hydra für Sustain zwischen Q-Trades, danach Death’s Dance gegen AD. Stridebreaker statt Hydra, wenn sein Spacing und die Comp den Kontakt zum Hauptproblem machen.',
'Executioner’s Calling vor einem entscheidenden All-in, wenn Heilung den Kill verhindert. Sterak’s gegen Burst. Maw bei zusätzlicher AP-Gefahr statt Sterak’s.',
'1 Item: Hydra ermöglicht wiederholte Versuche, kein Freipass gegen seine R. 2 Items: mit R und Death’s Dance oft gute Duelle. 3 Items: stark von Antiheal und Aatrox-Build abhängig. Sein Teamfight kann trotz verlorener Side relevant bleiben.',
'Spiele um Q3 und E, statt den ersten Treffer erzwingen zu wollen. Halte den Rückweg lang und starte R erst mit realistischem Auto-Kontakt. Ein sauberer Reset ist besser als ein Chase durch seine komplette R.',
'PTA, wenn Aatrox nur gehalten werden muss und vier fragile Gegner kurze Picks begünstigen. Conqueror behalten, wenn du seine Heilung auf der Side überwinden musst.');
add('akali','Akali','E','Conqueror',"Doran’s Shield + Health Potion",'Flash + Teleport','Frühe Boots zum Q-Dodgen. Mercury’s Treads nur bei zusätzlichem Wert gegen AP/CC.',
'Shroud und mehrere Dashes entziehen Olaf Autos, Lifesteal und R-Verlängerung. Ohne W kann er Akali bedrohen, aber sie kontrolliert häufig, ob der Kampf überhaupt weitergeht.',
'Q und E können Conqueror vorbereiten, während PTA vor drei Autos durch Shroud unterbrochen wird. Auch Conqueror ist während vollständigem Disengage wertlos. Kein Zwangs-All-in für die Rune.',
'Olaf im durchgehenden Kontakt. Akali gewinnt einzelne Q–Passive-Trades. Nach ihrem Q seitlich vorrücken, nicht für eine Axt in den nächsten verstärkten Auto laufen.',
'W herauslocken und verlassen. Nach Shroud-Ende bei fehlendem E oder wenig Energie Druck. E1 durch Minions erschweren. Lange Trades nur, wenn sie keinen sicheren Rückzug hat.',
'Ihre R liefert zwei zusätzliche Bewegungen und Execute-Druck. Olaf-R deckt Unsichtbarkeit nicht auf. R erst nach W oder wenn ein sicherer Kill vor dem Verschwinden besteht.',
'W-Shroud, E1-Markierung/E2, R2-Execute, Q–Passive-Reichweite.',
'W beendet plus E verbraucht/verfehlt. R auf Cooldown senkt Flucht- und Burstpotenzial. Ein einzelnes verfehltes Q reicht meist nicht.',
'R in frischen Shroud starten. Sweeper als True Sight behandeln. Auf sehr wenig HP gegen verfügbares R2 mit späterem W spekulieren.',
'Wave auf eigener Seite, aber vor dem Turm ausdünnen. TP für schlechte Resets. Nach W-Verbrauch einen Crash vorbereiten. Tiamat nicht kaufen, wenn der Freeze deine einzige Druckquelle ist.',
'Q aus sicherem Winkel, kurzen Auto–E-Trade nehmen, wenn sichtbar. W provozieren, aus Shroud-Reichweite zurück. Zweiter Anlauf nach W mit Q–Auto–W–Auto und R erst bei dauerhaftem Kontakt.',
'Ravenous Hydra für Waveclear und Rückheilung. Hexdrinker früh bei Killgefahr, danach Maw of Malmortius als zweites Item gegen AP-Burst.',
'Force of Nature bei mehreren dauerhaften AP-Quellen. Sterak’s nur ohne Maw. Kein früher Kritlaf: zusätzliche Crit-Chance löst fehlende Zielbarkeit nicht.',
'1 Item: Hydra stabilisiert die Lane, Gunblade/Burst respektieren. 2 Items: mit Maw schwerer zu töten, Akali aber weiter schwer festzuhalten. 3 Items: Side drücken und Antworten erzwingen, keine garantierten Solokills. Ihr Zugriff auf Carries bleibt stärker als ihr Turmschaden.',
'Behandle Shroud als Stoppsignal. Farm sicher, erzwinge ihren W-Cooldown und greife erst im zweiten Anlauf an. Bewahre ausreichend HP für R2 und nutze TP, damit ein schlechter Trade nicht zwei Waves kostet.',
'PTA nur bei klarer Rolle als Diver gegen andere Gegner mit zuverlässig drei Autos. Der Rune-Wechsel beseitigt Akalis Uptime-Problem nicht.');
add('ambessa','Ambessa','D','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps, falls ihre Auto-Weaves und AD-Trades dich drücken.',
'Ihre Dashes lassen sie Olafs R und Äxte ausspielen. Olaf gewinnt, wenn sie für Energie-Autos stehen bleiben muss und W bereits verbraucht ist. Später verbessern Penetration und Sustain ihre Duelle.',
'W-Schild und mehrere Re-engages verhindern ein verlässlich kurzes Killfenster. Conqueror passt zum Kampf über mehrere Energie- und Spell-Zyklen.',
'Olaf bei Kontakt nach verfehltem Q-Sweetspot. Abstand zum Q-Rand halten und nicht eine weit entfernte Axt durch ihre komplette Q-Sequenz verfolgen.',
'Nach W-Schildablauf oder verfehltem Q1 Druck. Sie braucht passive Autos für Energie. Diese Kontaktmomente bestrafen, statt jeden Dash zu verfolgen.',
'R verhindert ihren CC als Lockdown, nicht Schaden oder ihre Dashes. Ambessas R-Sustain/Penetration erhöht ihre Kampfstärke. R spät starten und Fluchtweg mit Ghost schließen.',
'Q-Rand und Folgeschlag, W-Schild, passive Dashes/Autos, R.',
'W verbraucht, niedrige Energie und kein guter Auto-Zugang. Nach verfehlter R kann sie keinen erneuten Fernengage erzwingen.',
'W-Schild mit vollem Burst beschießen. R im Anlauf verbrauchen. Dash-Distanz mit tatsächlichem Cooldown eines Spells verwechseln.',
'Bounce auf eigener Seite. Slowpush nur bei HP-Vorteil, damit sie beim Last-Hitten in Kontakt kommt. Kein halber Crash gegen ihre mobile All-in-Drohung.',
'Q treffen, Dash-Endpunkt anlaufen, Schild auslaufen lassen. Auto–W–Auto–E nach ihrem passiven Auto. Mit kurzen Qs nachsetzen, R bei nächstem sicheren Kontakt oder drohendem CC.',
'Ravenous Hydra gegen wiederholte kurze Trades, dann Death’s Dance. Stridebreaker als erste Alternative, wenn Kontakt längerfristig nicht gelingt.',
'Executioner’s bei relevanter Heilung. Sterak’s gegen gemischten Burst. Kein früher Crit-Ausbau ohne geklärte Auto-Uptime.',
'1 Item: Hydra hält HP stabil, ihr erster Bruiser-Spike bleibt gefährlich. 2 Items: ausgeführte Dashes/W-Timing entscheiden. 3 Items: eher Ambessa bei gleichen Ressourcen, wenn sie mehrfach disengagen kann. Gemeinsame Kämpfe über Flanken vorbereiten.',
'Warte auf W und bestrafe ihre Energie-Autos. Miss deine Chance an erreichbarem Kontakt, nicht an getroffenen Äxten allein. Bei gleich gutem Spiel musst du ihre Mobilität stärker respektieren als den CC.',
'PTA bei fragiler Backline und vorbereitetem Engage durch dein Team. Gegen Ambessa plus weitere Melees Conqueror halten.');
add('camille','Camille','E','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps für Autos und frühe Qs. Sie lösen späteren True Damage nicht.',
'Passive, Q2-Hit-and-run und Hookshot verhindern Olafs bevorzugten Dauerkontakt. R kann einen wichtigen Treffer ausweichen. Olaf hat frühe Fenster, Camille gewinnt später viele gleichwertige Side-Situationen.',
'Ihr Schild nimmt dem kurzen Auto-Fenster Wert. Conqueror passt zum nötigen zweiten Anlauf nach Schild/E. PTA nur bei tatsächlich festgehaltener Camille.',
'Olaf im langen Fight, Camille im Schildtrade. Passive zuerst auslösen, zurücktreten und nach Schildende mit Q erneut Druck. Nicht Q2 gratis nehmen.',
'E zum Trade verbraucht: hinterher, sobald Schild weg ist. Q2-Vorbereitung erkennen. W-Außenrand vermeiden oder innen stehen, wenn ein sicherer Kontakt möglich ist.',
'Olaf-R verhindert Hookshot-Stun, nicht die R-Arena. Camille kann mit R kurz untargetable werden und E/Q ausweichen. E nicht blind beim R-Cast verwenden.',
'Passiv-Schild, verzögertes Q2, E-Hookshot, R-Unzielbarkeit/Arena.',
'E und Passive gleichzeitig nicht verfügbar. Nach Q2 in Minions fehlt kurzfristig ihr stärkster Trade. Verbleibende R trotzdem einkalkulieren.',
'Jeden Q2-Trade beantworten wollen. Nahe Wand ohne R stehen. Annehmen, dass Ragnarok aus ihrer Arena herauslaufen lässt.',
'Früh Slowpush und sauber crashen. Danach Freeze/kleiner Gegnerüberschuss auf eigener Seite. Auf lange Lane achten, aber Gankwinkel an Wänden ward-en.',
'Passive mit kleinem Trade auslösen. Nach E-Verbrauch Q, an ihr bleiben, Auto–W–Auto. E nach ihrem Schild und nach der R-Unzielbarkeit einsetzen. Q2 mit W abfangen, wenn du nicht ausweichen kannst.',
'Ravenous Hydra für Sustain und Waveclear, danach Death’s Dance gegen physischen Anteil. Stridebreaker bei realistischem Chase statt Hydra. Gegen viel True Damage HP/Schild stärker gewichten.',
'Sterak’s für gemischten Burst/Q2-Puffer. Hullbreaker nur für Turmdruck, wenn Camille nicht frei duellieren kann. Armor allein ist kein Lategame-Counter.',
'1 Item: ihre Sheen-Spikes respektieren, Olaf braucht langen Fight. 2 Items: Camille kontrolliert oft Trade-Länge. 3 Items: Side eher ungünstig, besonders mit häufigem Q2. Pushfenster nutzen und rotieren, statt jeden Turm im 1v1 erzwingen.',
'Brich den ersten Schildtrade ab und greife nach ihrem E erneut an. Halte die Wave nah genug, dass sie für Farm vorlaufen muss. Plane später um ihre Q2-Fenster und vermeide einen erzwungenen Side-Statcheck.',
'PTA, wenn du Camille über Waveclear hältst und im Gesamtspiel auf kurze Carry-Kills gehst. Für echte Side-Duelle bleibt Conqueror sinnvoller.');
add('chogath',"Cho’Gath",'B','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Frühe Boots zum Q-Ausweichen. Mercury’s nur bei AP/CC-Comp.',
'Immobilität und Olafs E begünstigen lange Duelle. Cho-Sustain, hohe HP und Feast bestrafen das Spielen auf extrem niedrigen HP. Ein Lanevorteil verhindert seinen späteren Teamnutzen nicht.',
'Hohe effektive HP verlangen mehrere Q/E-Zyklen. Gegen AP-Cho kann PTA nach verfehltem Q sinnvoll sein, sofern er tatsächlich in drei Autos erreichbar bleibt.',
'Olaf bei Q-Reset-Chase. Cho mit E-Start nicht drei verstärkte Autos gratis geben. Patch 26.17 verstärkt genau diese frühen E-Treffer.',
'Nach verfehltem Q ansetzen. Außerhalb der Minionlinie stehen, damit E nicht gleichzeitig farmt und pokt. Seine Passive durch Wegzonen von Last-Hits begrenzen.',
'R nimmt Q/W-CC den Stoppeffekt. Feast bleibt True-Damage-Burst: W vor der Killgrenze, nicht erst in kritischem HP-Bereich. AP-Build deutlich burstiger als Tank.',
'Q-Knock-up, W-Silence, E-Autofolge, R-Feast.',
'Q verfehlt und W bereits verbraucht. R auf Minion/Objective benutzt schafft ein sichereres Low-HP-Fenster.',
'Olaf-Passive über Feast-Sicherheit stellen. AP- und Tank-Cho gleich itemisieren. Lange Trades in großem Minionüberschuss.',
'Slowpush/Crash früh möglich. Danach auf eigener Seite zonen und Last-Hits verweigern. Freeze aufgeben, wenn seine Q/E-Waveclear einen sauberen Crash erzwingt.',
'Q ausweichen, eigene Q treffen, seitlich der E-Kegel bleiben. Auto–W–Auto und E wiederholen. W gegen seine absehbare Burstfolge reservieren, wenn R bereit ist.',
'Ravenous Hydra, danach Black Cleaver gegen Armor. Gegen HP ohne viel Armor ist Blade of the Ruined King eine offensive Alternative. AP-Cho: Hexdrinker/Maw priorisieren.',
'Sterak’s gegen Feast plus Folgeschaden. MR gegen AP-Burst. Antiheal nicht allein wegen kleiner Passive-Heals vor dem Core erzwingen.',
'1 Item: Olaf kann bei Q-Miss Druck machen. 2 Items: Armor- und HP-Build bestimmen Cleaver/BORK-Wert. 3 Items: killbar bei anhaltendem Kontakt, aber langsam. Cho bleibt als Frontline und Objective-Execute nützlich.',
'Nutze verfehltes Q für lange Trades und verweigere sichere Last-Hits. R macht dich nicht immun gegen Feast. Schilde rechtzeitig und passe das zweite Item an seine tatsächlichen Defensivwerte an.',
'PTA gegen AP-Cho mit kurzem Killfenster oder vier fragile Gegner. Conqueror, wenn Cho die Frontline ist, die du wirklich durchkämpfen musst.');
add('darius','Darius','C','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps bei schwierigen Trades. Bleed und R bleiben gefährlich.',
'Beide können lange All-ins gewinnen. Olafs Chance hängt an Axe-Resets und dem Ausweichen des äußeren Q. Darius gewinnt leicht, wenn er fünf Stacks vor Olafs Gegenschaden erreicht.',
'Einzelne Dreiertrades geben Darius Blutungsstacks, ohne den Fight zu lösen. Conqueror unterstützt das Duell, das nach beiden Cooldown-Rotationen weitergeht.',
'Skillabhängig. Gegen W-Start und Ghost nicht blind facechecken. Mit Q-Start Distanzstaffelung nutzen und nur bei wiederholten Treffern sowie ausgeglichener Wave durchziehen.',
'Nach verfehltem äußeren Q oder verbrauchtem E handeln. In Q hineingehen, wenn sicher, statt beim Rückzug den Rand zu treffen. Bei vier/fünf Stacks ohne Kill sofort Fenster neu bewerten.',
'R negiert Pull/Slow, aber weder Bleed noch Dunk. W rechtzeitig vor R-Burst. Auf niedrigen HP ist ein verlorener Auto besonders teuer.',
'Q-Außenring mit Heal, W-Reset/Slow, E-Pull, Passiv-Stacks und R.',
'Q ohne Champion-Randtreffer plus E verbraucht. Ghost fehlt: lange eigene Lane besser nutzbar. Ein Q-Miss allein bei fünf Bleed-Stacks genügt nicht.',
'Aus Q herauslaufen und dadurch den Außenring treffen. Kämpfen, während W fehlt und Darius volle Stacks hält. Eine Axt in seine verstärkte Wave verfolgen.',
'Keinen Level-2-Nachteil durch sinnloses L1-Chasing. Bei Prio Slowpush crashen, sonst dünnen und auf eigener Seite halten. Freeze nur mit genug HP, um seinen Push zu contesten.',
'Q treffen, Auto–E, Q-Rand innen umgehen. Auto–W–Auto für Gegenschaden/Schild. R für Pull/Slow bei echtem Commit, kurze Äxte aufnehmen und möglichst keinen Auto auslassen.',
'Ravenous Hydra für Rückheilung und AD, danach Death’s Dance. Stridebreaker als Alternative, wenn Ghost-Spacing den Kampf entscheidet.',
'Sterak’s als Puffer gegen Burst. Executioner’s nur bei wiederholt relevanten Q-Heals. Armor hilft gegen Q/Autos, ersetzt kein Q-Dodging.',
'1 Item: Ressourcen und Summoner wichtiger als Name des Cores. 2 Items: DD hilft im physischen Duell, Dunk bleibt. 3 Items: beide tödlich bei Fehlern. Ein klarer Q-Miss kann weiter mehr zählen als allgemeines Scaling.',
'Spiele um den äußeren Q und halte Ghost verfügbar. Committe mit vollständigen Cooldowns, statt Darius einen halben Kampf und fünf Stacks zu schenken. W muss vor seinem tödlichen Dunk kommen.',
'PTA nur wenn die Side nicht dein Auftrag ist und gegnerische Carries in einem kurzen Kontakt sterben. Gegen Darius plus weitere Melees Conqueror.');
add('drmundo','Dr. Mundo','A','Conqueror',"Doran’s Blade + Health Potion",'Ghost + Ignite','Keine zwingenden Tier-2-Boots. Frühe Boots gegen Cleaver-Poke.',
'Mundo hat keinen Dash und seine Passive blockiert Olafs Slow nicht. Olaf kann frühe Farm verweigern. Mit HP-Stacks und R wird das Zeitfenster zum Töten wesentlich länger.',
'Mundos R und HP-Build verlangen anhaltenden Schaden. Conqueror ist für das zweite E und wiederholte Autos sinnvoller als bloßer Anfangsburst.',
'Olaf im Nahkampf. Eigene Minions gegen Cleaver nutzen, Q-Reset nur auf sicherem Weg. Mundo darf aus Distanz farmen, wenn Verfolgen mehr HP kostet als Druck bringt.',
'Nach verfehltem Q vorlaufen. Nicht mit halber HP in mehrere Qs chasen. W-Ende/Heilung respektieren und mit längerer Lane Farmzone wegnehmen.',
'Seine R muss in der Killplanung enthalten sein. Ignite während der relevanten Heilphase, nicht als frühen Poke verschwenden. Olaf-R hauptsächlich für Kontakt und Schaden.',
'Q-Cleaver, W-Heilung, E-Minionschuss, R-Regen. Passive schützt gegen Immobilisierung, nicht jeden Slow.',
'R vorbei/auf Cooldown. Q verfehlt erleichtert Kontakt. Ohne Ignite/Antiheal ist eine frische R kein automatisches Killfenster.',
'R-Heilung ignorieren. Cleaver-Kette beim Chase tanken. Seine Passive mit Olaf-Q „entfernen“ wollen.',
'Früh Slowpush, Crash und Bounce in Freeze umwandeln. Mundo für jeden Nahkampf-Last-Hit in Q-Reichweite zwingen. Hydra erst, wenn Sustain/Push mehr wert ist als Freeze.',
'Hinter Minions Q treffen, seitlich zur Fluchtlinie laufen. Auto–W–Auto–E, kurze Qs. Ignite auf seine R-Heilung legen. Wenn kein Finish möglich, Wave crashen statt HP spenden.',
'Ravenous Hydra, danach Blade of the Ruined King gegen HP-Stacking bei wenig Armor. Bei früher Armor Black Cleaver als zweites Item erwägen.',
'Executioner’s, wenn Ignite fehlt oder nicht jeden Fight deckt. Sterak’s gegen gemischte Comp. Hullbreaker, wenn du bereits Druck ausübst und Türme das Ziel sind.',
'1 Item: deutlicher Druck bei vergleichbaren HP. 2 Items: HP/Armor und Antiheal entscheiden. 3 Items: Mundo kann Kämpfe aussitzen und im Team sehr wertvoll sein. Olaf braucht echten Vorsprung oder passenden Schadensmix.',
'Halte ihn früh von der Wave fern und nutze Minions als Cleaver-Schutz. Plane seine R-Heilung vollständig ein. Kaufe den zweiten Schadensbaustein passend zu HP oder Armor, statt stumpf weiterzudiven.',
'PTA, wenn Mundo nur gefarmt wird und vier andere Gegner kurze Carry-Kills erlauben. Für Side-Killdruck Conqueror. Flash + Ghost bei gefährlichen gegnerischen Wänden/Engages statt Ignite.');
add('fiora','Fiora','E','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps gegen Autos. Vital-True-Damage bleibt ungemindert.',
'Vitals, Riposte und Q-Abstand bestrafen einen geraden Statcheck. Olaf kann frühe verlängerte Trades gewinnen, aber Fiora kontrolliert später häufig die Side und hat bessere Tank-Schadensskalierung.',
'Riposte kann Autos und E entwerten und PTA verzögern. Conqueror passt zum Duell nach W, das mehr als drei Autos braucht. Die Rune ersetzt das Ausweichen ihrer Riposte nicht.',
'Olaf, wenn er eine schlechte vordere Vital vermeidet und Qs aufnimmt. Fiora gewinnt kurze Q-Vital-Trades. Schlechte Vital durch Distanz resetten, falls ohne CS-Verlust möglich.',
'Nach W-Verbrauch verlängern. E nicht offensichtlich als einziger Burst telegraphieren. Q-Landung von Fiora verfolgen, ohne weitere Vitals freizugeben.',
'Olaf-R entfernt keine Fiora-Heilzone und verhindert ihre Vitals nicht. Eigene W vor der schnellen R-Vital-Folge. Wandposition kann eine Vital unzugänglich machen.',
'Passive-Vitals, Q-Repositionierung, W-Riposte und R-Vierfach-Vitals.',
'W verfehlt/abgelaufen plus Q-Rückzug schlecht positioniert. Nach verbrauchter R ist das nächste Duell deutlich übersichtlicher.',
'E in W abgeben. Um sie herum laufen und jede R-Vital schenken. Armor als vollständigen Schutz gegen Fiora betrachten.',
'Wave eigene Seite, damit ihre Q-Trades einen Rückweg kosten. Frühe Prio nur in vollständigen Crash umsetzen. Nicht endlos einfrieren, wenn sie ungestört roamen kann.',
'Q und Auto zum Antesten, W-Riposte sidesteppen. Erst danach Auto–W–Auto–E beschleunigen. Mit Rückseite zur geeigneten Wand kämpfen, ohne dich in einen Gank einzuschließen.',
'Ravenous Hydra gegen ihr Sustain, danach Death’s Dance bei hohem physischen Anteil oder Sterak’s für einen größeren Schildpuffer. Kein Armor-Rush ohne Schadensplan.',
'Executioner’s für R-Heilzone/Lifesteal. Hullbreaker nur zum Ausnutzen ihrer Abwesenheit. Kritlaf ist hier kein verlässlicher Counter gegen W und Vital-Burst.',
'1 Item: beide können durch Timing gewinnen. 2 Items: Fioras wiederholte Q/Vitals gewinnen an Wert. 3 Items: klare Vorsicht im offenen 1v1 bei Gleichstand. Wave schnell bearbeiten, dann mit Team Überzahl herstellen.',
'Spare E bis nach Riposte und schütze deine Vitals mit Positionierung. Erzeuge den langen Trade erst nach ihrem W. Nutze frühe Druckphasen für Farm und Türme, bevor das gleichwertige Side-Duell kippt.',
'PTA, wenn dein Team Fiora auf der Side übernimmt und du fragile Gegner angreifen sollst. In der Lane Conqueror als Standard.');
add('gangplank','Gangplank','B','PTA',"Doran’s Shield + Health Potion",'Flash + Ghost','Frühe Boots zum Barrel-Spacen. Steelcaps gegen Q/Autos, kein vollständiger Barrel-Schutz.',
'Ohne Barrel-Netz ist Gangplank ein erreichbares, wenig robustes Ziel. Olaf-R übergeht Slows, aber nicht Barrel-Schaden und passive True-Damage-Resets. Gute Fasskontrolle kann die Lane drehen.',
'Nach zerstörtem Fass bekommt Olaf oft drei Autos, bevor ein neues Netz steht. Dieses begrenzte Killfenster passt zu PTA. Langes Kämpfen durch mehrere passive Resets vermeiden.',
'Olaf im langen Kontakt, Gangplank beim Q-Poke. Eigene Q für Druck, nicht blind durch passiven Auto und Minions anlaufen.',
'Nach verlorenem Fass-Timing oder leeren Charges anlaufen. Seine W reinigt einen Slow: nächste Axt bereithalten, nicht sofort alle Mobilität verbrauchen.',
'R erlaubt Chase durch Slows. Fassschaden bleibt voll relevant. Gangplanks R kann deine Wave und den Rückweg bestrafen, deshalb vor Commit HP und Jungle prüfen.',
'E-Fässer/Chain, Passive-Resets, W-Heal/Cleanse, R-Zone.',
'Fass zerstört und keine gute Reserveposition. W verwendet: nächste Q bleibt besser haften. Nicht in ein bereits vorbereitetes zweites Fass laufen.',
'Auf ein Fass und Champion zugleich ohne Timing fokussieren. R als Schadensimmunität behandeln. Mehrere passive Procs gratis nehmen.',
'Anfangs HP erhalten. Bei gewonnenem Fassduell Slowpush crashen. Eigene Seite bietet lange Chase-Lane, aber ein stationärer Freeze in seinem Fassnetz ist wertlos.',
'Fass contesten oder Chain-Radius verlassen. Q auf Gangplank, W-Cleanse abwarten, zweite Q. Auto–W–Auto und dritten Auto sichern, E zwischen sichere Treffer legen. Fassspawn sofort neu bewerten.',
'Stridebreaker für dauerhaftes Nahbleiben, danach Death’s Dance gegen physischen Burst. Ravenous Hydra stattdessen, wenn Q-Poke/Wave-Sustain das größere Problem ist.',
'Sterak’s gegen Barrel-Combo. Bei klarer Führung Fiendhunter Bolts nach einem AD-Core für kurzen R-Burst, später Infinity Edge nur mit zuverlässiger Uptime und tragbarer Defensive.',
'1 Item: Scheen/Trinity-Spike und Fassschaden respektieren. 2 Items: Olaf gewinnt erreichbare Kämpfe ohne Fassnetz. 3 Items: Crit-Barrels können vor Kontakt entscheiden. GP hat starken Fernnutzen, auch wenn er Side-Duelle vermeidet.',
'Gewinne erst das Fassfenster, dann den Champion-Fight. Hebe eine zweite Q für seine Orange auf. Verfolge nur, solange kein neues Barrel-Netz zwischen dir und den sicheren Autos steht.',
'Conqueror bei tankigem Gangplank-Build oder mehreren robusten Melees, die du länger bekämpfen musst.');
add('garen','Garen','D','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps gegen Q/Autos. Sein E und R brauchen zusätzliche Planung.',
'Olaf kann frühe längere Trades erzwingen. Garen entkommt mit Q/Bewegungsrune, heilt Pausen aus und bestraft Olafs niedrige HP mit R. Gesamtspiel schwieriger als ein isolierter früher Statcheck.',
'W reduziert den frontloaded Burst, E hält den Kampf aktiv. Conqueror für langen Kontakt nach seinem ersten Trade. PTA nur, wenn du ihn wirklich vor dem Rückzug töten kannst.',
'Olaf bei mehrfachen Äxten. Garen-Q kurz abfangen, danach bestrafen. Nicht unnötig viel Wave-Aggro nehmen, das er später per Passive ausheilt.',
'W früh herauslocken, nach Ablauf verlängern. Q reinigt Slow: Folgewurf zurückhalten. Bei aktivierter Bewegungsrune nicht Ghost blind in seinen Turm verbrennen.',
'R entfernt Silence, verhindert aber Garens Execute nicht. W früh genug vor der R-Killgrenze. Garen kann erst disengagen und mit wiederhergestellten HP neu kommen.',
'Q-Slowcleanse/Silence, W-Defensive, E-Isolationsschaden, R-Execute, Passive.',
'W abgelaufen und Q/Bewegungsrune verbraucht. Nach R-Verbrauch darf Olaf niedrige HP offensiver nutzen, sofern der restliche Schaden kalkuliert ist.',
'Seine Passive zwischen jedem Trade komplett regenerieren lassen. Auf extrem niedrigen HP W sparen. Nur Armor kaufen und Execute vergessen.',
'Frühen Slowpush zum Crash, danach eigene Seite und mit Q Passive unterbrechen, wenn manasparend möglich. Kein sinnloses Dauerpushen, das ihm sicheren Sustain erlaubt.',
'Q/kleiner Trade löst W aus. Nach W Auto–W–Auto–E, nächste Q nach seinem Q-Cleanse. R gegen Silence bei Commit. W-Timing vor tödlichem Burst wichtiger als maximale Missing-HP-Ausbeute.',
'Ravenous Hydra zum Ausgleich seines Sustains, dann Sterak’s gegen Burst/Execute-Puffer. Death’s Dance, wenn AD-Comp den größeren Schaden liefert.',
'Black Cleaver bei echter Armor. Hullbreaker nur, wenn du bereits Side-Prio hast. Kritlaf aus Rückstand erhöht die Gefahr, vor dem eigenen Schaden zu sterben.',
'1 Item: Olaf kann nach W gewinnen, Garen kann Trades verweigern. 2 Items: Execute und Beweglichkeit erschweren den Abschluss. 3 Items: offener Statcheck bleibt ressourcenabhängig, Garen hat oft leichtere Pick-Ziele im Teamfight.',
'Ziehe W und Q heraus, bevor du die lange Verfolgung startest. Nutze Hydra, damit seine Passive nicht jeden abgebrochenen Trade gewinnt. Spiele nach Level 6 niemals absichtlich bis unter seine R-Killgrenze.',
'PTA, wenn der Plan ein kurzer Dive auf andere Gegner ist. Conqueror für Garen plus robuste Frontline.');
part2(add); part3(add); part4(add); part5(add);
matchups.sort((a,b)=>a.name.localeCompare(b.name,'de'));
