export default function(add){
add('riven','Riven','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps bei AD-Druck.',
'Ragnarok entwertet ihre CC-Kette; Olaf kann nach verbrauchten Dashes durchkämpfen. Gute Riven-Spielerinnen handeln kurz und lassen R auslaufen.',
'Mehrere Dash-/Schildzyklen unterbrechen drei frühe Autos. Conqueror lässt sich über Q/E und anschließenden Kontakt nutzen; kein Grund, blind hinterherzulaufen.',
'Olaf im dauerhaften Fight. Gegen Q-Start ihre Kette nicht gratis tanken; nach Q3 Druck, sofern sie Q nicht vorab zeitlich gestreckt hat.',
'Nach E und Q3 anlaufen. Keine lange Verfolgung, wenn Q-Cooldown durch vorbereitete Q-Kette bereits fast zurück ist. W vor ihrem entscheidenden Burst.',
'R nimmt Stun/Knock-up, Riven-R2 bleibt gefährlicher Finisher. R erst, wenn sie ihre Mobilität nicht komplett zum Auslaufen verwenden kann.',
'Q-Kette und Vorbereitung, E-Schild/Dash, W-Stun, R2.',
'E plus Q-Kette verbraucht; R2 verfehlt. Fehlende W erleichtert Kontakt vor 6.',
'CD von Q3 an wie eine komplett frische Q behandeln; auf minimalen HP R2 tanken; R aus Distanz starten.',
'Eigene Lanehälfte bevorzugen. Nach verbrauchter Kombo Slowpush; Freeze hält ihren Rückweg lang. Kein Dive mit offenen Dashes.',
'Q auf Landepunkt, kurze Autos/E bis E verbraucht ist. Danach Auto–W–Auto und Q-Pickups. R für CC im Commit, seitlich gegen R2 bewegen.',
'Ravenous Hydra für wiederholte Trades, danach Death’s Dance. Stridebreaker bei sehr gutem gegnerischem Spacing.',
'Sterak’s gegen Execute-Burst; Fiendhunter Bolts bei Vorsprung und sicherer Auto-Uptime. Kein voller Crit-Rush in ihre Burstcombo.',
'1 Item: gute lange Trades bei gleichen HP. 2 Items: Armor stabilisiert. 3 Items: Side weiterhin spielbar, aber Riven kann über Terrain und Burst den Fight wählen.',
'Zwinge Riven zuerst zu E und ihrer Q-Kette. Kämpfe anschließend mit R durch ihre Kontrolle. Spare genug HP und Schild für R2.',
'PTA, wenn du nach verbrauchten Dashes zuverlässig drei Autos bekommst und die gegnerische Comp kurze Killfenster verlangt.');
add('rumble','Rumble','D','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Boots zum Verlassen von Q/R; Mercury’s bei AP-Last.',
'Rumble verursacht viel Schaden, ohne Olaf mit reinem CC stoppen zu müssen. Heat, Harpunen und Equalizer bestrafen geradlinigen Kontakt.',
'Schild und Overheat-Autos erzeugen echte längere Melee-Fights. PTA kann funktionieren, ersetzt aber nicht das Überleben seiner Heat-Phase.',
'Olaf mit sauberer Q-Verfolgung; Rumble gewinnt, wenn du in seinem kompletten Flammenwerfer bleibst. Heat und gelernten Spell erst beobachten.',
'Außerhalb seines Q-Kegels bleiben. Nach Q/W-Verbrauch bei beherrschbarer Heat angreifen; Overheat nicht automatisch als wehrloses Fenster ansehen.',
'Ragnarok entfernt keine Brandfläche. Equalizer quer verlassen, erst dann weiterkämpfen. Low-HP-All-in mit aktiver Brandfläche ist riskant.',
'Heat/Overheat-Autos, Q-Flammenwerfer, E-Harpunen, W-Schild/Tempo, R-Zone.',
'Q beendet und W verbraucht; R verfehlt oder bereits verlassen. Harpunen-Ladungen mitdenken.',
'Im Q/R stehenbleiben; Overheat mit Schadenslosigkeit verwechseln; R als Immunität gegen den Magieschaden behandeln.',
'Wave auf eigener Seite, aber nicht im Q-Kegel mit der Wave stehen. Gute Reset-Windows höher gewichten als erzwungenen Freeze bei sehr wenig HP.',
'Harpune ausweichen, Q treffen, seitlich an den Flammen vorbei gehen. Auto–E–W–Auto; bei Equalizer zunächst kurze Querbewegung aus der Zone.',
'Ravenous Hydra gegen wiederholten Poke, danach Maw. Stridebreaker, wenn du gesund bist, aber keinen Kontakt bekommst.',
'Früher Hexdrinker bei drohendem Burst; Spirit Visage später bei mehreren AP-Quellen und Verbündetenheilung. Kein Crit vor ausreichendem Überleben.',
'1 Item: HP beim Einstieg entscheidend. 2 Items: Maw öffnet stabilere All-ins. 3 Items: Side oft besser spielbar als frühe Lane, Rumble bleibt sehr starker Objective-Fighter.',
'Bewahre HP und suche ein Fenster nach Q/W. Laufe quer aus Equalizer, bevor du weiter angreifst. Sein fehlender CC macht ihn für Olaf nicht automatisch einfach.',
'PTA bei sicherem kurzem Zugang zu vier fragilen Teamgegnern; Conqueror für Rumble und andere längere Melee-Fights.');
add('sett','Sett','D','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh gegen Auto-/Q-Druck.',
'Sett kann Olafs Low-HP-Plan mit W-True-Damage und starker Auto-Kette bestrafen. Olaf gewinnt bei vermiedener W-Mitte und sauberem Re-engage.',
'Grit-Schild und mehrere Autozyklen verlängern das Duell. Conqueror passt zum Kampf nach Setts erster Schadensphase.',
'Olaf bei Q-Abstand/Resets, Sett bei unkontrolliertem Nahkampf und gutem E. Nicht beide Seiten seines E mit eigenen Minions ermöglichen.',
'Kurze Trades, bis W verbraucht ist. Grit beobachten; nach hoher Grit nicht statisch vor ihm stehen. W-Schild auslaufen lassen, wenn sicher.',
'R verhindert Setts kontrollierende Bewegung bei rechtzeitigem Einsatz, aber nicht automatisch den Schaden seiner R/W. Position zu Turm und Team beachten.',
'E-Stunbedingung, Q-Doppelschläge, Grit/W-Mitte, R-Repositionierung.',
'W verbraucht/verfehlt und E fehlt. Ein volles Grit-Band ist Gefahr, kein Einladungssignal.',
'W-Mitte tanken; gleichzeitig von E plus W fixiert werden; auf minimalen HP vor voller Grit stehen.',
'Eigene Seite mit seitlichem Ausweichraum. Nach W-Verbrauch Slowpush. Nicht in enger Passage oder unter seiner Turmkante traden.',
'Q–Auto–E, seitlich bewegen. W erzwingen, Mitte verlassen, Schild abklingen lassen; dann Auto–W–Auto und Q-Chase.',
'Ravenous Hydra für Reset-Sustain, dann Death’s Dance gegen physischen Druck. Stridebreaker erleichtert Positionierung/Kontakt, schützt aber nicht vor W-Mitte.',
'Sterak’s als HP-/Schildpuffer; BotRK gegen hohen HP-Build, wenn du W ausweichst und genügend Defensive hast. Armor löst True Damage nicht.',
'1 Item: W-Dodge entscheidet. 2 Items: gute Duelle nach gezogenem W. 3 Items: hoher HP-/AD-Sett bleibt mit W gefährlich, selbst aus Rückstand.',
'Spiele den Kampf in zwei Phasen: W ziehen, dann wieder rein. Halte seitlichen Raum frei. Deine passive Heilung rettet dich nicht zuverlässig vor der W-Mitte.',
'PTA bei kurzen Team-Catches möglich; im wiederholten Sett-All-in Conqueror bevorzugen.');
add('shen','Shen','B','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Keine Pflicht-Boots; Plated Steelcaps bei viel gegnerischem Auto-Schaden.',
'Olaf übergeht Taunt mit R und kann lang kämpfen. Shens W entzieht jedoch Autos und Heilung; empowered Q macht die ersten Level gefährlich.',
'W pausiert Auto-Uptime, Q/E können Conqueror aufbauen. Nach der Zone folgt ein längerer Fight gegen Schild und HP.',
'Shen mit durch Olaf gezogener Klinge und empowered Q sehr stark. Nicht zwischen ihm und Klinge stehen; nach Q-Autos längeren Fight suchen.',
'W herauslocken und verlassen. Nach E-Verbrauch ohne frisches Q-Fenster nachsetzen. Passive Schildzyklen nicht ignorieren.',
'R nimmt Taunt, nicht W-Auto-Block. Shen-R auf andere Lane: früh pingen, Kanal vor eigener R mit keinem Hard-CC abbrechbar; Druck durch Crash/Turm.',
'Klingenposition/empowered Q, W-Zone, E-Taunt, passive Schild, globale R.',
'W beendet und E verbraucht. Nach seinen empowered Q-Autos besseres Nahkampffenster.',
'W-Autos in seine Schutzfläche verschwenden; vor 6 Klinge durchziehen lassen; R-Roam ohne Wave-Gegenwert zulassen.',
'Früh nicht blind pushen. Später Slowpush zur möglichen R-Rotation, damit sein Verlassen der Lane Minions/Turm kostet.',
'Q treffen, Klingenlinie vermeiden, Auto–E. W-Zone kurz verlassen, danach Auto–W–Auto; R für E im tatsächlichen Commit.',
'Ravenous Hydra für Waveclear und Sustain, dann Black Cleaver gegen Armor oder Death’s Dance gegen AD-Comp.',
'Hullbreaker nach Kampf-Basis, wenn Shen wiederholt wegultet und du sicher Türme schlagen kannst. Nicht kaufen, wenn du ständig zu Objectives gruppieren musst.',
'1 Item: Waveclear bestraft R. 2 Items: lange Duelle spielbar nach W. 3 Items: Side-Druck gut, Shens globaler Einfluss kann dennoch größer sein.',
'Respektiere Klinge und W, bis Shen seine defensive Phase verbraucht hat. Kämpfe erst dann durch. Bereite Waves so vor, dass seine globale R einen echten Preis hat.',
'PTA bei überwiegend kurzen Carry-Catches; Lane-W bleibt ein Gegenargument gegen erzwungene drei Autos.');
add('singed','Singed','B','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Boots of Swiftness gegen dauerhaftes Spacing; MR nach Comp.',
'Olaf kann Fling/Slow mit R übergehen, muss Singed aber erreichen. Giftspur und hohes Lauftempo können seine R ohne Auto-Kontakt auslaufen lassen.',
'Wiederholte kurze Kontakte und Singed-R-Defensivwerte machen den Fight länger. PTA scheitert oft an fehlenden drei ununterbrochenen Autos.',
'Olaf im direkten Nahkampf, Singed beim Hinterherlaufen durch Gift. Q auf seinen Weg, nicht minutenlang hinter seiner Spur herlaufen.',
'Fling-Verbrauch nutzen und vor Singed statt hinter ihn laufen. W-Zone vor 6 respektieren. Proxy nicht ohne Wave-/Jungle-Abwägung verfolgen.',
'R neutralisiert Kontrolle, nicht Gift oder die Heilungsreduktion seines R-verstärkten Q. Aktive Singed-R ist oft ein Grund, den Chase abzubrechen.',
'Q-Giftspur, E-Fling, W-Zone, R-Tempo/Defensive und Antiheal.',
'R beendet, E verbraucht und Fluchtweg abgeschnitten. Proxy nur mit sicherem zweiten Zugriff als Killfenster.',
'Blind Gift nachlaufen; Wave für aussichtslosen Proxy-Chase verlieren; mit geringer HP seine R-Heilungsreduktion ignorieren.',
'Waves sicher einsammeln, Crash/Reset planen. Freeze nur solange Singed die Lane wirklich spielt. Gegen Proxy lieber Ressourcen sichern und Ausgangswege bedrohen.',
'Q vorauswerfen, seitlich abschneiden, Auto–E–W–Auto bei Kontakt. Wenn er R zündet und Abstand schafft, Wave nehmen statt eigene R ohne Verlängerung zu verbrennen.',
'Stridebreaker für Kontakt, danach Maw bei AP-Druck. Ravenous Hydra, wenn Proxy und Sustain wichtiger als Solo-Kills sind.',
'Hullbreaker für sichere Turmzeit nach Push, nicht als Antwort auf jeden Proxy. Spirit Visage bei AP/Verbündetenheilung; Antiheal reduziert trotzdem deinen Sustain.',
'1 Item: Kontakt bleibt Hauptfrage. 2 Items: MR hilft, erzwingt aber keine Kills. 3 Items: Singed kann Duelle verweigern und im Teamfight stören; Wave- und Objective-Wert zählen.',
'Schneide Singed den Weg ab, statt Gift zu verfolgen. Nutze fehlende R oder verbrauchtes E. Wenn er keinen Fight anbietet, gewinne über Waves und sichere Türme.',
'PTA, wenn die restliche Comp kurze sichere Auto-Catches bietet und du Singed nur auspushst.');
add('sion','Sion','A','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Basis-Boots zum Q-Verlassen; Upgrades nach Comp.',
'Ragnarok entwertet Sions CC, E hilft gegen Armor. Seine HP und sichere Waveclear-/R-Flucht verhindern trotzdem kostenlose Kills.',
'Hohe effektive HP und W-Schild verlangen mehrere Auto-/E-Zyklen. Conqueror passt besser als kurzer Frontload.',
'Olaf nach ausgewichenem Q. Nicht für Axtpickup im geladenen Q stehen; seitlich aus dem Kegel.',
'Q verfehlt und W verbraucht: langer Trade. Shield-Burst vermeiden und E-Minions nicht geradlinig tanken.',
'R verhindert Knock-up/Stun, nicht R-Aufprallschaden. Sion kann seine R zur Flucht nutzen; ohne Killchance Wave/Turm nehmen.',
'Q-Aufladung, W-Schild/Explosion, E-Slow, R-Flucht, Todespassive.',
'Q verfehlt plus W weg. R-CD nimmt den langen Fluchtweg. Nach Kill der Todespassive sicher ausweichen.',
'Q voll tanken; nach Kill für Minions neben Zombie stehen; R durch gegnerische Turmzone verfolgen.',
'Slowpush und Bounce zu dir für lange Trades. Hydra nutzen, um seine Pushstrategie zu beantworten. Nicht für Kill eine große Wave verlieren.',
'Q treffen, seinen Q-Kegel seitlich verlassen, Auto–E. Nach W-Burst Auto–W–Auto und kurze Äxte; eigene R erst bei sicherem Anschluss.',
'Ravenous Hydra, danach Black Cleaver gegen Armor. BotRK als zweite Alternative gegen viel HP bei wenig Armor und ausreichendem Überleben.',
'Hullbreaker, wenn du dauerhaft Side/Türme spielen kannst. Sterak’s gegen gegnerischen Team-Burst. Kein voller Crit-Build allein, weil Sion langsam ist.',
'1 Item: gute Sustain-Lane. 2 Items: Shred oder HP-Schaden hält Side-Druck. 3 Items: riesige HP können Kills verlangsamen; Wave und Türme wichtiger als ständiges All-in.',
'Weiche dem geladenen Q aus und greife nach W an. Nutze deinen Druck für Waves und Türme. Nach dem Kill Abstand zur Todespassive halten.',
'PTA bei fragiler Backline und wenn Sion auf der Side nur gecleart werden muss.');
add('sylas','Sylas','B','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Frühe Boots zum E-Dodgen; Mercury’s bei AP/CC-Comp.',
'Olaf kann Sylas nach E-Verbrauch durch längeren Schaden schlagen. Sylas-W-Heilung und gestohlene R machen Low-HP-Rennen riskant.',
'W-Heilung und erneute E-/Passivzyklen verlangen anhaltenden Schaden. Conqueror profitiert vom langen Nahkampf.',
'Olaf im langen Fight mit Q-Resets. Sylas-Passivautos nach E nicht gratis tanken; nach seinem Spellzyklus Platz gewinnen.',
'E2 durch Minions erschweren. Nach E-Verbrauch gehen, W-Heilung bei niedrigen HP einplanen. Kein Dive nur aufgrund seiner aktuellen HP.',
'Sylas kann Ragnarok stehlen und selbst CC-immun kämpfen. Dein Q-Slow ist dann keine verlässliche Bindung; sein eigener Schadens-/Heilungszyklus bleibt relevant.',
'W-Heilung, E2-Zugang, passive Autos, gestohlene R.',
'W gerade benutzt und E verfehlt/weg. Gestohlene R beendet verbessert deinen Q-Chase.',
'Sein W auf Low-HP ignorieren; gestohlene Olaf-R als nutzlos ansehen; für E2 freien Winkel anbieten.',
'Eigene Seite mit Minion-Schutz gegen E2. Nach gutem Trade Slowpush; ohne W-Fenster keine Low-HP-Turmjagd.',
'Q treffen, E2 ausweichen, Auto–E. W-Heilung mitrechnen, danach eigenes W–Auto und kurze Qs; bei gestohlener R auf Laufwege statt Slow vertrauen.',
'Ravenous Hydra für wiederholte Trades, danach Maw. Stridebreaker bei Kontaktproblemen, dessen Slow gegen aktive gestohlene R nicht einplanen.',
'Executioner’s vor knappem All-in, wenn W den Unterschied macht. Spirit Visage später bei mehreren AP-Quellen und Teamheilung.',
'1 Item: stabile lange Trades bei guten HP. 2 Items: Maw hilft gegen Burst. 3 Items: gestohlene Ult-Auswahl im Gesamtspiel kann stärker wiegen als das Lane-Duell.',
'Blockiere E2 mit der Wave und greife nach W an. Rechne seine Heilung in den Kill ein. Wenn er Ragnarok stiehlt, brauchst du echten Kontakt statt eines Q-Slows.',
'PTA bei vier fragilen Zielen und kurzem Zugriff; Conqueror, wenn Sylas/weitere Melees wiederholt durchgekämpft werden müssen.');
add('tahmkench','Tahm Kench','C','Conqueror','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Boots für Q/W-Dodge; Mercury’s nur mit zusätzlichem AP/CC-Wert.',
'Olaf kann CC mit R neutralisieren, Tahms graue HP/Schild und Heilung verlängern das Duell stark. Vor 6 bedrohen drei Stacks die Laneposition.',
'Mehrere effektive HP-Balken und Q-Heilung brauchen nachhaltigen Schaden. PTA allein überwindet seine defensive Phase selten.',
'Olaf im freien langen Kontakt mit Q-Resets. Tahm gewinnt einzelne Q/Auto-Trades; Q hinter Minions vermeiden.',
'Passive Stacks beobachten; bei hoher Stackzahl nicht zur Turmseite ziehen lassen. Nach Q-Verfehlung und W-Verbrauch verlängern.',
'Aktives Olaf-R verhindert gegnerisches Verschlingen. Nicht darauf bauen, nach bereits erfolgreichem Devour noch frei reagieren zu können. R rechtzeitig bei drohendem dritten Stack nutzen.',
'Q-Heilung/Stun, drei passive Stacks, W-Zielkreis, E-graue HP/Schild, R-Devour.',
'Q verfehlt und W benutzt; E-Schild abgelaufen. Mehrere defensive Werkzeuge zusammen weg sind wichtiger als ein einzelner Q-CD.',
'Graue HP ignorieren; drei Stacks am gegnerischen Turm zulassen; im W-Landekreis stehen bleiben.',
'Auf eigener Seite halten, damit Devour keinen Turmkill vorbereitet. Nach verbrauchtem W Crash; Freeze nicht mit riesiger gegnerischer Wave erzwingen.',
'Q durch Minionwinkel vermeiden, eigene Q treffen, Auto–E. W-Kreis verlassen; nach Schildphase Auto–W–Auto. R vor drohendem Devour im Commit.',
'Ravenous Hydra für Sustain, danach Black Cleaver gegen Armor. BotRK bei hohem HP-Anteil und beherrschbarem Armor-Wert als offensive Alternative.',
'Executioner’s bei relevanter Q-/Build-Heilung, nicht als Schildkonter. Maw bei AP-Burst; Sterak’s bei gemischter Bedrohung.',
'1 Item: schwer zu töten ohne lange Lane. 2 Items: Shred/HP-Schaden verbessert Duell. 3 Items: Armor, Schildtiming und Teamhilfe entscheiden; Tahm kann lange stallen.',
'Halte die Wave fern vom gegnerischen Turm. Kämpfe nach verfehltem Q und verbrauchtem W, mit seinem Schild als eigener Phase. Setze R rechtzeitig gegen drohendes Verschlingen ein.',
'PTA bei kurzen Carry-Catches im Gesamtspiel; für Tahms lange Side-Duelle Conqueror.',
'Devour-Timing ist mechanisch sensibel: Prävention mit aktivem R als Plan, keinen nachträglichen Befreiungs-Trick voraussetzen. Tier ist qualitative Einschätzung.');
add('teemo','Teemo','A','PTA','Doran’s Shield + Health Potion','Flash + Ghost','Frühe Boots; Mercury’s bei AP-Schaden, Swiftness bei dominierendem Kiting.',
'Vor 6 unterbricht Blind Autos/Heilung, ab 6 kann Olaf ihn mit R neutralisieren. Pilzwege und Vorsprung entscheiden weiterhin den Zugang.',
'Mit R oder nach Blind-Ende sind drei Autos im kurzen Kontaktfenster realistisch. Ohne dieses Fenster ist PTA nicht zuverlässig.',
'Teemo bestimmt sichere Range-Autos. Olaf mit Q-Treffer und langer Chase-Linie stark; nicht blind in Minionaggro nachlaufen.',
'Blind herauslocken. Währenddessen Q/E nutzen oder Abstand, eigenes W-Autofenster nach Blind legen. HP für den späteren Einstieg erhalten.',
'R entfernt/verhindert Blind, nicht Gift- und Pilzschaden. Sicheren Laufweg mit Sweeper vorbereiten; ein aufgedeckter Pilz ist noch gefährlich.',
'Q-Blind, E-Gift, W-Tempo, R-Pilze und passive Unsichtbarkeit.',
'Q weg vor 6; W-Tempo verbraucht; ab 6 R/Ghost plus freier Weg und ausreichend HP.',
'W-Autos in Blind verschwenden; durch mehrere Pilze chasen; Sweeper als automatische Entschärfung oder True Sight behandeln.',
'Früh Wave zu dir, ausdünnen statt unter riesigem Stack tanken. Nach gewonnenem Trade crashen; vor erneutem langen Push Pilzzonen prüfen.',
'Q treffen, nach Blind entweder warten oder R im Commit. Auto–W–Auto–Auto, E zwischen Autos; kurze Qs und pilzarmen Fluchtweg wählen.',
'Stridebreaker für Kontakt, danach Maw bei AP-Druck. Ravenous Hydra statt Stride, wenn wiederholter Poke den Zugang verhindert.',
'Sweeper/Control Wards zur Wegkontrolle. Fiendhunter Bolts nur bei sicherer Uptime; Spirit Visage später gegen AP und mit zusätzlicher Teamheilung.',
'1 Item: R/Stride erlauben Druck. 2 Items: MR stabilisiert. 3 Items: Pilznetz und Kiting können Side verweigern; nicht ohne Vorbereitung in seine Zone.',
'Bewahre HP bis zu einem echten Kontaktfenster. Neutralisiere Blind mit R und benutze W erst für treffende Autos. Deine Route durch die Pilze ist oft wichtiger als ein weiteres Schadensitem.',
'Conqueror bei mehreren langlebigen Melees im restlichen Team; Teemo allein rechtfertigt dann nicht zwingend PTA.');
add('trundle','Trundle','E','Conqueror','Doran’s Blade + Health Potion','Flash + Ghost','Plated Steelcaps früh gegen Auto-/Q-Schaden.',
'Trundle gewinnt viele reine Nahkampfrennen durch Q-AD-Verschiebung, W-Attack-Speed und R-Stat-Steal. Olaf muss seine Buffphasen ausspielen.',
'Beide heilen und liefern über viele Autos Schaden. Conqueror ist für den langen Statcheck passender als kurzer PTA-Frontload.',
'Nicht blind statchecken: Trundle-Q verschiebt AD zu seinen Gunsten. Mit Q-Reichweite traden und ohne freien Rückweg keinen reinen Auto-Fight erzwingen.',
'Außerhalb seiner W-Zone kämpfen. Nach Q kurz handeln, aber dessen schneller Rückkehr bewusst bleiben. Säule kann Axe-Pickups und Rückzug blockieren.',
'Olaf-R reinigt Trundles Stat-Steal nicht. Seine R ziehen, per Q Abstand herstellen und nach Ende neu prüfen; eigener R-Einsatz ist kein automatischer Counter.',
'Q-AD-Steal/Reset, W-Zone, E-Säule als Terrain, R-Stat-Steal/Drain.',
'W und R beendet; E verbraucht öffnet Rückweg. Ein einzelnes Q auf Minion reicht selten für volles All-in.',
'In W plus R stehenbleiben; Säule mit R durchlaufen wollen; niedrige HP als sicheren Vorteil ansehen.',
'Wave auf eigener Seite, aber genügend Platz weg von W/Säule. Nach gezogenem R crashen oder resetten; keine endlose stationäre Farmduell-Abmachung.',
'Q–E und wenige Autos außerhalb W. Bei R per Q kiten, wenn möglich; nach Buff-Ende Auto–W–Auto und kurze Äxte für den erneuten Fight.',
'Ravenous Hydra für kurze Trades/Reset-Sustain, danach Death’s Dance. Stridebreaker erleichtert Abstand und Wiederkontakt, gewinnt den Statcheck aber nicht allein.',
'Executioner’s bei entscheidendem Heal-Fight; BotRK erst mit ausreichend Defensive. Randuin’s gegen Crit-Anteile der Gesamtcomp, nicht als genereller Trundle-Counter.',
'1 Item: Trundle im reinen Duell gefährlich. 2 Items: R/W-Management bleibt entscheidend. 3 Items: seine Side/Turmdrohung ist groß; Hilfe und Objective-Timing nutzen.',
'Kämpfe nicht stationär in Trundles W und R. Ziehe seine Buffs, schaffe Abstand und suche den zweiten Einstieg. Deine R entfernt weder Säule noch Stat-Steal.',
'PTA für kurze Team-Catches möglich; ohne Side-Hilfe verschärft fehlender Conqueror das Trundle-Duell.');
}
