export default function(add){
add('gnar','Gnar','A','PTA',"Doran’s Shield + Health Potion",'Flash + Ghost','Plated Steelcaps gegen Mini-Gnar-Autos. Boots früh für Q-Ausweichen.',
'Mini-Gnar ist nach Hop-Verbrauch verwundbar, Mega-Gnar verliert gegen Ragnarok viel Kontrolle. Hop, Hyper-Tempo und Transformation verhindern trotzdem einen blinden Chase.',
'Nach Hop entsteht ein begrenztes Fenster mit zuverlässigen Autos auf Mini-Gnar. PTA nutzt es. Gegen ausschließlich lange Mega-Duelle ist Conqueror erwägenswert.',
'Olaf im Kontakt, Mini-Gnar beim freien Poke. Q durch die Wave drohen und Bushes nutzen, ohne zu viel HP für Level-1-Druck zu zahlen.',
'Nach E/Hop Druck, aber Rage prüfen. Nicht auf Minions zulaufen, die ihm einen sicheren Doppelhop geben. Vor hoher Rage kein unvorbereitetes All-in.',
'R kann Mega-CC neutralisieren. Zusätzliche HP und Schaden der Transformation bleiben. Mini-Gnar ohne E ist meist das bessere Killziel.',
'E/Hop, Rage/Transformation, W-Dreierproc, Mega-R an Wänden.',
'Hop verbraucht und Rage niedrig oder gerade zurücktransformiert. Verfehltes Q ohne sicheren Fang verschlechtert seinen Rückzug.',
'Bei fast voller Rage committen. Doppelhop ermöglichen. R früh starten, bevor er zweimal wegspringt.',
'Gegen Range eher eigene Seite. Nach Hop-Verbrauch Slowpush und vollen Crash. Cheater nur mit gewonnener Prio, nicht gegen fortlaufenden Poke erzwingen.',
'Q treffen, Hop auslösen, Landepunkt mit Ghost anlaufen. Zweite Q, Auto–W–Auto und PTA fertigstellen. R erst, wenn Kontakt gegen CC gehalten werden muss.',
'Stridebreaker, danach Experimental Hexplate für den nächsten R-Chase. Ravenous Hydra statt Stride, wenn du mehr Sustain als zusätzliche Bindung brauchst.',
'Death’s Dance gegen AD-Comp. Sterak’s gegen Transformation/Burst. Fiendhunter Bolts nur mit Vorsprung und erreichbarem Mini-Gnar, nicht als Lösung gegen Doppelhop.',
'1 Item: gutes Catch-Fenster mit Stride. 2 Items: R/Hexplate erlauben Druck, E bleibt Schlüssel. 3 Items: Mini kann stärker kiten, Mega hat mehr Teamnutzen. Side-Prio in Objectives umsetzen.',
'Lies Rage und Hop vor jedem Anlauf. Lass dich kurz poken, statt einen Chase in die Transformation zu erzwingen. Nach seinem Sprung ist deine Chance, die Lane lang zu nutzen.',
'Conqueror bei Tank-Gnar plus langer gegnerischer Frontline. PTA für Mini-Catches und Carry-Zugriff.');
add('gragas','Gragas','B','Conqueror',"Doran’s Shield + Health Potion",'Flash + Ghost','Boots früh. Mercury’s bei AP-Druck plus sonstigem CC, nicht nur wegen E.',
'Ragnarok bricht sein CC-Disengage. Gragas kann aber über W-Reduktion, Passive und Bewegungstempo Trades neutralisieren. Die Lane ist oft leichter zu halten als wirklich zu töten.',
'Seine Defensive und Heilung verlangen mehrere Kontakte. PTA wird vor 6 oft durch E unterbrochen. Conqueror für den langen Fight nach E/W.',
'Olaf im langen Fight nach Q-Miss. Gragas-Q-Poke und Passive nicht ohne Gegenwert tauschen. Q für Farm/Druck nutzen.',
'E verfehlt oder für Wave verbraucht: vorlaufen. Seine W-Reduktion auslaufen lassen. Nicht für drei Autos den nächsten E-Reset tanken.',
'R verhindert E/R-Verdrängung bei rechtzeitigem Einsatz. Bewegungsrune, W und Heilung bleiben. Ohne R kann er wieder kurze Trades kontrollieren.',
'E-Body-Slam, W-Reduktion, Passive-Heal, R-Disengage.',
'E verfehlt plus W beendet. Nach defensiver R ein weiteres Fenster bei eigenem R-/Ghost-Vorteil.',
'R schon auf große Distanz nutzen. W-Defensive und Phase des E-Cooldowns ignorieren. Schadenloser Dauerpoke in seine Passive.',
'Eigene Seite für längeren Chase, eingehende Q-Waves ausdünnen. Hydra ermöglicht später Crash/Reset. Cheater nur, wenn Q/E die Wave nicht festhalten.',
'Q trifft, kleinen Trade anbieten, E/W provozieren. Nach Defensive erneut Q–Auto–W–Auto–E. R beim verbindlichen Kontakt, um den Disengage zu verhindern.',
'Ravenous Hydra für Sustain und Push, danach Maw gegen AP-Burst. Experimental Hexplate bei sicherer Lane, wenn häufiger R-Zugriff wichtiger ist.',
'Executioner’s erst, wenn seine Heilung ein konkretes Killfenster verhindert. Force of Nature gegen mehrere AP-Dauerquellen. Sterak’s nicht mit Maw kombinieren.',
'1 Item: Hydra macht Lane stabil, aber nicht jeden Gragas killbar. 2 Items: mit R leichter Druck. 3 Items: Gragas kann Wellen klären und Teamkämpfe entscheiden. Side-Kill nicht zum einzigen Siegplan machen.',
'Ziehe E und W heraus und starte den langen Trade danach. Spare R für den Moment, in dem sein CC dich wirklich vom Ziel lösen würde. Ein erzwungener Recall und Wavevorteil sind oft der realistische Gewinn.',
'PTA gegen fragilen AP-Gragas ohne zuverlässigen Disengage oder bei klarer Carry-Dive-Comp.');
add('gwen','Gwen','D','Conqueror',"Doran’s Blade + Health Potion",'Ghost + Ignite','Frühe Boots für Q/R-Dodges. Mercury’s bei weiterer AP/CC-Belastung.',
'Olaf kann früh Raum nehmen, Gwen skaliert im direkten Duell stark. Gestacktes Q, Mist-Resistenzen und R-Heilung bestrafen einen geraden All-in.',
'Gwen bleibt lange in Nahkampfreichweite, wenn sie kämpfen will. Conqueror passt zu mehreren Q/E-Zyklen und ihrer Heilung. PTA beendet einen gleichwertigen Fight meist nicht früh genug.',
'Olaf mit Q-Resets. Gwen-E-Start respektieren und kein langes Duell mit Minionnachteil. Gestacktes Q nicht mittig treffen lassen.',
'Nach Q-Verbrauch oder E ohne Angriffs-Reset handeln. Seitlich um Q-Zentrum bewegen. W-Rand beachten: Q von außerhalb Mist ist keine sichere Kontaktquelle.',
'Gwen-R verleiht großen Schadens-/Heilspike. Ragnarok negiert Slow, nicht die Nadeln. Ignite während Heilphase und quer zu R-Linie laufen.',
'Vierfach-Q, E-Autos, W-Mist/Resistenzen, mehrere R-Würfe.',
'Q ungestackt/verbraucht, W vorbei. R vollständig verbraucht bietet besseren Re-engage als nur der erste Wurf.',
'Von außerhalb W auf Q-Treffer vertrauen. Alle Nadeln tanken. MR als Schutz gegen Q-True-Damage interpretieren.',
'Früh Slowpush crashen und Bounce zum Zonen. Nicht freies Farmen bis zwei Items zulassen. Bei verlorener Prio dünnen, statt auf großer Wave zu duellieren.',
'Q treffen, seitlich an Gwen heran. Auto–W–Auto–E, bei ihrem Q quer gehen. Während R-Folge weiter dodgen, nicht für einen zusätzlichen Auto im Zentrum bleiben.',
'Ravenous Hydra, danach Maw of Malmortius gegen ihren magischen Anteil. Stridebreaker, wenn E-Spacing das größere Problem ist.',
'Executioner’s ohne Ignite oder bei längeren Heilduellen. Sterak’s als Alternative zu Maw. Force of Nature bei AP-Comp. Kein früher Crit-Glascannon-Statcheck.',
'1 Item: Olaf mit sauberem Dodging konkurrenzfähig. 2 Items: Gwens Nashor/Riftmaker-artiger Dauerschaden gewinnt stark. 3 Items: Side eher Gwen bei Gleichstand. Frühe Prio für Türme und Teamdruck nutzen.',
'Nimm früh Raum und kämpfe nach ihrem Q. Weiche Zentrum und Nadeln aus, auch während Ragnarok. Vermeide den gleichwertigen Drei-Item-Statcheck ohne klaren Ressourcen- oder Cooldownvorteil.',
'PTA bei vier fragilen Zielen und wenn ein anderer Verbündeter Gwen übernimmt. Ghost + Flash, wenn Ignite den fehlenden Flash gegen die übrige Comp nicht rechtfertigt.');
add('heimerdinger','Heimerdinger','B','PTA',"Doran’s Shield + Health Potion",'Flash + Ghost','Boots früh zum E/W-Ausweichen. Mercury’s bei magischem Burst und weiterem CC.',
'Olaf kann nach 6 durch den Stun laufen und Heimer ohne Dash erreichen. Ein intaktes Turret-Nest verursacht trotzdem mehr Schaden, als Ragnarok auffängt.',
'Nach Turret-Abbau und verfehltem E zählt ein schneller Kill auf Heimer. PTA passt zu drei erreichbaren Autos. Ein langer Fight im Nest ist kein sinnvolles Conqueror-Ziel.',
'Heimer kontrolliert vorbereitetes Terrain. Olaf gewinnt nur Kontakt abseits mehrerer Türme. Q für Farm und Turret-Chip, keinen Bush ungeprüft betreten.',
'Türme mit Q und sicheren Autos abbauen. E-Miss nur nutzen, wenn nicht drei aktive Türme plus Wave auf dich feuern. Jungler über gefährliche Gankwinkel informieren.',
'R schützt vor Stun/Slow, nicht Turret-Laser oder RQ. Nach E und dünnem Nest anlaufen. Bei aufgestelltem RQ lieber neu positionieren.',
'Q-Turret-Netz, E-Granate, W-Raketen, RQ/RE.',
'E verfehlt, Türme/Charges reduziert. R gerade defensiv verbraucht und Lane weit weg vom Turm.',
'Einen Gank im vollen Nest erzwingen. R mit Schadensimmunität verwechseln. Heimer fokussieren, während drei Türme freie Laser erhalten.',
'Push annehmen und kontrolliert ausdünnen. Freeze nur ohne Turret-Dauerdruck realistisch. Mit Hydra vollständigen Crash/Recall erzwingen, bevor neues Nest steht.',
'Turrets chippen, E seitlich ausweichen. Q auf Heimer, R beim Kontakt, Auto–W–Auto und PTA. Aus RQ-Schusslinie herauslaufen, falls der schnelle Kill nicht gelingt.',
'Ravenous Hydra zum Nest-/Waveabbau und Sustain. Stridebreaker, wenn Catch wichtiger wird. Zweites Item Maw gegen AP-Burst oder Hexplate bei freiem Zugriff.',
'Force of Nature gegen dauerhaften AP-Schaden. Kein früher Kritlaf, solange das Nest vor Kontakt zu viel HP kostet.',
'1 Item: Hydra vereinfacht Farm und Reset. 2 Items: guter Catch ohne Nest, schlechter Kampf in RQ. 3 Items: Terrain entscheidet mehr als reines Scaling. Er kann Objective-Zonen halten, daher vorher Waves drücken.',
'Baue zuerst die Türme ab und warte auf die Granate. Erst dann mit R auf Heimer gehen. Wenn der Kill nicht schnell fällt, verlasse das Nest und gewinne über einen besseren zweiten Anlauf.',
'Conqueror nur gegen viel zusätzliche Frontline; nicht als Begründung, im Turret-Nest stehen zu bleiben.');
add('illaoi','Illaoi','E','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Boots zum E/Q-Dodging. Steelcaps gegen W/Autos, nicht gegen gesamten Tentakelschaden.',
'Illaoi bestraft genau Olafs Wunsch, stehenzubleiben. Olaf gewinnt nach E-Miss und ohne aktives R-Nest. Ragnarok entfernt weder Geist noch Tentakelschaden.',
'Der erlaubte Fight nach E/R-Abklingen dauert meist mehrere Rotationen. Conqueror unterstützt ihn. PTA rechtfertigt keinen kurzen Burst in Geist plus R.',
'Olaf vor aufgebautem Nest. Tentakel nur bei sicherem Abstand entfernen und Q-Start für Druck nutzen. W-Start-Illaoi an Wandtentakel nicht blind duellieren.',
'E durch Minions blockieren. Nach Miss sofort Platz nehmen. Getroffener Geist: Abstand/Nest verlassen, nicht auf Zwang dagegenhalten.',
'Illaoi-R herauslocken und rauslaufen. Erst nach Ende erneut kämpfen. Olaf-R hilft beim Weglaufen durch Slow, aber nicht gegen den Hauptschaden.',
'E-Geist, W-Sprünge, Tentakelpositionen, R.',
'E verfehlt und wenige Tentakel. R vollständig vorbei. Nach E-Hit existiert meist kein gutes Killfenster ohne großen Vorsprung.',
'In E plus R stehenbleiben. Den Geist als rein visuellen Effekt ignorieren. W-Lifesteal gegen mehrere Tentakel überschätzen.',
'Früh Prio zum Crash und Tentakel entfernen. Ab 6 Wave eigene Seite und dünn halten. Nicht zwischen feindlichem Turm und vollem Nest einfrieren wollen.',
'Hinter Minions E baiten, danach Q–Auto–E. Auto–W–Auto nur außerhalb mehrerer Tentakelschläge. R erzwingen, zurückziehen, nach Ablauf zweite Q-Kette starten.',
'Ravenous Hydra für Sustain/Waveclear, danach Death’s Dance gegen physischen Schaden. Stridebreaker bei Bedarf, R-Zone besser zu verlassen und neu anzusetzen.',
'Executioner’s gegen relevante Tentakelheilung, aber kein Ersatz für Disengage. Sterak’s gegen Burst. Hullbreaker nur bei bereits gewonnenem Side-Zustand.',
'1 Item: E-Miss erlaubt Druck. 2 Items: R-Zone bleibt nicht statcheckbar als Standard. 3 Items: direkte Side sehr bedingt, über Push/Rotation spielen. Ihre Abwesenheit an Objectives nutzen, ohne Turm zu verschenken.',
'Ohne E-Treffer ist Illaoi angreifbar. Mit Geist und R verlässt du den Bereich sofort. Nutze die Pause, heile an der Wave und greife erst nach dem nächsten klaren E-Miss wieder an.',
'PTA gegen vier fragile Gegner, wenn du Illaoi über Waveclear hältst. Nicht wählen, um ihr R-Nest schneller durchzubursten.');
add('irelia','Irelia','C','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps gegen ihre Auto-Uptime.',
'Olaf kann die direkte Nahkampfphase gewinnen, Irelia nutzt Minions für Heilung, Passive und Ausweichen. Mit voller Passive und Reset-Wave kippt derselbe Fight.',
'Mehrere Re-engages, W-Reduktion und Lifesteal verlangen langen Gegenschaden. Conqueror ist zuverlässiger als PTA hinter einer Dash-Kette herzujagen.',
'Olaf gegen ungestackte Passive. Irelia darf nicht ungestört mehrere niedrige Minions Q-en und danach kämpfen. Mit Q Position sichern, nicht in vier Stacks anlaufen.',
'E verfehlt und keine Low-HP-Minions: All-in-Fenster. W abwarten. Eigene Minion-HP als ihre Mobilitätsressource lesen. Patch 26.17 stärkt ihre Q-AD-Skalierung.',
'R verhindert Stun/Slow als Kontrolle, nicht Markierung, Dash-Resets oder R-Schaden. Sie kann Olaf-R über Minions auslaufen lassen.',
'Passive-Stacks, Q-Resetziele, E, W-Reduktion, R-Markierung.',
'E-Miss, W beendet und Q ohne Reset verbraucht. BORK-Komplettierung ist gegnerischer Spike, kein eigener Angriffsbefehl.',
'Mit vier Stacks und mehreren Q-Healzielen kämpfen. R vor ihrer Fluchtkette. W-Reduktion vollständig mit Autos füttern.',
'Früh kontrollierte Prio. Freeze eigene Seite ohne viele niedrige Minions, die ihr perfekte Dashes bieten. Nach gewonnenem Trade vollständig crashen.',
'Q aus Winkel, E sidesteppen. Ihre W abwarten, nach Q-Landung Auto–W–Auto–E. Kurze Qs und so positionieren, dass sie für den nächsten Reset vom Kampf wegmuss.',
'Ravenous Hydra, danach Death’s Dance. Stridebreaker statt Hydra, wenn Dash-Endpunkte erreichbar sind und Slow den Rückweg schließt.',
'Executioner’s gegen Lifesteal, besonders ohne Ignite. Randuin’s nur bei tatsächlichem Crit-Ausbau. Sterak’s gegen Burst. Keine gedankenlose Crit-Antwort auf ihre BORK.',
'1 Item: BORK-Spike verändert HP-Schwellen. 2 Items: Wave und Defensive entscheiden. 3 Items: starke Irelia kann weiter mit Resets gewinnen; Olaf gewinnt eher auf leerer Lane mit R. Kein pauschaler Outscale-Spruch.',
'Schau zuerst auf Passive und Minion-HP. Warte auf E/W und kämpfe auf möglichst leerer Lane. Halte R bis zu einem Kontakt, den sie nicht einfach mit mehreren Q-Resets auflösen kann.',
'PTA, wenn Irelia bereits ohne W/Resets zuverlässig festgehalten wird oder dein Hauptziel eine fragile Backline ist.');
add('jax','Jax','F','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Plated Steelcaps früh. Gemischter Schaden braucht später mehr als Armor.',
'Counter Strike entzieht Olaf Autos und Lifesteal, Q trennt Kontakte, R gewinnt lange Duelle. Ragnarok verhindert den Stun, aber nicht das Ausweichen. Frühe E-Cooldown-Fenster sind entscheidend.',
'PTA wird durch E und Q häufig vor dem dritten Treffer unterbrochen. Q und E können Conqueror aufbauen und der Fight muss nach Counter Strike weitergehen. Kein Vorteil während Auto-Dodge behauptet.',
'Nicht blind E-Start angreifen. Q zum Abstandhalten, E auslaufen lassen, dann mögliche Verlängerung. Passive-gestackten Jax nicht im Minionüberschuss statchecken.',
'Nach E-Ende Druck, falls Q nicht sicher zurück zum Turm führt. E-Schaden von Olaf kann Jax während Dodge treffen. Danach W für tatsächliche Autos aufheben.',
'Olaf-R gegen Stun einsetzen, aber Counter Strike weiterhin aussitzen. Jax-R liefert Resistenzen/Schaden, Q kann R-Uptime brechen. Ein R-Tausch ist noch kein Kill.',
'E-Dodge, Q-Disengage, Passiv-AS, R-Defensive/on-hit.',
'E gerade vorbei und Q offensiv verbraucht. Am besten zusätzlich wenig Passive-Stacks. Gegen E plus Q verfügbar ist ein Q-Treffer allein zu wenig.',
'W-Attacks in Counter Strike verschwenden. Annehmen, R mache Autos treffsicher. E-Cooldown später wie früh behandeln.',
'Wave auf eigener Seite und E-Verbrauch fürs Pushen bestrafen. Crash nach gewonnenem Trade. Nicht ohne R eine große zurücklaufende Wave halten müssen.',
'Q-Poke, bei Jax-E Abstand und eigenes E falls sicher. Nach E-Ende Q–Auto–W–Auto. R bei Stunbedrohung und nur weiterjagen, wenn Q-Fluchtweg kontrolliert ist.',
'Ravenous Hydra für Sustain/neutralen Waveclear, danach Death’s Dance gegen physischen Anteil. Stridebreaker bei realem Catch-Plan, kein garantierter Jax-Counter.',
'Frozen Heart bei mehreren Auto-Angreifern und eigener ausreichender Schadensbasis. MR bei hohem magischem Anteil. Kein früher Kritlaf: Dodge negiert die gekauften Autos.',
'1 Item: frühe E-Fenster bleiben spielbar. 2 Items: Jax wird im wiederholten Duell deutlich besser. 3 Items: offene Side bei Gleichstand vermeiden. Waves bearbeiten und bessere Teamkämpfe suchen.',
'Greife nach Counter Strike an, nicht währenddessen. Halte W für treffende Autos und R für einen kontaktfähigen Kampf. Später ist Waveclear plus Rotation oft besser als der gleichwertige Side-Statcheck.',
'PTA nur wenn Jax nicht dein Ziel ist und die übrige Comp kurze Carry-Kills erlaubt. Die Lane wird dadurch nicht leichter.');
add('jayce','Jayce','B','PTA',"Doran’s Shield + Health Potion",'Flash + Ghost','Plated Steelcaps gegen Autos. Frühe Boots zum Shock-Blast-Dodging.',
'Jayce kann vor 6 starke Poke-/Disengage-Trades spielen. Mit Ragnarok verliert Hammer-E den Stoppeffekt und Olaf kann ihn auf langer Lane töten. Gate-Tempo bleibt eine Fluchtmöglichkeit.',
'Nach verbrauchtem Hammer-E bekommt Olaf mehrere Autos, bevor Jayce erneut Abstand gewinnt. PTA passt zum kurzen Kontaktfenster.',
'Jayce hat Reichweitenkontrolle, Olaf gewinnt erreichbaren langen Kontakt. Q für Drohung/Farm, Bush-Deckung nutzen, nicht für jedes CS zwei Autos nehmen.',
'Hammer-E und Gate beobachten. Nach E-Verbrauch mit Q nachsetzen. Sein R ist ab Level 1 verfügbar: nicht wie klassischen Level-6-Ultgegner behandeln.',
'Olaf bekommt echten R-Spike, Jayce keinen neuen Ultimate-Button. Knockback verhindern und Tempo für Gate aufheben. Poke vor Kontakt bleibt gefährlich.',
'Cannon-Q+E, Hammer-E, Cannon-W-Autofolge, Formwechsel.',
'Hammer-E verbraucht und Gate bereits benutzt. Q-Poke-Miss senkt den Schaden vor dem Anlauf.',
'Mit halber HP in seine komplette Burstrotation. R außerhalb Chase-Reichweite. Frühe Formwechsel-Cooldowns ignorieren.',
'Push annehmen, Wave dünnen und eigene Seite. Mit HP-Vorteil Slowpush crashen, damit Poke nicht unter eigenem Turm endlos bleibt.',
'Shock Blast dodgen, Q treffen, Hammer-E erzwingen. Zweite Q und R bei Kontakt, Auto–W–Auto für PTA. Ghost für Gate-Rückzug nutzen.',
'Stridebreaker für Kontakt, danach Death’s Dance gegen AD-Burst. Ravenous Hydra statt Stride, wenn Lane-Sustain den Zugang erst ermöglicht.',
'Sterak’s gegen vollständige Combo. Fiendhunter Bolts nach AD-Core nur bei Vorsprung und sicherem Zugriff. Kein Crit-Item statt notwendiger früher Defensive.',
'1 Item: Olaf-R kann Lane drehen, Jayce-Poke bleibt stark. 2 Items: gute Catch-Situation favorisiert Olaf. 3 Items: Jayce hat starke Fernbelagerung, direkte Side hängt an Tempo und HP vor Kontakt.',
'Erhalte HP bis zum echten Anlauf. Nach Hammer-E und Gate öffnet sich die Lane. Ab 6 nutze R gegen Knockback und zwinge einen kurzen, zusammenhängenden Auto-Fight.',
'Conqueror, wenn Jayce defensiv baut und du im Gesamtspiel lange Frontline-Duelle erwartest.');
add('ksante',"K’Sante",'B','Conqueror',"Doran’s Blade + Health Potion",'Flash + Ghost','Frühe Boots zum Q/W-Ausweichen. Steelcaps bei vielen Autos.',
'Olafs E und R helfen gegen Tankwerte und CC. K’Sante kann mit W, Shields und Dashes Zeit gewinnen und mit All Out gefährlich zurückkämpfen. Gute Lane heißt nicht garantierter Dive.',
'Shield- und W-Phasen plus hohe effektive HP erfordern mehrere E-Zyklen. Conqueror statt eines kurzen Dreiertrades gegen seine Defensive.',
'Olaf im langen Kontakt, K’Sante im kurzen Q–Auto. Q treffen und seine nächste Q seitlich vermeiden. Keine freien Passiv-Autos für einzelne CS.',
'Nach Q3 und W-Verbrauch Druck. Nicht in den W-Dash laufen. E zu Minions kann den Chase beenden, deshalb Fluchtrichtung lesen.',
'R verhindert Verdrängung bei rechtzeitigem Einsatz, aber All-Out-Schaden bleibt gefährlich. Mit R-Transformation kann sein W erneut bereit sein: nie einfach einen alten W-Cooldown weiterzählen.',
'Q3, W-Defensive/Dash, E-Schild, R und All-Out-W.',
'W und E verbraucht, keine verfügbare R-Resetmöglichkeit. Q3 verfehlt öffnet vor 6 eine kurze Kontaktphase.',
'An Turm/Wand ohne R stehen. W-Reset nach R vergessen. CC-Immunität mit Immunität gegen All-Out-Schaden verwechseln.',
'Kontrollierter Slowpush/Crash, danach eigene Seite für längere Trades. Keine große gegnerische Wave vor dem Turm tanken, während sein All-in bereit ist.',
'Q treffen, Q3 sidesteppen, W abwarten. Auto–W–Auto–E nach Defensive. Bei All Out neu positionieren und den zweiten W-Dash vermeiden, dann weiterkämpfen.',
'Ravenous Hydra, danach Black Cleaver gegen Armor. Bei AD-Comp Death’s Dance vor zusätzlicher Penetration, wenn Überleben der Engstelle entscheidend ist.',
'Sterak’s gegen All-Out-Burst. BORK nur bei HP-lastigem Build und genug Uptime. Hullbreaker, wenn er dauerhaft gruppiert und du sicher Türme nehmen kannst.',
'1 Item: Olaf kann Tankform gut unter Druck setzen. 2 Items: W/All-Out-Ausführung entscheidet. 3 Items: weiter spielbar mit Armorantwort, aber sein Team-Peel skaliert. Keine lineare „Tank = freier Kill“-Annahme.',
'Verlängere nach W und halte Abstand zu gefährlichen Wänden. Mit All Out beginnt eine neue Cooldown-Situation. Nutze R für Kontrolle und bewege dich trotzdem aus seinem hohen Schaden.',
'PTA, wenn K’Sante nur gehalten wird und dein Team Carry-Zugriff vorbereitet. Für tatsächliches Durchkämpfen Conqueror.',
'Mittlere Unsicherheit: K’Sante hat mehrere Kit-Revisionen. Keine sekundengenauen W-/R-Zahlen verwendet. Tier besonders ausführungssensitiv.');
add('kayle','Kayle','D','PTA',"Doran’s Blade + Health Potion",'Flash + Ghost','Boots früh zum Kontakt. Mercury’s nur gegen relevante AP/CC-Comp.',
'Olaf kann frühe Farm und Lane-Länge diktieren. Kayles Range, R-Invulnerability und spätere DPS machen Gleichstand zum schlechten Ergebnis. Frühe Lane günstiger als Gesamtspiel.',
'Nach Q/W-Verbrauch ist ein kurzes Killfenster vor sicherem Rückzug relevant. PTA hilft, bevor sie ihren nächsten Abstandszugang bekommt. Späteres Invulnerability-Fenster muss trotzdem ausgesessen werden.',
'Olaf mit Q-Resets, aber Kayle mit gestackter Passive und Kampfrune nicht blind anfassen. Erst Stacks/Wave prüfen, dann zonen.',
'Wavezugang bestrafen, nach Q-Miss anlaufen. W-Tempo auslösen und zweite Q/Ghost dafür behalten. Nicht per Dauerpush sichere XP schenken.',
'Kayle wird ranged und hat R als Schadensschutz. R herauslocken, sicher folgen und E/Finisher für danach halten. Olafs R nicht am Turm ins Leere laufen lassen.',
'Q-Slow/Resistenzsenkung, W-Tempo, Passiv-Stacks, R-Invulnerability.',
'R verbraucht plus W fehlt. Vor 6 Q-Miss bei langer Lane. Ab 11 Range/DPS höher gewichten als alte HP-Schwellen.',
'Volles Damagepaket in R. Level-1-Kayle pauschal schwach nennen. Bei Gleichstand bis drei Items nur farmen.',
'Früh Slowpush crashen, Bounce einfrieren und XP/Gold bedrohen. Freeze lösen für sicheren Turm-/Objective-Gewinn. Hydra kann Freeze-Kontrolle erschweren.',
'Q treffen, W-Tempo verfolgen, Auto–W–Auto–E. Kayle-R erzwingen, aus maximaler Gegen-DPS repositionieren und nach Ende nächste Q/Autos. Nicht gedankenlos unter Turm warten.',
'Stridebreaker, danach Experimental Hexplate für wiederholte Catch-Fenster. Ravenous Hydra bei Wave-/Sustainbedarf, aber ohne Slow etwas schwerer nachzusetzen.',
'Maw bei AP-Kayle/weiterem AP. Bei Führung Fiendhunter Bolts nach AD-Core, wenn R bereits gezogen ist. Kein Burst-Ausbau als Antwort auf aktive Invulnerability.',
'1 Item: frühe Lane noch ausnutzbar. 2 Items: R und eigener Kontakt entscheiden, Kayle wird gefährlicher. 3 Items/hohe Level: offene Side eher Kayle. Früh Türme nehmen und sie zu Antworten zwingen.',
'Nutze die ersten Waves, um einen langen Rückweg für Kayle zu schaffen. Ziehe R und greife im nächsten Fenster wieder an. Gleichstand bis ins späte Spiel ist für Olaf meist kein gewonnener Plan.',
'Conqueror, wenn Kayle defensiv baut und du lange Frontline-Kämpfe statt kurzer Kayle-Catches spielen musst.');
}
