import {add} from './warwick-data.mjs';
add('kayle','C','A','E','PTA','ranged',
'Warwick kann frühe Farm bestreiten. Ab Range und besonders mit mehreren Items erschweren Kiting und Unverwundbarkeit den Abschluss.',
'Nicht blind ihre gestapelte Passive traden. Nahkontakt mit Q und eigener Wave nutzen, wenn sie für CS herantritt.',
'Nach Q-Verfehlen zonen. W-Lauftempo ermöglicht ihr Rückzug; kurze PTA-Trades zuverlässiger als Verfolgung bis zum Turm.',
'Unverwundbarkeit baiten und eigene R-Heilung nicht darin verbrauchen. Nach ihrer R mit Fear/R abschließen, solange Kontakt bleibt.',
'Q-Slow/Resistenzsenkung, W-Tempo, R-Unverwundbarkeit, spätere Range.',
'R verbraucht, Q fehlt und langer Rückweg. Vor 6 nach W-Verbrauch Farmdruck.',
'R-Schaden und Heilung in Unverwundbarkeit planen; nach frühem Vorteil nur gleichwertig farmen.',
'Früher Crash für Bounce und Freeze. Bei unmöglichem Freeze Push für Plates/Objective; ihr keine freie Endlosfarm schenken.',
'Auto–Q–Auto, E bei Gegenwehr. Fear für Kontakt, R erst nach Unverwundbarkeit; bei Flucht ohne Anschluss Ressourcen sparen.',
'1: frühes Killfenster bleibt. 2: Range und AS erschweren Zugang. 3: gleichwertig deutlich Kayle-favored; Catch mit Team statt offener Verfolgung.');
add('kennen','D','D','D','PTA','aprange',
'Fernkampf, Stun und E-Flucht lassen Warwick wenig sichere Heil-Autos. Ein verfehltes E/R-Fenster kann trotzdem einen Kill ermöglichen.',
'Kennen bestimmt Abstand. Nicht für einen Q-Trade mehrere Autos und Stacks nehmen.',
'Nach E-Verbrauch anlaufen, Marks mitzählen. Eigene E vor Stun-Schaden; Q-Heal rechtzeitig, bevor Kontrolle den Zugriff blockiert.',
'Seine R kann nach deinem R-Aufprall stunnen. Marks und E vorher erzwingen, sonst den sicheren Farm-/Resetweg wählen.',
'Drei Passive-Marks, E-Flucht, W-Procs und R-Fläche.',
'E fehlt, wenige Marks auf Warwick; nach R-Ende neu angreifen.',
'R in vorbereiteten dritten Stun-Mark; Low-HP-Bait ohne Zielkontakt; Magieresistenz für unnötigen Angriffsschaden aufschieben.',
'Auf eigener Seite ausdünnen und Gankwinkel halten. Nach Kennen-Roam pushen und pingen, nicht blind durch River folgen.',
'E-Verbrauch abwarten, Auto–Q–Auto im Zugriff. E gegen Burst, Fear und R nach Stunzyklus; kein Chase ohne Sicht.',
'1: MR/Stride können Zugriff verbessern. 2: du wirst haltbarer, er bleibt mobil. 3: sein Teamfight bleibt stark; einzelne Flanken statt Frontdurchlauf.');
add('kled','C','B','C','Lethal Tempo','ad',
'E-Reduktion kann Kleds W-Burst auffangen. Dismount ist aber kein Kill: Courage und Remount erzeugen eine zweite HP-Phase.',
'Q ausweichen, direkten Kontakt nur ohne große Wave suchen. Mit Q-Tether nicht im schlechten Abstand kleben bleiben.',
'Seine W-Autos zuerst provozieren, danach kämpfen. Dismount-Fenster mit Mana für Q und E vorbereiten; Courage beobachten.',
'Kled-R ist kein guter Zeitpunkt für Fear/Unterdrückung. Nach Ankunft und W-Phase handeln, eigene R zum sicheren Abschluss der Dismount-Phase.',
'W-Autoburst, Q-Tether, E-Nachsetzen und Remount.',
'W verbraucht, wenig Courage nach Dismount und keine sichere Minion-/Auto-Serie für Remount.',
'Dismount als Tod zählen; alle Heil-/Kontrollfähigkeiten davor verschwenden; fälschlich alte Q-Antiheal-Regeln anwenden.',
'Eigene Seite mit überschaubarer Wave. Nach Rückzug vollständig crashen, damit er nicht gratis Courage an vielen Zielen sammelt.',
'E gegen W-Autos, Auto–Q–Autos. Nach Dismount Fear für sichere Autos und R vor Remount, falls der Schaden wirklich reicht.',
'1: Duell gut nach W-Verbrauch. 2: Armor verbessert Burstüberleben. 3: Remount/Teamrotationen bleiben entscheidend, kein kostenloser Statcheck.');
add('ksante','D','C','D','Lethal Tempo','ad',
'Warwick kann Tankphasen länger bekämpfen, K’Sante aber mit Kontrolle und All Out den Kampf räumlich und zeitlich bestimmen.',
'Q seitlich ausweichen; Auto–Q im Kontakt günstig, nicht an ungünstiger Wand verlängern.',
'W-Reduktion abwarten, Q3 erkennen. Gehaltenes Q ist ein Timing-Werkzeug gegen Verschiebung, keine Garantie gegen jede Kontrollkette.',
'Nicht durch Wand in Isolation ziehen lassen. R erst nach W und ohne sofortige Kontrollantwort, E für seinen tatsächlichen All-Out-Schaden.',
'Q3, W-Reduktion, E-Schild und R-Isolation.',
'W und Q3 verbraucht; sein E-Rückweg fehlt. All Out nicht ungeprüft als reine Verwundbarkeit sehen.',
'R in W-Reduktion; an Turmwand kämpfen; Fear und R in derselben gegnerischen Immunitätsphase verschwenden.',
'Lane mittig oder eigene Seite, mit Abstand zu isolierenden Wänden. Push nur mit Sicht und nachvollziehbarem Recall.',
'Q-Tap zwischen seinen Qs, W abwarten. Eigene E während seines Commits, Fear nach Q3/W, R zur Heilung bei sicherem Kanal.',
'1: längere Kontakte möglich. 2: Kontrollzyklen und All Out erschweren Kills. 3: Side häufig neutralisierbar, K’Santes Teamkontrolle bleibt wertvoll.');
add('malphite','B','B','C','Lethal Tempo','ap',
'Warwicks magischer Q-/Passiveschaden verhindert, dass reine Armor alles löst. Malphites AS-Slow und Disengage begrenzen den Dauerkampf.',
'Kurzes Q gegen seinen Schild bringt wenig; Schild entfernen und dann erst ernsthaft traden. Warwick gewinnt festen Kontakt.',
'E-AS-Slow abwarten, Q-Heilung gezielt einsetzen. Mana nicht in wiederkehrende Passivschilde investieren, wenn er jeden Trade verweigert.',
'R kann Malphite zur Flucht oder zum Counter-Engage nutzen. Seine R kann deinen laufenden Kanal unterbrechen; erst Zugriff bestätigen.',
'E-AS-Slow, Q-Temposwing, Passivschild und R.',
'E und Q verbraucht; ohne R ist der nächste lange Kontakt schwerer zu vermeiden.',
'Nur physischen Schaden gegen Armor stapeln; AS-Slow mit vermeintlich garantiertem Lifesteal ignorieren.',
'Früh halten und wiederholt Schild entfernen. Später komplette Crashes für Mapdruck, wenn er sich nur noch unter Turm zurückzieht.',
'Schild mit Auto entfernen, nach E Auto–Q–Autos. Fear beim Rückzug, R nach seiner R oder mit Team, das Kanalunterbrechung verhindert.',
'1: magischer Anteil hält Duell spielbar. 2: HP/MR je Build; BotRK nicht allein gegen Armor kaufen. 3: er kann die Side halten und besser initiieren.');
add('mordekaiser','B','A','C','Lethal Tempo','ap',
'Warwick hat frühe Heil-/Auto-Fenster und kann isolierte Qs umgehen. Death Realm plus passive DPS verhindert aber ein bedingungsloses Dauerduell.',
'Q seitlich umgehen und mit eigener Wave handeln. Warwick im festen Kontakt gut, isolierte Q nicht mehrfach schenken.',
'W-Schild erst verbrauchen lassen und E ausweichen. Eigene E dämpft Q/Passive; nicht bei Manaende weiterkämpfen.',
'Im Realm bleiben deine Fähigkeiten nutzbar, aber seine gestohlenen Werte zählen. Eigene R als rechtzeitige Heilung nach seinem Schild, nicht als Realm-Cleanse.',
'Isolierte Q, W-Schild, E-Zugriff und R-Statdiebstahl.',
'W verbraucht, E verfehlt; nach Realm-Ende kann ein erneuter Angriff deutlich besser sein.',
'R-Heilung in vollen Schild stecken; QSS als sicheren Ausstieg aus seiner R einplanen; E vor dem eigentlichen Schadensfenster verlieren.',
'Früh kontrolliert zonen; seine Q-Waveclear nicht in schlechten Push übersetzen. Vor 6 gute Resets sichern.',
'Q ausweichen, Auto–Q–Autos, E gegen Passive. W auslaufen lassen, Fear für Abstand oder Anschluss; R heilen bevor Q-Burst tödlich ist.',
'1: BotRK/Q können Druck halten. 2: MR verhindert reine Damage-Races. 3: ausgeglichen bis buildabhängig, Realm mit Item-/Levelnachteil meiden.');
add('nasus','C','A','E','Lethal Tempo','hp',
'Früher CS-Druck ist stark. Wither nimmt Warwick aber Angriffstempo und damit Heil-Autos; später fehlt Olafs CC-Immunität als Antwort.',
'Warwick kann Q-Last-Hits bestrafen. Keine unnötige Minionaggro durch dauerhaftes Chase.',
'Nach Wither-Ende ernsthaft handeln. E gegen verstärkte Qs, Q-Mana für echte Trades statt jeden Farm-Last-Hit sparen.',
'Nasus-R früh provozieren, mit Fear Abstand gewinnen und nach Ablauf zurück. In Wither plus R nicht auf Low-HP-Autos vertrauen.',
'W-Wither inklusive AS-Slow, R-Q-Takt und Stackstand.',
'W verbraucht und R nicht aktiv; vor 6 Q auf Minion als kurzes Tradefenster.',
'Dauerpush nur zum vermeintlichen Stackdeny; mit vollem Wither weiterlaufen; nach vielen freien Stacks alten Early-Vorteil annehmen.',
'Vollständiger früher Crash, Bounce und Freeze solange du zonen kannst. Tiamat verschieben, wenn Freeze dein stärkstes Werkzeug ist.',
'Q-Last-Hit mit Auto–Q beantworten, E gegen Antwort. Bei R Fear für Rückzug; erst nach R/Wither-Pause erneut lang angreifen.',
'1: frühe Führung zählt stark. 2: Wither und Stacks können drehen. 3: gleiche Ressourcen oft Nasus-favored; Side gemeinsam lösen.');
add('olaf','C','B','D','Lethal Tempo','ad',
'Warwick besitzt vor 6 E/Fear und Barrier als Duellwerkzeuge. Olaf-R nimmt später Fear und Suppression, wodurch Warwick Kontrolle für Heilzeit verliert.',
'Kein pauschaler Sieg gegen aufhebbare Äxte. Warwick bei dauerhaftem Kontakt mit Q gut, lange Axtbahn und Ignite verändern das Duell.',
'E vor Olafs W-Autofenster und Fear zum Unterbrechen seiner Uptime. Äxte nicht durch geradliniges Zurücklaufen erneut anbieten.',
'Bei aktiver Ragnarok keine R als sichere Heilung einplanen. E reduziert physischen Schaden, nicht Olaf-E; Abstand schaffen bevor er Kontakt erzwingt.',
'Q-Slow/Armor-Shred, W-Schild, E-True-Damage, R-CC-Immunität.',
'R fehlt oder ist ausgelaufen, W verbraucht und eine Axt verfehlt. Vor 6 nach schlechtem Q-Wurf nachsetzen.',
'R in Ragnarok, E gegen True-Damage-Execute aufsparen, mit Barrier automatisch jedes Low-HP-Duell erwarten.',
'Eigene Seite, damit Olaf keinen langen Axt-Chase bekommt. Früh Druck in Crash/Recall umsetzen, später R-Timer für Farmwege nutzen.',
'Auto–Q–Autos mit E gegen W-Burst. Vor 6 Fear zum Anschluss; ab 6 beim R-Commit rechtzeitig trennen und erst nach Ragnarok selbst unterdrücken.',
'1: vor allem Ultis entscheiden. 2: Olaf wird bei R-Kontakt schwer kontrollierbar. 3: eher Olaf im direkten All-in, Warwick kann andere Ziele fangen.');
add('ornn','C','B','C','Lethal Tempo','hp',
'Warwick kann Ornn lange an der Wave bekämpfen. W-Unaufhaltsamkeit und späterer Teamnutzen begrenzen, wie viel aus Lane-Druck wird.',
'Q ausweichen, Auto–Q bei Kontakt. Seine W-Antwort nicht mit vollem Rückzug in Brittle-Auto verschenken.',
'Nach W länger handeln. Eigene E gegen Q/W/Auto; Fear nicht während seiner Unaufhaltsamkeit verbrauchen.',
'R nach W und ohne freie Gegenkontrolle. Ornn-R kann deinen laufenden Kanal unterbrechen; zwischen den R-Phasen Abstand/Timing beachten.',
'W/Brittle, Q-Säule plus E, R-Kontrollkette.',
'W und E verbraucht; ohne R kann er den längeren zweiten Kontakt schlechter unterbrechen.',
'Fear/R in W, an Q-Säule stehenbleiben, gute Lane mit garantiert besserem Gesamtspiel verwechseln.',
'Früh eigene Hälfte für längere Trades. Wenn Ornn nur neutralisiert, ganz crashen und Objectives vorbereiten statt Mana unter Turm ausgeben.',
'W abwarten, Auto–Q–Autos; E beim nächsten Burst. Fear nach E, R mit freiem Kanal als Heilung.',
'1: erreichbarer Tank mit gutem Q-Wert. 2: Mischresistenzen zähmen den Killdruck. 3: Ornn-Upgrades stärken sein Team, reine Side-Farm reicht selten.');
add('pantheon','C','C','B','PTA','ad',
'Warwick kann Pantheons Burst überleben und zurückheilen. Frontales E verhindert jedoch guten Q-/R-Schaden und damit Heilung.',
'Q-Spitzen respektieren, keine wiederholten Treffer für einzelnen CS. Nach Q-Verbrauch ist der Nahkontakt besser.',
'E vor W-Stun vorbereiten. Sein E abwarten oder mit gehaltenem Q die Seite wechseln, falls sicher; nicht hinterher bis unter den Turm.',
'Seine R erzeugt Mapdruck, deine R Duellkontrolle. Erst E-Verteidigung verbrauchen lassen, dann unterdrücken.',
'Empowered W, E-Frontschutz, Q-Execute-Bonus.',
'E beendet, verstärktes W verbraucht und Q nicht sofort verfügbar.',
'R frontal in E; bei niedrigen HP Q-Execute unterschätzen; fehlenden Pantheon nicht pingen.',
'Wave auf eigener Seite empfangen. Seine Roams mit vollständigem Crash und Plates bestrafen, sofern Jungle-Sicht passt.',
'E vor Stun, Auto–Q nach Burst. Bei gegnerischem E warten oder sicher hinter ihn, danach Fear und R als zweite Rotation.',
'1: Burst mit E überleben. 2: Warwick gewinnt längere Kontakte häufig. 3: Duelldruck gut, Pantheon kann über Catch und Map schneller wirken.');
add('poppy','C','C','C','Lethal Tempo','ad',
'Poppys W blockiert Dash-Zugriff und ihr E bestraft schlechte Position. Außerhalb ihrer defensiven Fenster kann Warwick sustainen.',
'Q-Zone zweimaligen Schaden vermeiden, Schild-Buckler nicht unter Wandeinfluss contesten.',
'Q-Dash nicht in aktive W planen. Nach W-Ende gehen und E vor Wandstun drücken, wenn Ausweichen nicht mehr möglich ist.',
'R-Flug und Kanal nicht gleichsetzen: die eigene R macht Warwick nicht dauerhaft CC-immun. Poppys R/E nach Aufprall können das Heilen stören.',
'W-Anti-Dash, E-Wandstun, Q-Zone und R-Disengage.',
'W und E verbraucht; nach ihrer R fehlt ein weiterer Kampfabbruch.',
'Q in W, an Wänden traden, komplette Suppression trotz bereitem gegnerischem CC garantieren.',
'In offener Lanemitte auf eigener Hälfte. Buckler-Zonen nicht mit schlechten Wave-Zügen erzwingen.',
'Q-Zone verlassen, Auto-Trade bis W vorbei. Eigene Q danach, E gegen Burst, Fear im offenen Raum und R nach Disengage-CD.',
'1: HP/Armor erschweren Solokill. 2: sustainbarer Kontakt spielbar. 3: beide können Side halten; Poppys Peeling kann deinen Teamzugriff verhindern.');
add('quinn','D','D','D','PTA','ranged',
'Blind/Nearsight und Vault verhindern sichere Auto-Serien. Warwick muss erst Vault ziehen, bevor ein verbindlicher kurzer Kill möglich wird.',
'Quinn hat Reichweitenvorteil; keine langen Wege durch Harrier-Autos laufen.',
'E-Vault erzwingen und wieder herausgehen. Q-Halten bei passendem Kontakt kann Bewegung folgen; nicht als Fernkampf-Gapclose missverstehen.',
'Eigene R nach Vault und auf Sicht. Quinn roamt schneller; ihre Abwesenheit pingen und Crash/Plates nehmen statt blind folgen.',
'E-Vault, Q-Nearsight, Harrier-Procs und Roamtempo.',
'E verbraucht und Q verfehlt; ohne diese beiden wird R auf kurze Distanz zuverlässiger.',
'In frisches Vault investieren; Blood Hunt als sicheren permanenten Kampf-Speed ansehen; blind in Nebel springen.',
'Eigene Seite halten, bei Roam vollständig crashen. Kein unnötiger Freeze, wenn sie damit kostenlos anderswo gewinnt.',
'Q ausweichen, Vault baiten. Zweiter Anlauf mit E gegen Autos, Auto–Q–Auto für PTA; R erst nach Abstandswerkzeug.',
'1: Stride/Armor helfen beim Zugriff. 2: Kiting bleibt wichtiger als Duellwerte. 3: Flanken oder Team-Catch, kein verlässlicher freier Chase.');
add('renekton','C','C','B','Lethal Tempo','ad',
'Warwick kann nach Renektons erster Rotation zurückkämpfen. Fury-W und der Schildbruch bestrafen falsch getimte Barrier.',
'Q-Poke nicht mehrfach gratis nehmen. Längerer Kontakt nach Q günstig, solange Fury nicht schon hoch ist.',
'E vor W-Stun, Barrier nicht direkt in verstärktes W stellen. Nach zweitem Dash und Q sein Rückzugsfenster bestrafen.',
'R-HP und Fury verlängern seine starke Phase. Eigene R nach W-Stun und mit genug HP zum Heilen, nicht gegen komplette bereite Rotation.',
'Fury, empowered W-Schildbruch, Q-Heilung, zweites E und R-HP.',
'W und beide E verbraucht, wenig Fury. Nach Q kann ein zweiter Q-Zyklus von Warwick den Kampf drehen.',
'Barrier von empowered W entfernen lassen; vor E/E-Verbrauch alle Mobilität investieren; Burst ohne E tanken.',
'Eigene Seite und Fury auf Minions beobachten. Nach seinem Q-Push ausdünnen und auf Rückzugspfad traden.',
'E vor W, nach Stun Auto–Q–Autos. Barrier nach Schildbruchfenster, Fear nach zweitem E, R für den zweiten Heilzyklus.',
'1: Fury-/Cooldown-Duell. 2: Warwick wird im langen Kontakt besser. 3: Renekton kann Team-Burst liefern, Side bei gleichen Ressourcen häufig spielbar.');
add('riven','B','B','C','Lethal Tempo','ad',
'Warwick kann Rivens kurze physische Trades mit E und Heilung beantworten. Ihre Mobilität erlaubt Rückzug, R2 bedroht zu späte Heilversuche.',
'Q-Kette respektieren und nach Q3 länger handeln. Nicht gegen größere Wave alle drei Qs nehmen.',
'E vor ihrer Combo, Q für E-/Q-Rückzug behalten. Nach W und Q3 ist dein zusammenhängendes Auto-Fenster.',
'R2 mit rechtzeitiger Barrier/Heilung beantworten. Eigene R nach Stun/Knock-up-Zyklus einsetzen, sonst droht Kanalabbruch.',
'Q3, W-Stun, E-Schild, R2-Execute.',
'Q-Kette und E verbraucht; ohne W ist ein kurzer R-Kanal besser abzusichern.',
'Barrier erst nach R2 planen; Q in frischen Schild drücken und gleiche Heilung erwarten; ihr über Wand ohne Sicht folgen.',
'Eigene Hälfte und lange Rückzugsbahn. Nach gewonnenem Trade vollständig crashen; nicht ohne Mana vor ihrem Turm warten.',
'E gegen Q/W, Auto–Q-Halten beim Rückzug. E-Fear nach ihrer Q3, weiter autos; R vor R2-Todesgrenze und nach Kontrolle.',
'1: Warwick kann häufig Nahkontakt gewinnen. 2: Armor stabilisiert. 3: Riven kann Zugang und Burst besser steuern; kein bedingungsloser Side-Sieg.');
add('rumble','D','D','C','PTA','ap',
'Flamespitter und Harpunen bestrafen den Weg in Q-Reichweite. Warwick gewinnt erst, wenn er E-Reduktion und echte Heil-Autos zusammenbekommt.',
'Nicht durch volle Q-Dauer laufen. HP für den ersten kontrollierten Kontakt behalten.',
'Hitze lesen und nach Q-Ende handeln. Eigene E für Flamespitter/Overheat-Autos, Q-Heal nach dem ersten Schaden.',
'Equalizer quer verlassen; R-Kanal nicht darin beginnen. Overheat bedeutet keine ungefährliche Phase, seine Autos bleiben stark.',
'Q-Dauerschaden, E-Slow/MR-Senkung, Overheat-Autos und R-Fläche.',
'Q vorbei, Harpunen verbraucht und kein günstiger Overheat-Autokampf. Nach R-Ausweichen erneut prüfen.',
'R im Equalizer, E zu früh reaktivieren, mit gesenkter MR Low-HP-Limit testen.',
'Wave aus Q-Fläche ausdünnen und eigene Seite nutzen. Bei zu viel Pushverlust MR/Reset priorisieren.',
'E vor Q-Schaden, Auto–Q–Auto nach Ankunft. Fear für Seitenwechsel aus R, erst außerhalb der Zone mit eigener R heilen.',
'1: MR-Komponente kann mehr Kampfwert haben als sofortiger Vollschaden. 2: längerer Nahkontakt besser. 3: Rumbles Zonen-/Teamfightdruck bleibt stark.');
add('sett','C','C','C','Lethal Tempo','ad',
'Warwick hat guten wiederholten Nahkampf, Setts W-True-Damage und E-Setup können aber das gesamte Low-HP-Fenster beenden.',
'Seine Doppelschläge nicht in größerer Wave traden. Warwick kann verlängern, wenn Q und sichere Autos bereit bleiben.',
'Q-Halten für die W-Mitte zurückhalten, sofern E-Stun es nicht verhindert. E früh gegen Autos, nicht als Antwort auf True Damage.',
'Setts R kann den laufenden Kanal stören. Eigene R nach E/R und W-Schild einsetzen, wenn Heilung tatsächlich Schaden erzeugen kann.',
'E-Stun bei Zielen auf beiden Seiten, Grit/W-Mitte, R-Suppression.',
'W verbraucht und E fehlt. Hoher Grit ohne W-Verbrauch ist kein guter Kill-Commit.',
'W-Mitte tanken, E gegen True Damage planen, eigene R-Heilung in riesigem W-Schild überschätzen.',
'Seitlich von Minions, damit Setts E keinen freien Stun bekommt. Eigene Seite halten und W-Waveclear für Bounce nutzen.',
'E gegen Q-Autos, Auto–Q-Tap. W-Zentrum seitlich/mit gehaltenem Q verlassen; nach Schildende Fear, Autos und R.',
'1: W-Ausweichen entscheidet. 2: Armor/HP verbessern Vorarbeit, nicht W-True-Damage. 3: ähnlich bedingt; Setts Teamfight kann Side-Vorteile überwiegen.');
add('shen','C','C','B','PTA','hp',
'Shens W nimmt Auto-/On-Hit-Fenster, seine verstärkten Qs sind früh stark. Nach diesen Phasen kann Warwick länger heilen und Druck aufbauen.',
'Nicht zwischen Shen und Schwert stehen. Drei verstärkte Autos abwarten, danach Q-Trade.',
'W-Zone verlassen statt darin auf Heilung zählen. Nach E-Verbrauch folgen und E gegen nächste Q-Autos.',
'Shen-R kann mit Fear oder eigener R unterbrochen werden, wenn rechtzeitig erreichbar. Sonst pingen und Crash/Plates nehmen.',
'Q-Schwertdurchzug, W-Autoblock, E-Taunt und globale R.',
'W beendet und E verbraucht; Q-Verstärkung abgelaufen.',
'Q-/Autoheilung in W voraussetzen; unnötig für R-Unterbrechung unter Turm tauchen; Schwertposition ignorieren.',
'Vor seinem R-Fenster Push vorbereiten. Ohne erreichbaren Interrupt voll crashen statt an leerer Lane zu freezen.',
'Q-Autos mit E dämpfen, W abwarten. Auto–Q–Auto für PTA, Fear nach Taunt; R für Heal oder tatsächlich erreichbaren Kanalabbruch.',
'1: W-Pausen erlauben Druck. 2: Waveclear stärkt Turmantwort. 3: Warwick kann Side halten, Shen erzeugt anderswo Zahlenvorteile.');
add('singed','E','D','E','PTA','aprange',
'Gift, Grounding und Flip verhindern Warwicks stationäre Heil-Autos. Singed kann die Lane umgehen und zwingt schlechte Verfolgungen.',
'Warwick gewinnt direkten Kontakt ohne lange Giftstrecke. Nicht für einen Trade durch die ganze Wave hinterherlaufen.',
'Flip und Kleber respektieren. In Grounding Q/R nicht als freie Flucht planen; nach Flip nur bei kurzem sicheren Weg angreifen.',
'Singed-R gibt starke Dauerwerte, sein Gift mit R beeinträchtigt Heilung. Eigene R nur nach Flucht-/Kontrollfenster und außerhalb langer Giftbahn.',
'Q-Gift, W-Grounding, E-Flip und R-Werte/Antiheal.',
'W und E verbraucht und R nicht aktiv; kurzer Zugriff von vorne statt Hinterherlaufen.',
'Proxy endlos jagen; auf passive Heilung ohne Autoziel setzen; in Kleber R retten wollen.',
'Wave einsammeln und Proxy mit Teamzustand bewerten. Vollständigen Crash sichern, nicht mehrere Waves für unklaren Singed-Kill verlieren.',
'Von vorn Auto–Q–Auto, E gegen Gift. Fear zur Trennung, R bei sicherem Catch; nach Flip keinen automatischen Chase.',
'1: MR/Waveclear erhalten Spielbarkeit. 2: Stride hilft nur bei erreichtem Ziel. 3: oft kein sinnvolles langes Side-Duell, Objectives und Catch wählen.');
add('sion','B','B','C','Lethal Tempo','hp',
'Warwick kann Sions HP im Kontakt gut bearbeiten und Q-Kanäle kontrollieren. Sion kann mit Waveclear und R den direkten Kill verweigern.',
'Q-Zone seitlich verlassen und nach Fehlschuss Auto–Q. Warwick gewinnt längeren Nahkontakt ohne vollen Charge.',
'Fear für geladene Q bereithalten; E vor unvermeidlichem Burst. Sion-W nicht mit voller Rotation füttern, wenn es bald ausläuft.',
'Sion-R nicht mit Fear als sicher stoppbar behandeln. Eigene R nach seiner Fluchtphase oder bei gebundenem Ziel; nach Kill Passive verlassen.',
'Geladene Q, W-Schild/Explosion, E-Slow, R und Todespassive.',
'Q abgebrochen/verfehlt, W vorbei und R nicht bereit.',
'Im voll geladenen Q stehen; nach Kill auf Low HP an der Passive kämpfen; Ressourcen ohne Killchance unter Turm leeren.',
'Q-Push ausdünnen, dann eigene Hälfte halten. Bei ständiger Flucht Crash für Plates/Rotation statt endloser Verfolgung.',
'Q umgehen oder mit Fear abbrechen, Auto–Q–Autos, E gegen W. R nach Schild und ohne neue Q-Kanalantwort.',
'1: BotRK/Q gegen HP brauchbar. 2: Resistenzmix erschwert schnelle Kills. 3: Warwick kann Side halten, Sion erzeugt Druck durch Waves und R.');
add('sylas','B','A','C','Lethal Tempo','ap',
'Warwick kann Sylas frühen Nahkampf über mehrere Auto-/Q-Zyklen gewinnen. Sylas’ W-Heal und gestohlene R ermöglichen dennoch knappe Turnarounds.',
'E2 durch Minions erschweren. Warwick bei dauerhaftem Kontakt gut, nicht unnötig dessen vollen Passive-Burst nehmen.',
'Nach W ernsthaft handeln, eigenes E gegen E2-/Passive-Burst. Mana für zweiten Q-Zyklus sichern.',
'Sylas kann Warwicks R stehlen und selbst heilen/unterdrücken. Eigene R nach seiner E-Kontrolle, nicht beide Ultis als automatischen Warwick-Vorteil zählen.',
'W-Heal, E2, Passive-Autos und gestohlene R.',
'W und E verbraucht; fehlender Zugang auf nächste W-Heilung ermöglicht den längeren Kill.',
'Seine Low-HP-W ignorieren; R mit direkt bereitem E2 unterbrechen lassen; Mana beim Farmen leeren.',
'Eigene Hälfte für langen Kontakt, kleine Wave gegen Passive-AoE. Bei Sieg komplett crashen und Reset erzwingen.',
'E vor E2-Burst, Auto–Q–Autos. Nach W-Heal weiter, Fear für erneuten Zugriff; R wenn sein Kontrollzyklus vorbei ist.',
'1: Warwick oft guter Duelldruck. 2: Antiheal/MR nach Bedarf. 3: gestohlene Team-Ultis verändern Sylas Gesamtwert, Side bleibt buildabhängig.');
add('tahmkench','C','C','C','Lethal Tempo','hp',
'HP und Nahkontakt passen zu Q/On-Hit, aber graues Leben und Devour können Warwicks Heilzyklus unterbrechen.',
'Minions gegen Q nutzen. Direkte Autos bei kleiner Wave handeln, nicht wiederholt Slow aus der Distanz nehmen.',
'Zungen-Q ausweichen, graues Leben/Schild abwarten. Eigene E vor drittem Stack und Burst, nicht erst nach Kontrollbeginn.',
'Drei Stacks plus R können deine Heilphase aussetzen. Eigene R nach Stack-/Q-Stun-Fenster und ohne vollen Schild einsetzen.',
'Q-Stun nach Stacks, W-Tauchgang, E-Schild und R-Devour.',
'Q verfehlt, W verbraucht und Schild beendet; drei Stacks auf dir begrenzen den scheinbaren Kill.',
'R-Heilung in vollen E-Schild rechnen; drei Stacks und Devour ignorieren; ohne Rückweg in Q-Slow laufen.',
'Minion-Schutz auf eigener Seite erhalten. Keine lange Freeze, wenn seine Qs dich dadurch frei treffen; kontrolliert ausdünnen.',
'Auto–Q, E vor Stack-Burst. Schild abwarten, Fear für Abstand bei drei Stacks oder Anschluss nach Q-Verbrauch; R bei sicherem Kanal.',
'1: BotRK guter HP-Druck. 2: gegenseitige Defensive verlängert. 3: zähes Duell, Tahm kann Carries schützen statt deine Side anzunehmen.');
add('teemo','D','D','C','PTA','aprange',
'Blind nimmt Warwicks Auto-Heilung und erschwert On-Hit-Druck. Nach Blind-Ende kann Warwick Teemo mit einem kurzen Catch bestrafen.',
'Teemo gewinnt Range-Poke. Bei Q-Start keinen Low-HP-Autokampf erzwingen; Busch/Minions für sichere CS nutzen.',
'Blind auslösen, zurücktreten, danach erst längeren Zugriff. Q-Heilung nicht pauschal mit normaler Auto-Uptime verwechseln.',
'Pilzpfad prüfen und R nach Blind-/Fluchtfenster auf Sicht. R ist kein dauerhafter Schutz vor Teemos nächstem Blind.',
'Q-Blind, E-Gift, W-Tempo und R-Pilze.',
'Q verbraucht und W-Flucht erschwert; keine Pilzkette auf dem Anschlussweg.',
'Passive im Blind als Rettung erwarten; auf Blood Hunt durch Pilze rennen; MR für unnötigen Crit aufschieben.',
'Eigene Seite mit sicheren Farmwegen. Nach 6 Pilze bei Push mitdenken; Waveclear schafft Resets statt endlosen Gifttrades.',
'Blind baiten, kurze Pause; danach E gegen Gift, Auto–Q–Auto, Fear für Anschluss. R nur auf geprüftem Weg bei sicherem Ziel.',
'1: MR/Zugang priorisieren. 2: kurze Catches werden realistischer. 3: mit Sichtkontrolle spielbar, unvorbereitete Side bleibt gefährlich.');
add('trundle','D','C','E','Lethal Tempo','ad',
'Beide gewinnen lange Autos, Trundles Q-AD-Diebstahl und R-Resistenzdiebstahl verschieben spätere Duelle gegen Warwick.',
'Q-Steal beachten; kein blindes All-in bei schlechter Wave oder Ignite-Nachteil. Q-Heal gezielt nach Schaden.',
'W-Feld verlassen oder dessen Ende abwarten. Eigene E für die dichte Auto-Phase, Fear für Trennung nach Pillar.',
'R-Duell nicht automatisch annehmen. Subjugate reduziert Widerstandskraft; mit Fear und Wegwahl pausieren, eigene R nach Pillar für weniger Abbruchrisiko.',
'Q-AD-Steal, W-Attack-Speed, E-Pillar und R-Statdiebstahl.',
'W vorbei und R fehlt; Pillar verbraucht erleichtert sicheren Rückzug/erneuten Zugriff.',
'Sein W/R komplett durchstehen wollen; Pillar im R-Kanal ignorieren; defensive Items als garantierten Side-Sieg zählen.',
'Eigene Seite mit kurzem Rückweg. Frühe Crashfenster nutzen; später Side nicht ohne R-/W-Timer übernehmen.',
'Auto–Q, E gegen Q/Autos. Bei W/R ausfearen, nach Ablauf neu; R nach Pillar, solange genug HP für Heilung bleiben.',
'1: ausgeglichener bis schwieriger Auto-Kampf. 2: sein R und AS werden stärker. 3: Warwick braucht deutlichen Vorteil oder Teamhilfe.');
add('tryndamere','D','C','E','Lethal Tempo','ad',
'Warwick kann frühe Trades heilen und Fury-Fenster bestrafen. Tryndameres R überbrückt später das Killfenster und zwingt präzises Kiting.',
'Keine volle Fury aufladen lassen. Bei niedriger Fury Q-Trade; frühe Crit-Varianz macht knappe All-ins riskant.',
'Nach E-Verbrauch handeln, Q-Heilung verbraucht Fury. Eigene E gegen Autos, nicht sofort für Fear wegwerfen.',
'R erzwingen, mit E-Reduktion/Fear und Bewegung überleben. Eigene R bei fast totem unverwundbarem Ziel heilt nicht zuverlässig genug: nicht als komplette Reset-Heilung kalkulieren.',
'Fury-Crits, W-AD-Senkung/Slow, E-Reset und R-Unsterblichkeit.',
'R fehlt, Fury niedrig und E verbraucht. Während R nur tödlichen Chase verhindern, nicht weiter den Kill erzwingen.',
'R und Fear gleichzeitig vor seiner R verschwenden; maximalen R-Heal an minimalen HP voraussetzen; bei W falsch abdrehen.',
'Fury-Aufbau mit kontrollierten Trades begrenzen. Eigene Seite für Rückzug; spätere Side nur mit passenden CDs halten.',
'E gegen Autos, Auto–Q–Autos bis R. Dann Fear/Abstand und Barrier falls nötig; nach R-Ende mit Q abschließen, sofern E-Flucht kontrolliert ist.',
'1: ohne R-Fenster gegenseitig bestrafbar. 2: Armor verbessert Überleben. 3: schnelle E-Zyklen und R machen dauerhaftes Solo-Halten schwer.');
add('urgot','D','C','E','Lethal Tempo','ad',
'Warwick kann vor Urgots W-Spike kämpfen, aber E-Flip und R-Execute bestrafen Low-HP-Heilung. Spätere Shotgun-Zyklen erhöhen den Druck.',
'Seine bereiten Beine vermeiden. Nur nach E-Verfehlen direkt kämpfen, keine freien Rundum-Shotguns geben.',
'E seitlich umgehen oder Q-Timing bewusst nutzen; kein garantierter Anti-Flip-Trick. Eigene E vor W/Shotgun-Schaden.',
'Unter Execute-Schwelle mit R-Markierung nicht auf Barrier als Rettung zählen. Vorher heilen, R1 ausweichen oder den Kampf vermeiden.',
'E-Flip/Schild, passive Beine, W ab höheren Rängen und R-Execute.',
'E verfehlt, relevante Beine verbraucht und R nicht verfügbar. Ab W-Max ist die Pause kleiner.',
'Barrier als sichere Antwort auf aktiven Execute nehmen; Q-Halten um ihn herum in frische Beine; volle R-Markierung ignorieren.',
'Eigene Seite, nicht in seinen starken Push/W-Spike kämpfen. Wave ausdünnen und sichere Resets vor Level-9-Druck.',
'E ausweichen, Auto–Q-Tap auf verbrauchter Beinseite. E gegen W, Fear für Abstand; R rechtzeitig heilen, bevor Execute-Bedingung erfüllt ist.',
'1: vor W-Max gute Fenster. 2: Urgot gewinnt dauerhafte DPS. 3: schwere Side bei Gleichstand, Execute verhindert typische Warwick-Baits.');
add('vayne','E','D','E','PTA','ranged',
'Silberbolzen, Condemn und R-Stealth nehmen Warwick zuverlässige Heil-Autos. Q-Follow hilft situativ, ersetzt aber keine Antwort auf Unsichtbarkeit.',
'Range respektieren und dritten W-Treffer vermeiden. Kein langer Lauf durch freie Autos.',
'Condemn baiten; bei bereits bestehendem Kontakt Q-Halten für Tumble/Knockback timen. Wände meiden.',
'R erst wenn sichtbar und Fluchtfenster reduziert. Sweeper gibt keine dauerhafte Zielbarkeit; eigene E reduziert W-True-Damage nicht.',
'E-Wandstun, W-True-Damage, Q-Tumble und R-Unsichtbarkeit.',
'E verbraucht und R nicht aktiv; Q allein ist zu kurz als zuverlässiges Langfenster.',
'R blind in Stealth, E als Schutz gegen Silberbolzen, ohne Flash über offene Side verfolgen.',
'Eigene Seite und Gankzugang, Minions zum Heilen nur ohne gratis dritte Procs. Voll crashen bei ihrer Abwesenheit.',
'E herausziehen, dann kurzer Auto–Q–Auto-Kontakt. Fear bei Sicht, R nach Tumble/Stealth-Ende; bei erneutem Unsichtbarwerden nicht alle Ressourcen blind werfen.',
'1: Fehler in E nutzbar. 2: Stealth/On-Hit schwer. 3: offene Side klar schwierig, Catch aus Nebel mit Team besser.');
add('vladimir','C','B','D','PTA','aprange',
'Warwick kann frühe kurze Kontakte erzwingen, Vladimir mit Pool aber R-Zugriff vermeiden. Später bedrohen verstärktes Q und R-Burst knappe HP.',
'Roten Q-Balken meiden. Nach normalem Q kurzer Kontakt; nicht für jeden Poke Mana in Minion-Q ausgeben.',
'Pool erzwingen und nach Ende neu kommen. Eigene E vor E-/Q-Burst, genug Mana für Folge-Q behalten.',
'R nicht in bereiten Pool. Vlad-R-Endschaden berücksichtigen und eigene Heilung/Barrier vorher timen.',
'Empowered Q, W-Pool, E-Aufladung und verzögerter R-Schaden.',
'Pool verbraucht und kein rotes Q; nach E-Verbrauch kurzer Zugriff.',
'R in Pool, unter rotes Q laufen, verzögerten R-Burst beim Low-HP-Ködern vergessen.',
'Langer Rückweg auf eigener Seite. Nach Pool-Lücke vollständiger Crash; spätere freie Farm nicht als Sieg ansehen.',
'Auto–Q–Auto, E gegen E/Q. Pool rausziehen, dann mit Fear und R zweites Fenster; R-Burst früh mit Heilung/Barrier abfangen.',
'1: früher Kontakt kann günstig sein. 2: MR unterstützt, Pool bleibt Grenze. 3: Vlad-Sustain/Burst und Teamfight wachsen stärker.');
add('volibear','D','C','D','Lethal Tempo','mixed',
'Beide heilen im Nahkampf. Volis E-Schild und markiertes W können den Kampf drehen; Warwick muss E-Zone und W-Heal bewusst beantworten.',
'Warwick bei Q-Kontakt gut, Voli mit passiver AS und Wave nicht unterschätzen. Nicht in seinen vorbereiteten E-Bereich laufen.',
'E-Zone verlassen und eigene E vor Q-Stun drücken. Markiertes W-Healfenster: mit Fear pausieren oder nur bei überprüftem Schaden weiterkämpfen.',
'Voli-R-Ankunft nicht mit Fear stoppen wollen. Eigene R nach Q-Stun und E-Schild; unter deaktiviertem Turm nicht auf sicheren Towerbait zählen.',
'E-Schaden/Schild, Q-Stun, W2-Heal und R-Towerdisable.',
'E verfehlt, Q verbraucht und W-Markierung abgelaufen; ohne diese Bedingungen bleibt der lange Heal-Kampf unsicher.',
'In E stehen und trotzdem statchecken; E-Recast vor seinem Burst; R-Heal gegen vollen Schild überschätzen.',
'Wave auf eigener Seite, aber Dive-Wave ab Level 6 ausdünnen. Volis Passive-Push für guten Bounce nutzen.',
'E ausweichen, eigene E vor Q, Auto–Q–Autos. Markiertes W mit Fear/Abstand überbrücken; nach E-Schild und Stun R heilen.',
'1: stark CD-abhängig. 2: AP-/On-Hit- oder Tankbuild neu bewerten. 3: Volis wiederholte W/E-Zyklen machen identische Dauerduelle schwieriger.');
add('wukong','B','B','C','Lethal Tempo','ad',
'Warwick kann Wukongs kurze Auto-Trades heilen. Clone und doppelte R verhindern jedoch sichere Zielbindung und ungestörte R-Heilung.',
'Nach E-Ankunft eigene Q handeln; gegnerische Passive-Armor macht rein physischen Vergleich unvollständig.',
'Clone nicht mit echter Zielbestätigung verwechseln. E vor E–Q-Autos, Q/R für sichtbaren echten Champion reservieren.',
'Zwei R-Aktivierungen beachten. Nach erster R ist die Kontrollphase nicht zwingend vorbei; eigene R erst bei sicherem Anschluss.',
'W-Clone/Unsichtbarkeit, Q-Armor-Shred und beide R-Knock-ups.',
'W verbraucht und R-Kontrolle beendet; Q allein erzeugt nur einen kurzen Trade.',
'R auf Clone, zweite R vergessen, E-Reduktion im Nichts ablaufen lassen.',
'Eigene Hälfte mit sichtbarem Rückweg. W-Flucht nicht in unbekannten Jungle verfolgen; Crash für Reset nutzen.',
'E gegen E–Q, Auto–Q nur auf bestätigtes Ziel. Clone abwarten, Fear nach Rückkehr, R nach letzter Kontrollphase.',
'1: Warwick gute Sustained-Trades. 2: Armor/CDs machen den Kill schwerer. 3: Side spielbar, Wukongs Teamfight-CC oft wertvoller.');
add('yasuo','B','B','C','Lethal Tempo','ad',
'Warwicks direkter Nahkampf ist früh stark. Minion-Dashes und Q3 können aber den R-Kanal unterbrechen und sichere Auto-Zeit verhindern.',
'Passivschild erst entfernen. Keine lange Verfolgung durch große Minionwave; Q seitlich umgehen.',
'Q3 und verfügbare Minion-Dashes lesen. Q-Halten nur mit sicherem Zielort, E gegen wiederholte Autos.',
'R erst nach Q3 oder aus Fear. Windwall ist nicht der zentrale Blocker deiner Nahkampfrotation, die Luftkontrolle ist es.',
'Q3, E-Minionpfade, Passivschild und R-Follow-up.',
'Q3 verbraucht und wenige frische Dash-Ziele; nach Schildablauf besseres Heil-/Damagefenster.',
'Q-Halten bis unter Turm mitnehmen lassen; R im vorbereiteten Tornado; starke frühe Lane als ewigen Vorteil lesen.',
'Dünne Wave auf eigener Seite, ohne viele freie E-Ziele. Nach erzwungenem Rückzug komplett crashen.',
'Schild entfernen, Auto–Q–Autos; E gegen Q/Autos. Q3 ausweichen, Fear nach Dash und R kurz bestätigen.',
'1: Warwick kann Kontakte dominieren. 2: Crit und Armor-Werte prüfen. 3: spielbar, aber Minionmobilität und Crit-Burst können drehen.');
add('yone','B','B','C','Lethal Tempo','ad',
'Warwick kann Yones frühen Nahkampf bestrafen und dessen E-Rückkehrpunkt kontrollieren. Später erhöhen Mischschaden und Burst das Risiko.',
'Q3 nicht gratis aufladen lassen; Auto–Q bei ungefüllten Stacks und kleiner Wave.',
'Nach W-Schild handeln und E-Rückkehrpunkt für Fear nutzen. Nicht über lange E-Reise ohne klare Anschlussposition folgen.',
'Q3/R bedrohen deinen Kanal. Nach seiner Rückkehr bzw. verbrauchter Kontrolle R nutzen, E-Reaktivierungsschaden in HP-Budget einrechnen.',
'E-Schadenswiederholung/Rückkehr, W-Schild, Q3 und R.',
'E beendet, Q3 verbraucht und W-Schild vorbei.',
'Q-Halten unbeabsichtigt in gefährlichen Rückkehrpunkt; R in laufende Q3/R-Kontrolle; verzögerten E-Schaden vergessen.',
'Eigene Hälfte, Rückkehrpunkt beachten. Nach E-Pause Crash/Recall sichern statt endlos ohne Mana Druck halten.',
'W abwarten, E gegen Autos, Auto–Q–Autos. Am Rückkehrpunkt Fear vorbereiten, R nach Kontrollverbrauch als rechtzeitige Heilung.',
'1: Warwick hat gute Druckfenster. 2: beide Builds relevant. 3: Yones Misch-/Critschaden verhindert sorglose Low-HP-Duelle.');
add('yorick','C','B','D','Lethal Tempo','ad',
'Warwick kann Yorick ohne Pets früh dominieren. Käfig, Ghouls und Maiden erzwingen später Zielwechsel und nehmen direkte Heil-Autos auf Yorick.',
'Vor vorbereiteten Gräbern aggressiv CS bestreiten. Q-Verstärkung nicht ohne eigene Antwort nehmen.',
'E seitlich ausweichen, Ghouls zuerst sicher entfernen. Q-Halten am Champion kann Position ändern, ist kein verlässlicher Ausweg aus jedem Käfig.',
'Maiden-Lage vor All-in prüfen. Eigene R für sicheren Championkontakt oder Flucht, nicht unüberlegt durch Pets/CC ins volle Setup.',
'E-Markierung, W-Käfig, Ghoul-Sprung und Maiden.',
'E verfehlt, W verbraucht und wenige Pets; nach Maiden-Tod besonders wertvolles Fenster.',
'Pets ignorieren, Käfig ohne Auto-Ausweg nehmen, niedrige Yorick-HP mit schwachem Gesamtsetup verwechseln.',
'Früh Freeze solange zonierbar; später Pets/Waves ausdünnen, bevor sie am Turm stapeln. Waveclear-Item für Side-Kontrolle.',
'E ausweichen, Pets entfernen, Auto–Q auf Yorick. Eigene E gegen Petburst; Käfig öffnen, dann Fear/R nachsetzen.',
'1: guter Druck ohne Maiden. 2: Waveclear entscheidet Farmkontrolle. 3: vorbereitetes Pet-Duell schwerer; Maiden gezielt mit Team entfernen.');
add('zaahen','D','C','D','Lethal Tempo','mixed',
'Warwick hat frühe Kontakte, Zaahens Heil-/Revive-Phasen verlängern spätere Duelle. Der aktuelle Q2-Buff erhöht die Unsicherheit zusätzlich.',
'Q2 ausweichen statt jeden Nahkampf zu erzwingen. Q-Heal nach erstem Schaden, Minionnachteil vermeiden.',
'Nach Q-Kette/E-Bewegung handeln und seine Passive-Aufladung lesen. E für tatsächlichen Burst statt sofortigen Fear einsetzen.',
'R-Verteidigung und Wiederbelebung als zweite Kampfphase einplanen. Nach Revive nicht annehmen, dass seine Q noch lange fehlt: 26.18 startet deren CD früher.',
'Q2, Bewegung mit E, passive Heil-/Revive-Phase und R-Defensive.',
'Q-Kette/E verbraucht, geringe Passive-Vorbereitung; nach R-Ende ohne verfügbare Wiederbelebung bessere Chancen.',
'Alle CDs vor Revive verbrauchen; volle Heilung in defensive Phase rechnen; neue Q-Verfügbarkeit nach Wiederbelebung ignorieren.',
'Eigene Seite mit Rückzugsweg für Phase zwei. Frühe gewonnene Trades crashen, statt passives Scaling-Duell zulassen.',
'Q2 umgehen, Auto–Q–Autos mit E gegen Antwort. Fear zur Unterbrechung von Uptime; R erst nach Defensivfenster und mit Plan für Revive.',
'1: frühe CD-Fenster spielbar. 2: Heil-/Revive-Zyklen stärker. 3: eher schwierig bei Gleichstand; Bewertung vorläufig nach Q2-Änderung.');
