import fs from 'node:fs/promises';
// Independently authored matchup judgments; no Olaf tactical text is copied.
const rows=[];
function add(slug,tier,lane,late,rune,profile,reason,l1,l25,l6,threats,window,errors,wave,trade,side){rows.push({slug,tier,lane,late,rune,profile,reason,l1,l25,l6,threats,window,errors,wave,trade,side});}
add('aatrox','D','C','D','PTA','ad',
'Q-Reichweite und Rückzug mit E erschweren kontinuierliche Heilung. Warwick kann nahe Trades gewinnen, Aatrox kontrolliert aber häufig den Abstand und später die Teamfights.',
'Warwick im direkten Kontakt; Aatrox beim freien Q-Poke. Q nicht für einen einzelnen CS ausgeben, wenn danach ein Nahkampf möglich ist.',
'Nach Q3 vorlaufen. Eigene E vor dem nächsten Sweetspot aktivieren; Q-Halten für seine E-Repositionierung aufsparen, statt blind in Q3 zu springen.',
'R nach seiner Q-Kette oder aus Fear bestätigen. Vorbereitete Qs und fremder CC können die Heilphase nach dem Aufprall unterbrechen; Aatrox-R nicht als freien Statcheck behandeln.',
'Q-Sweetspots, E-Abstand, W-Zone und Heilung mit R.',
'Q3 und E verbraucht; ohne eigene E nur kurzer Q-Trade. Nach gegnerischem R-Ende neu ansetzen.',
'Alle Sweetspots tanken; R bei voller HP als reinen Gapclose verschwenden; mit leerem Mana in den zweiten Kampf gehen.',
'Auf eigener Seite ausdünnen. Vollständig crashen vor Recall; ein halber Push gibt Aatrox Raum zum Poken.',
'Auto–Q–Auto im kurzen Kontakt, E gegen seine Antwort. Nach Q3/E längeren Kampf suchen; Fear Richtung eigene Lanehälfte, R erst bei sicherer Verbindung.',
'1 Item: BotRK erlaubt starke Kontakte, schützt nicht vor Q-Poke. 2: AD-Defensive verbessert Überleben. 3: Abstand, Antiheal und Aatrox-R entscheiden; kein garantierter Side-Sieg.');
add('akali','C','B','D','PTA','ap',
'Q-Trades und Sustain geben Warwick frühe Antworten. Shroud und R2 begrenzen lange Autos und bestrafen das bewusste Spielen auf wenig HP.',
'Direkter Nahkampf günstig, freies Q–Passive-Poken ungünstig. Nur nach verbrauchtem Q bis an sie heranlaufen.',
'Q-Trade wenn sichtbar, E gegen ihren Rückschaden. Nach Shroud-Ende mit Mana nachsetzen; im Nebel nicht auf blinde Autos hoffen.',
'R2 kann das Heilfenster abschneiden. R auf Sicht nach E/R-Bewegung bestätigen, keine maximale Distanz in verfügbaren Shroud.',
'W-Shroud, E-Markierung, R2-Burst und Q-Reichweite.',
'W abgelaufen und E verfehlt; ohne R hat sie weniger Fluchtmöglichkeiten.',
'Barrier bis nach R2 halten; ungezielt in Shroud ulten; Q-Halten ohne Sicht als Stealth-Aufdeckung verstehen.',
'Wave nahe eigener Seite halten, in ihrer W-Pause Crash vorbereiten. TP statt Barrier erwägen, wenn Poke wiederholt schlechte Resets erzwingt.',
'Auto–Q–Auto, E beim Gegenangriff. Bei W zurücktreten, an Minions erholen und nach Shroud mit Fear einen zweiten Kontakt sichern.',
'1: Q und Lifesteal stabilisieren. 2: MR hilft gegen Burst, erzwingt aber keinen Kill. 3: Akali kann den Zweikampf verweigern und andere Ziele erreichen.');
add('ambessa','C','B','D','Lethal Tempo','ad',
'Frühe Energie- und Schildpausen erlauben Warwick Druck. Spätere Mobilität und Heilung machen längere Kämpfe deutlich anspruchsvoller.',
'Warwick bei festem Kontakt; keinen Minionnachteil durch Verfolgung ihrer ersten Dash-Kette schaffen.',
'W-Schild abwarten, Energie-Autos bestreiten. Q-Halten auf einen erkennbaren Dash und E erst vor ihrem tatsächlichen Schaden.',
'Beide gewinnen Heil-/All-in-Werkzeuge. Ihre R-Bewegung erst abwarten oder mit sicherem Fear vorbereiten, statt gegeneinander blind zu springen.',
'W-Schild, Passive-Dashes, Q2 und R-Zugriff.',
'W verbraucht und niedrige Energie; ein Dash allein bedeutet nicht, dass ihre Kette beendet ist.',
'Q für Farm verschwenden und danach Dashes hinterherlaufen; in vollem Schild all-in gehen.',
'Eigene Seite mit genügend Minions für Erholung. Bei erzwungenem Rückzug voll crashen; nicht dauerhaft ohne Jungle-Sicht schieben.',
'Kurzes Q bis W verbraucht ist, dann E–Auto–Q-Halten–Autos. Fear erst für Anschluss oder Rückzug auslösen, R nach ihrem Ausweichfenster.',
'1: häufig frühes Duellfenster. 2: nach AD-Defensive beidseitig spielbar. 3: Ambessas Heilung und Mobilität können die Side drehen.');
add('camille','C','B','D','PTA','ad',
'Warwick kann frühe Q-Trades heilen und Hookshot mit gutem Q-Timing verfolgen. Später bestraft Q2-True-Damage sein Low-HP-Spiel.',
'Nicht in ihren Passivschild tauschen. Nach Schildablauf gewinnt Warwick den verlängerten Kontakt häufig.',
'Zwischen Q2-Fenstern handeln. Q-Halten gegen E-Flucht nur in Reichweite und bei sicherem Zielort; Fear verhindert den freien Rückzug, wenn sie sich bindet.',
'Camille kann mit ihrer R deiner R ausweichen. Ihre Ulti-/Hookshot-Nutzung abwarten, dann R bestätigen; E reduziert Q2-True-Damage nicht.',
'Passivschild, Q2, E an Wänden und R-Unzielbarkeit.',
'Schild und E verbraucht; frühes Q2 bereits eingesetzt. Eigene Manareserve für mindestens Q und E nötig.',
'E als Antwort auf True Damage einplanen; blind hinter E unter den Turm folgen; R in ihre bereite R werfen.',
'Wave auf eigener Seite, abseits der Wand für E. Nach gewonnener Schildrotation slowpushen und vollständig resetten.',
'Schild mit kurzem Kontakt provozieren, abwarten, Auto–Q–Auto. E gegen physische Antwort, Fear nach E-Landung; R nach ihrer R-Unzielbarkeit.',
'1: Warwick kann Druck halten. 2: Camille-Q2 wird gefährlicher. 3: eher Camille bei gleichen Ressourcen; Druck gemeinsam beantworten.');
add('chogath','B','B','C','Lethal Tempo','ap',
'Chos HP liefern ein erreichbares Ziel für Q und On-Hit. Silence, Knock-up und Feast verhindern aber sichere Heilung auf kritischen HP.',
'Q-Poke ausweichen und nah handeln; Warwick im Auto-Kontakt stärker, solange die gegnerische Wave klein bleibt.',
'Nach verfehltem Q längerer Trade; E vor E-Spikes. Nicht gleichzeitig mit Q auf ihn und in eine angekündigte Rupture gehen.',
'Feast setzt eine harte HP-Grenze. Barrier früh vor Silence/Execute nutzen; R heilen, solange noch genug HP für die Verzögerung bleiben.',
'Q-Rupture, W-Silence, E-Spikes, R-True-Damage.',
'Q und W verbraucht; nach Feast auf Minion fällt der Execute-Druck vorübergehend weg.',
'Unter der Execute-Grenze auf Passive vertrauen; Q-Heal erst während Silence einplanen; E als True-Damage-Schutz betrachten.',
'Außerhalb des Turms halten und seine Q-Ausdünnung bestrafen. Erst bei echtem Zeitfenster Crash, sonst regeneriert er über CS.',
'Q ausweichen, Auto–Q–Autos, E gegen Spikes. Fear als Anschluss; R vor tödlichem Feast und nach Silence.',
'1: BotRK/Q gegen HP günstig. 2: MR/HP halten dich aus Execute-Reichweite. 3: zäher Sidekampf; Cho bringt stärkere Objective-Sicherung.');
add('darius','D','C','D','Lethal Tempo','ad',
'Q-Halten kann den Außenring vermeiden, E seine physische Vorarbeit dämpfen. Fünf Stacks und R-True-Damage machen jeden knappen Kampf riskant.',
'Warwick kann Kontakt gewinnen, aber W-Start, Ignite und Minions verändern das Duell. Ohne klare HP-/Spell-Lage kein blindes Level-1-Rennen.',
'Q für seinen Außenring reservieren und nah bleiben. Früh abbrechen, falls er gratis mehrere Stacks bekommt, bevor du selbst Schaden anbringst.',
'Dunk ignoriert E-Schadensreduktion. Barrier und eigene R vor tödlichem Execute einsetzen; vorhandene Blutungsstacks laufen während R weiter.',
'Q-Außenring, W-Slow, E-Rückzugssperre, fünf Stacks und R.',
'Q verfehlt oder innerer Treffer, E verbraucht und wenige Blutungsstacks. Nach R-Ende/Verbrauch nur mit überprüfter HP-Lage.',
'Bei vier Stacks erst einen langen Rückweg beginnen; E gegen Dunk aufsparen; Q auf Minions verschwenden.',
'Eigene Seite mit Rückzugsweg. Levelvorsprung durch seine große Wave respektieren; keine unvollständigen Crashes, die lange Ghost-Chases ermöglichen.',
'Auto, sein Q mit gehaltenem Q innen treffen, E gegen Autos/W. Entweder vor fünf Stacks sauber rausfearen oder mit Mana und Barrier einen bewusst kalkulierten Kill abschließen.',
'1: stark von Außenring und Summoners abhängig. 2: Armor hilft gegen Vorarbeit, nicht R. 3: fehlendes Damagefenster wird hart bestraft; Teamfight-R auf Carry oft sinnvoller.');
add('drmundo','B','A','C','Lethal Tempo','hp',
'Früher Q-/Auto-Druck ist stark gegen Mundos schwache Kampfphase. Seine Passive blockiert den ersten Hard-CC, spätere R-Heilung verlängert das Duell.',
'Warwick im Kontakt klar im Vorteil; hinter Minions vor Cleavern schützen und nicht ohne Grund die Wave tanken.',
'Mit E seine Passive entfernen und Kanister kontrollieren, wenn erreichbar. Nicht für den Kanister in Turmreichweite gehen.',
'Erst Passive mit Fear auslösen, dann R verwenden. Mundo-R und Summoners einkalkulieren; ein frühes R bei voller HP liefert wenig Heilwert.',
'Passive-CC-Schutz, Q-Cleaver, R-Heilung und E-AD bei niedrigen HP.',
'Passive fehlt, Q verfehlt; nach R-Ende erneut angreifen statt jede Heilphase durchzudrücken.',
'R in aktive Passive verschwenden; auf Kanister kämpfen und Cleaver tanken; Heilung ungeprüft unterschätzen.',
'Früh Druck und kontrollierter Crash, danach Freeze für verweigerte CS. Tiamat erst, wenn du aus Push Turmzeit oder Rotationen bekommst.',
'Minions als Q-Schutz, Auto–Q–Autos, E-Fear entfernt Passive. Kanister nehmen, dann R als zweites Kontroll-/Heilfenster.',
'1: BotRK sehr brauchbar gegen HP. 2: Antiheal und genügend Schaden erhalten Druck. 3: Mundo wird schwerer zu töten; Turm-/Teamdruck statt endloser Verfolgung.');
add('fiora','D','C','E','Lethal Tempo','ad',
'Warwick kann frühe Nahkämpfe sustainen, doch Riposte bedroht beide Hard-CCs und späte Vitals umgehen E-Reduktion.',
'Schlechtes vorderes Vital durch Abstand zurücksetzen. Nach ihrer Q kurz handeln, keinen freien Vital-Kreis erlauben.',
'Fear-Timing variieren und ihre W baiten. Q-Halten kann ein Vital hinter dir öffnen; Position ist wichtiger als zusätzliche Animation.',
'R nicht in bereite Riposte. Bei ihrer R eine Vital-Seite an einer Wand schützen und Barrier vor dem letzten Burst nutzen.',
'Passive-Vitals, W-Riposte inklusive AS-Slow, R-Heilfeld.',
'W verfehlt; Q auf Cooldown und kein freier Vitalzugang. Ein pariertes E macht den sofortigen Folgeangriff schlecht.',
'E und R zusammen in Riposte werfen; True Damage über E tanken wollen; mit Q-Halten alle Vitals anbieten.',
'Nahe eigener Seite, aber genügend Platz zum Vital-Schutz. Früh gewonnene Trades für Crash/Plates nutzen, nicht das spätere gleiche Duell abwarten.',
'Auto–Q-Tap und seitlich repositionieren. W herausziehen, danach Fear und R zeitlich versetzen; an Wand heilen, ohne von Minions eingeschlossen zu sein.',
'1: spielbares Duell nach W-Verbrauch. 2: Fioras Vitals gewinnen Gewicht. 3: bei Gleichstand klar schwieriger; nicht allein ihre perfekte R ausspielen lassen.');
add('gangplank','D','D','D','PTA','ad',
'Barrels und Q halten Warwick von Heil-Autos fern. Oranges lösen Suppression, weshalb die eigene R erst nach W zuverlässig bindet.',
'Gangplank gewinnt Abstandspoke; Warwick nur bei unerwartetem Nahkontakt. HP für Level 2 erhalten.',
'Fässer zuerst entschärfen, Q-Trades in Lücken. Nach Passive-Procs nicht wiederholt kurze Treffer tauschen, die er mit Fass-Reset wiederholt.',
'Sein W vor R erzwingen; im Ultifeld nicht geradlinig durch eine Fasskette jagen. Fear und R getrennt nutzen.',
'Fassketten, Passive-True-Damage, W-Reinigung und R-Slow.',
'Keine nutzbaren Fässer und W verbraucht; fehlendes Q erleichtert Zugang, ersetzt aber kein Fassfenster.',
'R in Orange, Low-HP-Trade auf brennender Passive oder Auto-Commit durch zwei Fässer.',
'Wave näher bei dir und seitlich von Fässern halten. Wenn er roamt, vollständig pushen; nicht in eine sichere Barrel-Freeze hineinlaufen.',
'Fass brechen, Auto–Q–Auto, E gegen Q/Autos. Fear erzwingt W; danach R für Heilung und Anschluss, sofern keine neue Fasskette bereitsteht.',
'1: Zugang ist wichtiger als Dummy-DPS. 2: Stride kann Kontakt erleichtern. 3: GP kann mit Crit stark punishen und global beitragen.');
add('garen','D','C','D','PTA','ad',
'Q-Heilung beantwortet kurze Trades; Garen kann mit W und E zurückgehen. Seine R bestraft Warwicks Low-HP-Fenster besonders stark.',
'Warwick im längeren Kontakt günstig; seinen Q-Treffer nicht ohne Antwort nehmen.',
'E vor Silence/Spin drücken, Auto–Q wenn wieder möglich. W-Verteidigung nicht mit kompletter Rotation füttern.',
'Barrier früh vor tödlichem R; E reduziert den Execute nicht. R nicht erst bei minimalen HP starten, wenn Q-Silence noch bereit ist.',
'Q-Silence, W-Verteidigung, E-Rüstungssenkung und R-Execute.',
'W und E verbraucht; Q bereits eingesetzt, sodass ein eigener Q-Heal nicht blockiert wird.',
'Barrier erst unter Silence planen; Garen nach Spin gratis passiv heilen lassen; ohne Mana auf Low HP ködern.',
'Kurze Kontakte verhindern ungestörte Passive, aber Wave nicht per Dauer-Q schieben. Nach E-Push ausdünnen und Bounce nutzen.',
'E vor Q–E, nach Silence Auto–Q–Auto. Mit Fear Abstand schaffen, W abwarten und zweiten Trade starten; R rechtzeitig vor Execute.',
'1: Sustainduell spielbar. 2: Armor begrenzt Spin, nicht Execute. 3: Garen kann Fehler schnell abschließen; kleine HP-Baits verlieren Verlässlichkeit.');
add('gnar','D','D','C','PTA','ranged',
'Mini-Gnar gewinnt wiederholtes Spacing; Warwick braucht einen echten Kontakt. Mega-Gnars feste Kampfphase bietet bessere Q-/E-Gegenfenster.',
'Gnar kontrolliert freie Autos. Hinter Minions gehen, Q-Heilung sparsam nutzen und kein langes Level-1-Chase starten.',
'Nach E mit bereitgehaltener Q folgen, falls bereits in Reichweite. Vor Rage-Transformation nicht für ein knappes Blood-Hunt-Ziel committen.',
'R nach Sprung oder auf immobileren Mega-Gnar. Unterbrechungs-CC nach Aufprall beachten; nicht neben Wänden auf Low HP feststehen.',
'Mini-W-Dreiertreffer, E-Doppelsprung, Rage, Mega-W/R.',
'E verbraucht und Rage niedrig; Mega-Q/W verfehlt liefert einen Nahkampf ohne freien Rückzug.',
'In fast volle Rage laufen; im Rückzug weitere W-Procs schenken; W-Lauftempo als Kampfimmunität gegen Kiting verstehen.',
'Wave auf eigener Seite, größere Wellen ausdünnen. Unter Turm sicher farmen und nach verbrauchtem E junglerfreundlich halten.',
'Nach Q-Verfehlen vorlaufen, Auto–Q-Halten auf E nur bei Kontakt, E gegen den Gegenschaden. Fear hält Anschluss, R nach Mobilität.',
'1: Stride hilft erst nach Erstkontakt. 2: Armor/HP stabilisieren. 3: Mini bleibt ausweichfähig, Mega ist direkter bekämpfbar; Teamfightwinkel entscheidend.');
add('gragas','B','B','C','PTA','ap',
'Warwick kann kurze Gragas-Trades heilen und hat Q-Timing gegen Verdrängung. Gragas kann jedoch viele Kills mit E/R verhindern.',
'Q-Poke ausweichen, Nahkontakt mit Auto–Q beantworten. Nicht in seinen vollen W-Treffer laufen, falls er W startet.',
'E erst nach Body-Slam-Verbrauch durchziehen. W-Reduktion abwarten, Q-Heal gegen seine kurze Rotation tauschen.',
'R nicht als blinden Start gegen E/R nutzen. Gehaltenes Q kann bei passendem Timing Verdrängung abfangen, ist aber kein allgemeiner CC-Cleanse.',
'E-Body-Slam, W-Reduktion, Q-Slow und R-Abstand.',
'E verfehlt und W beendet; ohne R fällt ein wichtiges Disengage-Werkzeug weg.',
'Jeden Q-Treffer mit teurer Heil-Q beantworten; R durch bereitliegende Kontrolle; sicherer Farm-Vorteil für schlechten Dive aufgeben.',
'Eigene Hälfte für längeren Rückweg. Falls er jeden Trade verweigert, Crash und Recall/Objective statt Mana in Turmreichweite verschwenden.',
'W-Schaden mit E abfangen, Auto–Q–Auto nach seinem E. Fear Richtung eigene Hälfte, R als zweiter Zugriff nach seinem R.',
'1: Warwick häufig stark im Kontakt. 2: MR verbessert Wiederholungen. 3: Gragas kann die Side neutralisieren und über Engage mehr Gesamtwert erzeugen.');
add('gwen','B','A','D','Lethal Tempo','ap',
'Frühe Nahkontakte sind für Warwick gut spielbar. Später steigen Gwens Heilung und True-Damage-Anteil, gegen den E nicht genügt.',
'Nicht gegen voll gestapelte Q mitten in Minions stehen. Nach Q-Verbrauch längeren Auto-Kontakt suchen.',
'Q-Zentrum seitlich oder mit Q-Halten verlassen; W-Nebel ist im Nahkampf kein vollständiger Schutz vor Warwick. Ihr E entscheidet Rückzug.',
'R-Nadeln seitlich ausweichen und eigene R nicht für den Erstkontakt verschwenden. E reduziert magische Anteile, nicht Q-True-Damage.',
'Q-Zentrum, E-Reset, W-Resistenzen und R-Heilung.',
'Gestapelte Q verbraucht und E fehlt; nach R-Ende ist ein zweiter Angriff wesentlich besser.',
'Alle Nadeln und Q-Zentren tanken; nach frühem Sieg drei Items passiv abwarten.',
'Früh zonen, kontrolliert crashen und den Bounce halten. Mit Farmdeny Druck machen; ihr Minion-Q-Stacken nicht gratis geben.',
'Q-Zentrum umgehen, Auto–Q–Autos, E gegen magischen Rückschaden. Fear nach E, R zur Heilung nach Nadelserie bei weiterhin sicheren HP.',
'1: Warwick kann Vorteile erzwingen. 2: MR und Goldvorsprung helfen. 3: gleichwertige lange Kämpfe werden für Warwick deutlich schwerer.');
add('heimerdinger','D','D','C','PTA','aprange',
'Türme verhindern sicheren Dauerkontakt. Nach Abbau des Nests und verfehlter Granate kann Warwick dagegen einen kurzen Kill erzwingen.',
'Heimer kontrolliert das Nest. Türme sicher mit Minionhilfe entfernen; keine Q-Heilung gegen drei aktive Türme erzwingen.',
'Nicht Raketensalven und Turmstrahlen zugleich tanken. Granate herauslocken, dann kleine Trades am Rand statt mitten im Nest.',
'R erst nach E-Verbrauch und bei erreichbarem Champion. Fremder oder verzögerter CC kann den Kanal beenden; R-Turm eventuell verlassen.',
'E-Granate, Turmstrahlen, Raketen und verstärkte R-Varianten.',
'E verfehlt, Türme reduziert; ein niedriger Heimer mit vollem Nest ist kein automatisches W-Killfenster.',
'R ins komplette Nest, Low-HP-Passive ohne erreichbare Autos, alle Ressourcen für einen einzelnen Turm.',
'Wave unter eigener Kontrolle empfangen, Nest mit Minions abbauen. Ein Cheater-Recall ist nur bei tatsächlich freiem vollständigem Crash möglich.',
'Turm abbauen, E ausweichen, Auto–Q–Auto. Eigene E vor Turmstrahlen, Fear aus dem Nest heraus; R kurz und sicher nach E.',
'1: MR/Zugang wichtiger als bloßer On-Hit. 2: Waveclear erlaubt Resets. 3: Kämpfe außerhalb des Nests oder mit Teamdruck suchen.');
add('illaoi','D','C','E','Lethal Tempo','ad',
'Ohne Geisttreffer hat Warwick frühe Kontakte. E und R produzieren aber Schaden und Heilung, die ein statischer Low-HP-Kampf kaum kontrolliert.',
'Tentakel entfernen, bevor Nahkampf beginnt. Nach Q-Ausweichen ist Warwick stark, zwischen zwei Tentakeln nicht.',
'E durch Minions blockieren und nach Fehlschuss durchziehen. Bei getroffenem Geist Lage bewerten und den schlechten Bereich verlassen.',
'Ihre R-Zone verlassen, statt über Passive darin zu stehen. Eigene R nach gegnerischer R-Pause oder zur Flucht verwenden.',
'E-Geist, R-Tentakel, W-Sprünge und Flächenschläge.',
'E verfehlt und wenige Tentakel; R verbraucht. Fehlendes Q alleine reicht im vorbereiteten Nest nicht.',
'In Geist plus R hineinulten; Q-Halten unter Tentakel; Antiheal als Ersatz für Ausweichen ansehen.',
'Nicht unter eigenem Turm ein komplettes Nest zulassen: früh ausdünnen und Tentakel löschen. Crash nur nach E-Pause.',
'E ausweichen, Auto–Q–Autos mit eigener E. Wenn Illaoi R setzt, Fear für Abstand und raus; nach Ablauf neu mit Q beginnen.',
'1: gute E-Pausen nutzbar. 2: Antiheal/Armor nötig, aber kein Freipass. 3: vorbereitete Side bleibt sehr schwer; Rotation erzwingen.');
add('irelia','A','A','C','Lethal Tempo','ad',
'Warwick kann Irelias Nahkampf und Heilung früh beantworten. Entscheidend sind Minion-Resets und ihre Passive, nicht ihr bloßes Championlevel.',
'Ohne gestapelte Passive Warwick-favored. Nicht vier Gratis-Qs vorbereiten lassen und dann in voller gegnerischer Wave kämpfen.',
'Nach E-Verfehlen kämpfen, Q-Halten auf Flucht-Q nur mit sicherem Zielort. Eigene E vor ihrem Auto-Burst, Fear wenn Resets aufgebraucht sind.',
'R nicht in ihr defensives W verschwenden, wenn du erst noch heilen musst. Minion-Mobilität beachten und aus Fear kurz bestätigen.',
'Passive-Stacks, niedrige Minions, E/R-Markierung und W-Reduktion.',
'E verfehlt, Passive niedrig und keine Q-Reset-Kette. Nach W bleibt ein echtes Dauerfenster.',
'In ihre sechs niedrigen Minions verfolgen; an W heilen wollen und geringe Rückheilung ignorieren; Goldvorsprung überschätzen.',
'Eigene Seite halten, Minion-HP bewusst beobachten. Große Slowpush-Wellen machen ihre Q-Resets gefährlicher; nach Crash neu positionieren.',
'Auto–Q, E vor verstärkten Autos. W abwarten, Fear nach letzter Flucht-Q, R für Heilung und sicheren Abschluss.',
'1: Warwick kann frühe Side dominieren. 2: BotRK auf beiden Seiten macht Wave-State entscheidend. 3: nicht automatisch gewonnen; Irelia kann Carries leichter erreichen.');
add('jax','E','D','E','PTA','ad',
'Counter Strike nimmt Warwick Autos und damit einen großen Teil seiner Heilung. E-Pausen sind spielbar, spätere kurze E-Zyklen bleiben ein strukturelles Problem.',
'E-Start respektieren, bis Dodge vorbei ist. Keine lange Auto-Kette in Counter Strike, auch mit Barrier nicht.',
'Eigenes E reduziert Gegenschaden und Fear kann Abstand schaffen. Q nicht als zuverlässige Heilung in Dodge einplanen; nach E zügig handeln.',
'Eigene R nicht gleichzeitig mit Jax-E als volle Heilgarantie betrachten. Erst E beenden lassen; seine R-Resistenzen verlängern den Kampf.',
'E-Dodge/Stun, Q-Zugriff, R-Resistenzen und Passive-AS.',
'E beendet und Q offensiv verbraucht. Kurz handeln, bevor sein nächstes E bereit ist.',
'Low-HP-Heilung gegen aktives E erzwingen; lange R-Reise in Dodge; nach Itemrückstand denselben frühen Statcheck wiederholen.',
'Eigene Seite, damit offensives Q bestrafbar wird. Bei Push-Vorteil crashen und resetten; später keine endlosen Side-Duelle erzwingen.',
'E herausziehen, mit eigener E/Fear überbrücken. Danach Auto–Q–Auto für PTA; R nur nach Dodge und ohne sofortigen neuen Stun.',
'1: nur in E-Pausen günstige Trades. 2: seine Haste/On-Hit verschärfen das Duell. 3: klar schwierig, Side mit Team oder Waveclear beantworten.');
add('jayce','D','D','C','PTA','ranged',
'Range und Hammer-E erschweren dauerhafte Autos. Warwick hat mit Q-Halten eine Timing-Antwort, muss aber erst schadensarm ankommen.',
'Jayce kontrolliert die Reichweite; HP erhalten, Q für sinnvolle Heil-/Tradefenster statt jeden CS.',
'Nach Hammer-E kann ein langer Kontakt entstehen. Bei bereits erreichbarem Ziel Q-Halten gegen Knockback timen; kein sicherer Trick aus der Distanz.',
'Warwick bekommt R, Jayce keinen neuen Ultimate-Button. R nach Hammer-E oder aus Fear sichern, nicht in unbekannte Distanzbewegung.',
'Beschleunigtes Q, Hammer-E, Fernkampf-W und Formwechsel.',
'Hammer-E und Fernkampf-Q verbraucht; ohne beide kann er den zweiten Kontakt schlechter verhindern.',
'Blood-Hunt-Chase durch Shockblast; W-Lauftempo im Championkampf voraussetzen; Q in falscher Form zu früh verbrauchen.',
'Eigene Seite und Minions als Poke-Schutz. Nach sicherem Crash resetten, statt ohne Mana Plates gegen zwei Formen zu erzwingen.',
'Q ausweichen, heranlaufen, Auto–Q-Halten gegen E wenn passend. Eigene E vor Burst, Fear und kurze R nach Hammer-Rückstoß.',
'1: Stride erleichtert Festhalten. 2: Armor verbessert die Ankunft. 3: 1v1 bei Kontakt spielbar; sein Poke kann den Kampf vorher entscheiden.');
export {rows,add};
