import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
const base=process.env.TEST_URL||'http://127.0.0.1:8080';
const errors=[];
await mkdir('test-results',{recursive:true});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base);await page.locator('#results .card').first().waitFor();
 await page.locator('input[name=q]').fill('cho gath');assert.equal(await page.locator('#results .card').count(),1);
 await page.locator('input[name=q]').fill('aatrox');await page.locator('#results .card').click();
 await page.locator('.team-toggle').click();
 await page.locator('#team-result h2').waitFor();
 for(const [role,id]of [['jungle','elise'],['mid','syndra'],['adc','ziggs'],['support','lux']])await page.locator(`[data-role="${role}"]`).selectOption(id);
 await page.locator('#team-result h2').waitFor();
 assert.equal(await page.locator('#team-result > .team-build > .team-item').count(),6);
 const ap=await page.locator('#team-result > .team-build').innerText();
 for(const [role,id]of [['jungle','masteryi'],['mid','zed'],['adc','jinx'],['support','pyke']])await page.locator(`[data-role="${role}"]`).selectOption(id);
 await page.locator('#team-result h2').waitFor();
 const ad=await page.locator('#team-result > .team-build').innerText();assert.notEqual(ap,ad);
 await page.screenshot({path:'test-results/desktop.png',fullPage:true});
 await page.screenshot({path:'test-results/desktop-viewport.png'});
 await page.reload();await page.locator('#team-result h2').waitFor();assert.equal(await page.locator('[data-role="adc"]').inputValue(),'jinx');
 await page.locator('[data-champion="warwick"]').click();
 await page.locator('.team-shell:not([open])').waitFor();await page.locator('.team-toggle').click();await page.locator('#team-result h2').waitFor();
 assert.match(await page.locator('h1').innerText(),/Aatrox/);
 await page.locator('[data-lane="adc"]').click();
 await page.locator('.team-toggle').click();await page.locator('[data-role="adc"]').selectOption('vayne');
 await page.locator('#team-result h2').waitFor();assert.equal(await page.locator('[data-role="adc"]').inputValue(),'vayne');
 await page.locator('#team-reset').click();await page.getByText('Wähle deinen Lane-Gegner, um').waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.locator('[data-role="adc"]').selectOption('caitlyn');await page.locator('#team-result h2').waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile layout must not overflow');
 await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/mobile-viewport.png'});
 await page.locator('[data-role="adc"]').focus();await page.keyboard.press('Tab');
 assert.ok(await page.evaluate(()=>document.activeElement?.tagName==='SELECT'));
 assert.deepEqual(errors,[]);
 console.log('Browser checks passed: search, team changes, persistence, champion/lane switch, reset, mobile, keyboard, no JS errors.');
}finally{await browser.close();}
